### ISSUE TITLE
libffi.so dependency on zlinux HotSpot builds builds

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#1058]
The openjdk builds on zlinux require libffi.so.4.

At the moment it seems like not all machines have the `libffi` package installed. This should be added to the ansible playlists and all the machines (`build-marist-s390x-rhel-6` is the most recent one I've ran on)

There is another issue whereby on Ubuntu 16 and RHEL7 the only `libffi` in the default repositories is `libffi.so.6` so the builds don't work out of the box - SLES12 is ok - but that will be s separate issue to address I suspect.

```
$ jdk8u144-b01/bin/java -version
Error: dl failure on line 893
Error: failed /dev/shm/y/jdk8u144-b01/jre/lib/s390x/server/libjvm.so, because libffi.so.4: cannot open shared object file: No such file or directory
```

**Comment by M-Davies** [comment]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-hotspot/ looks happier now. @sxa can this be closed?

**Comment by sxa** [comment]
This issue was visible as an end-user, not necessarily as part of the build process in the pipelines. It will need to be checked out.

**Comment by karianna** [comment]
@fjeremic - Are you able to test our latest builds?

**Comment by fjeremic** [comment]
> @fjeremic - Are you able to test our latest builds?

I've just verified. The issue appears to be resolved on my end. Thanks!

**Comment by adamfarley** [comment]
This issue appears to be back, example:

```
Error: failed /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-s390x-temurin_SmokeTests/openjdkbinary/j2sdk-image/jre/lib/s390x/server/libjvm.so, because libffi.so.6: cannot open shared object file: No such file or directory
```

However, it only happens on:
- [test-marist-sles12-s390x-2](https://ci.adoptium.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-temurin_SmokeTests/150/)
- [test-marist-sles15-s390x-2](https://ci.adoptium.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-temurin_SmokeTests/148/)
- [test-docker-sles15-s390x-1](https://ci.adoptium.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-temurin_SmokeTests/143/).

The following machines appear unaffected:
- [test-marist-rhel7-s390x-2](https://ci.adoptium.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-temurin_SmokeTests/149/)
- [test-marist-rhel8-s390x-2](https://ci.adoptium.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-temurin_SmokeTests/147/)
- [test-marist-ubuntu2004-s390x-1](https://ci.adoptium.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-temurin_SmokeTests/146/)

Perhaps the package wasn't added to the ansible playbook for sles? Checking...

**Comment by adamfarley** [comment]
That does seem to be the case. The [Ubuntu playbook](https://github.com/adoptium/infrastructure/blob/40fbb033244ea606f791dd027114b5f7e18f5c09/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/Ubuntu.yml) has libffi-dev in the build_tool_packages list, but the [SLES playbook](https://github.com/adoptium/infrastructure/blob/40fbb033244ea606f791dd027114b5f7e18f5c09/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/SLES.yml) does not.

Will check the SLES website to make sure the package exists there before making a PR, and subsequently asking our infrastructure experts for an ansible re-run on all the sles zlinux machines.

**Comment by adamfarley** [comment]
Hmm, it appears SLES doesn't have libffi6 ([Link](https://scc.suse.com/packages?name=SUSE%20Linux%20Enterprise%20Server&version=12.5&arch=s390x&query=libffi&module=)). As Shelley mentioned, we've avoided this problem in the past by symlinking libffi6 to libffi4. Maybe we can do this in the playbook? Looking into it.

**Comment by steelhead31** [comment]
Its variant based on the version of sles, sles12 only has libffi4 , sles 15 has libffi7, so I'll try symlinks, and test them, and then make the changes via the playbooks / dockerfiles as necessary based on O/S version.

**Comment by adamfarley** [comment]
Good job Scott. 👍

**Comment by adamfarley** [comment]
All of the aforementioned tests have passed, and Scott's PR has been merged. Closing as fixed.
