### ISSUE TITLE
provide (gpg ?) signed releases

### ISSUE THREAD

**Issue by altiOnGithub** [adoptium/temurin-build#1275]
Please provided code-signed releases. (checksums are good but not enough)

Currently only the following releases are signed:
* windows MSI (from 'London Jamocha Community CIC')
* deb and rpm via jfrog.io repository (https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public)

However, all .zip and .tar.gz releases which are provided via https://adoptopenjdk.net only have a checksum next to them, but no (gpg ?) signature is provided.
Or do I miss anything?
So currently we can check for integrity but not for authenticity.

Please provided signed releases on https://adoptopenjdk.net 

Thank you!

**Comment by andrew-m-leonard** [comment]
I will have a look into this.
Numerous Enterprises will only consume binaries that are digitally verifiable, eg.via pgp/gpg.
Red Hat OpenJDK jdk8/11 upstream binaries have pgp signatures for example.
eg: https://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-October/012817.html

**Comment by tellison** [comment]
Flag for TSC discussion too.

**Comment by aahlenst** [comment]
@andrew-m-leonard Do you still plan to work on it? Would be really useful.

**Comment by andrew-m-leonard** [comment]
@aahlenst not at the moment, so i've un-assigned myself thanks

**Comment by aahlenst** [comment]
Why this is important (apart from the immediate security benefits): It allows mirroring our binaries and consuming them from 3rd party servers. This is also required as part of our move to Eclipse. The challenge here is where to sign and how. Having key material on the build machines is undesirable. Signing on the Jenkins master might be doable, but there only seems to be a plug-in for Maven. Using an Eclipse signing service would probably be best, but those are only accessible from selected machines controlled by the Eclipse Foundation.

**Comment by bmarwell** [comment]
Related: require sigs in API: https://github.com/adoptium/api.adoptium.net/issues/138

**Comment by jerboaa** [comment]
@gdams @tellison I think it would be useful to get implemented. The question I have is does Eclipse support gpg signing tarballs/zips? If so the obvious gpg key would be the one the Eclipse Foundation. Then OpenJDK update stream leads could sign their public key.

**Comment by sxa** [comment]
This is now progressing with an intention to have something usable for the July releases:
- https://github.com/adoptium/ci-jenkins-pipelines/pull/320
- https://github.com/adoptium/ci-jenkins-pipelines/pull/337
- https://github.com/adoptium/github-release-scripts/pull/88
- https://github.com/adoptium/api.adoptium.net/pull/464

**Comment by bmarwell** [comment]
IBM releases are already signed: https://github.com/ibmruntimes/semeru17-binaries/releases/tag/jdk-17.0.3%2B7_openj9-0.32.0.
