### ISSUE TITLE
Build date is not correct (lies in the future) for nightly builds

### ISSUE THREAD

**Issue by ghost** [adoptium/temurin-build#1456]
It looks like something is off when determining the build date used for naming the nightly release binaries. See for example: https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/tag/jdk13u-2020-12-29-10-47

**Comment by sxa555** [comment]
2020 instead of 2019 ... That's odd ...

**Comment by sxa555** [comment]
Ah - it's due to the scripts using `YYYY` as the date format instead of `yyyy`:
```
[sxa@localhost bin]$ cat tz.groovy
println new Date();
println new Date().format("YYYY-MM-dd-HH-mm");
println new Date().format("YYYY-MM-dd-HH-mm", TimeZone.getTimeZone("UTC"));
println new Date().format("dd/MMM/yyyy - YYYY");
[sxa@localhost bin]$ ./groovy tz.groovy
Tue Dec 31 12:03:48 GMT 2019
2020-12-31-12-03
2020-12-31-12-03
31/Dec/2019 - 2020
[sxa@localhost bin]$ 
```

**Comment by smlambert** [comment]
Still seeing future dates in openjdk -version output July 16, 2024 for a build that ran June 26th, example from https://ci.adoptium.net/job/Test_openjdk21_hs_sanity.perf_aarch64_linux/241/console which is using JDK binary from recent build https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-aarch64-temurin/211/ (June 26, 2024):

```
16:38:54  =JAVA VERSION OUTPUT BEGIN=
16:38:54  openjdk version "21.0.4-beta" 2024-07-16
16:38:54  OpenJDK Runtime Environment Temurin-21.0.4+6-202406261902 (build 21.0.4-beta+6-ea)
16:38:54  OpenJDK 64-Bit Server VM Temurin-21.0.4+6-202406261902 (build 21.0.4-beta+6-ea, mixed mode, sharing)
16:38:54  =JAVA VERSION OUTPUT END=
```

**Comment by sxa** [comment]
@smlambert If you're referring to the end of the second line in the output I believe that comes from upstream openjdk as an expected release date or similar and is not something generated by us. This issue was originally related to the time stamps we published under to the `-binaries` releases which is different (and resolved, and now superceded by the ea-tagged builds)

**Comment by smlambert** [comment]
Thanks, so in TRSS, we need to change what we are parsing and taking as build date, as I believe we are using the 2nd line rather than extracting build date from 3 or 4th line or some other metadata.  Will create an issue in aqa-test-tools.

**Comment by sxa** [comment]
Yeah from a temurin-build perspective if you can parse `202406261902` from your example that should be the best thing to key on 👍🏻
