### ISSUE TITLE
AdoptOpenJDK 14 JRE archives contain bin/javac

### ISSUE THREAD

**Issue by breun** [adoptium/temurin-build#1650]
* **Platform and architecture (e.g. Linux/x64**: Linux/x64 (others possibly also affected, but not checked)

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**: 14+36, 14+36.1

* **Variant e.g. HotSpot or OpenJ9**: all

* **Have you tested it with other vendors' java**: No

* **Steps to reproduce**: Download and extract the current  [HotSpot](https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14%2B36/OpenJDK14U-jre_x64_linux_hotspot_14_36.tar.gz), [OpenJ9](https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14%2B36.1_openj9-0.19.0/OpenJDK14U-jre_x64_linux_openj9_14_36_openj9-0.19.0.tar.gz) and [OpenJ9 Large Heap](https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14%2B36.1_openj9-0.19.0/OpenJDK14U-jre_x64_linux_openj9_linuxXL_14_36_openj9-0.19.0.tar.gz) JRE archives for AdoptOpenJDK 14.

* **Error messsage and/or description of what is not working as expected**: The archives contain `bin/javac`, which I don't expect to find in a JRE archive. `bin/javac` also doesn't seem to present in the equivalent archives for Java 13.

**Comment by keithc-ca** [comment]
Perhaps our efforts should be focussed on making https://github.com/AdoptOpenJDK/jlink.online the source of right-sized Java packages. The JRE links at https://adoptopenjdk.net/ could refer to the appropriate resource at jlink.online.

**Comment by breun** [comment]
@sxa555 Thanks for checking, I indeed hadn’t checked HotSpot builds (added that to the ticket description now).

I also haven’t checked builds for other platforms, but I guess the issue is not limited to Linux/x64 either.

**Comment by karianna** [comment]
TSC voted to build jlinked bundles for 11, 14 and tip - working name `adopt bundle`.  We will host these *alongside* the legacy jre bundles for 11 and 14.

A decision will be made on 15+ but as the legacy jre target is no longer valid we may on ly produce 'adopt bundles' going forward.

**Comment by karianna** [comment]
We'll have to do this after July CPU release

**Comment by mbien** [comment]
bin/java might require javac for JEP330 "Launch Single-File Source-Code Programs" which added another way of running java 11+ programs.

**Comment by gdams** [comment]
Closing as JDK14 is long out of support now
