### ISSUE TITLE
OpenJDK binaries depend on system zlib

### ISSUE THREAD

**Issue by izbyshev** [adoptium/temurin-build#1951]
* **Platform and architecture**: Linux/all

* **Java version**: 9 and above

* **Variant e.g. HotSpot or OpenJ9**: Tested on HotSpot

* **Have you tested it with other vendors' java**: Upstream (RedHat) binaries distributed by AdoptOpenJDK have this problem too

The dependency on system zlib can be easily verified on glibc-based systems:
```
LD_DEBUG=libs openjdk-11.0.7+10-jre/bin/java -version |& grep libz.so
     20167:     find library=libz.so.1 [0]; searching
     20167:       trying file=/home/test/openjdk-11.0.7+10-jre/bin/../lib/jli/tls/haswell/x86_64/libz.so.1
     20167:       trying file=/home/test/openjdk-11.0.7+10-jre/bin/../lib/jli/tls/haswell/libz.so.1
     20167:       trying file=/home/test/openjdk-11.0.7+10-jre/bin/../lib/jli/tls/x86_64/libz.so.1
     20167:       trying file=/home/test/openjdk-11.0.7+10-jre/bin/../lib/jli/tls/libz.so.1
     20167:       trying file=/home/test/openjdk-11.0.7+10-jre/bin/../lib/jli/haswell/x86_64/libz.so.1
     20167:       trying file=/home/test/openjdk-11.0.7+10-jre/bin/../lib/jli/haswell/libz.so.1
     20167:       trying file=/home/test/openjdk-11.0.7+10-jre/bin/../lib/jli/x86_64/libz.so.1
     20167:       trying file=/home/test/openjdk-11.0.7+10-jre/bin/../lib/jli/libz.so.1
     20167:       trying file=/home/test/openjdk-11.0.7+10-jre/bin/../lib/tls/haswell/x86_64/libz.so.1
     20167:       trying file=/home/test/openjdk-11.0.7+10-jre/bin/../lib/tls/haswell/libz.so.1
     20167:       trying file=/home/test/openjdk-11.0.7+10-jre/bin/../lib/tls/x86_64/libz.so.1
     20167:       trying file=/home/test/openjdk-11.0.7+10-jre/bin/../lib/tls/libz.so.1
     20167:       trying file=/home/test/openjdk-11.0.7+10-jre/bin/../lib/haswell/x86_64/libz.so.1
     20167:       trying file=/home/test/openjdk-11.0.7+10-jre/bin/../lib/haswell/libz.so.1
     20167:       trying file=/home/test/openjdk-11.0.7+10-jre/bin/../lib/x86_64/libz.so.1
     20167:       trying file=/home/test/openjdk-11.0.7+10-jre/bin/../lib/libz.so.1
     20167:       trying file=/lib/x86_64-linux-gnu/libz.so.1
     20167:     calling init: /lib/x86_64-linux-gnu/libz.so.1
     20167:     calling fini: /lib/x86_64-linux-gnu/libz.so.1 [0]
```

This dependency reduces the otherwise good OpenJDK portability for headless use cases, in particular, in chroots and containers, where zlib might not be present.

I suspect that this issue may be caused by confusing/buggy help text of the upstream configure: it claims that the bundled zlib is used by default, but in fact it uses the system one on Linux if it's present: https://hg.openjdk.java.net/jdk-updates/jdk14u/file/452c05ce40d2/make/autoconf/lib-bundled.m4#l173

Could you explicitly set `--with-zlib=bundled` when configuring OpenJDK?

**Comment by sxa** [comment]
Since most other distributors of OpenJDK ship with the same external zlib dependency (I've checked zulu and liberica 11 and OP has checked our upstreams) I'd be somewhat reluctant to change it, but it's certainly worth floating the idea around ...

FYI @AdoptOpenJDK/tsc

**Comment by aahlenst** [comment]
I like to hear more about the rationale.

I only see arguments against it: With bundled libraries, I've to wait for the next quarterly release to get security updates. Further, I do not understand why not having zlib in chroots/containers is a problem. There are other libraries that OpenJDK needs that aren't bundled either.

**Comment by izbyshev** [comment]
> I only see arguments against it: With bundled libraries, I've to wait for the next quarterly release to get security updates

Security is a classic argument against linking dependencies statically, but its relevance depends on the goals of a particular distributor. Linux distributions usually do care about this and try to ensure that software packages use libraries provided by the distro, and OpenJDK is not an exception here. But standalone OpenJDK distributions that I know of have never been in this camp. In particular, AdoptOpenJDK doesn't set any `with-` options in [sbin/build.sh](https://github.com/AdoptOpenJDK/openjdk-build/blob/93fc3c34ed4c5814da1d2c11b84d3906eec9c457/sbin/build.sh) for libraries [bundled by default in OpenJDK](https://github.com/openjdk/jdk14u/blob/7a3bf58b8ad2c327229a94ae98f58ec96fa39332/make/autoconf/lib-bundled.m4#L29). The same is true for other standalone distros I've used, including Zulu and Sun/Oracle ones. So I'm not sure why you bring the security argument against zlib alone.

Moreover, the docs explaining that the system zlib may be used on Linux despite what [`configure --help` claims](https://github.com/openjdk/jdk14u/blob/7a3bf58b8ad2c327229a94ae98f58ec96fa39332/make/autoconf/lib-bundled.m4#L158) were [committed only 14 month ago](https://github.com/openjdk/jdk14u/commit/fd5806017991), though this was true since OpenJDK 9. So this whole situation looks more like accidental reliance on upstream defaults rather than a conscious decision, though I admit that I don't know why the upstream default has been changed. 

>  Further, I do not understand why not having zlib in chroots/containers is a problem. There are other libraries that OpenJDK needs that aren't bundled either.

I referred to the headless use case specifically in my report. For that, the only OpenJDK dependencies in the default configuration are the C library and zlib. All other dependencies are listed in https://github.com/openjdk/jdk14u/blob/7a3bf58b8ad2c/doc/building.md#external-library-requirements and are irrelevant for this use case. At my organization we bundle OpenJDK with our software which runs in environments that we can't control or impose requirements on, and even users often can't change those environments (think chroots used to build OS distros). So zlib dependency _is_ a problem, and in case of AdoptOpenJDK the current workaround is to put a copy of `libz.so.1` into `lib` inside the JRE and have it picked by the dynamic loader automatically due to `RPATH/RUNPATH` settings in OpenJDK executables.

**Comment by sxa** [comment]
I was thinking about this recently and I'm increasingly leaning towards using the bundled `zlib` as far as possible for a few reasons:
- Whether the "bundled" `zlib` needs to be updated (i.e. whether any issue really affects java) should be done by the security team and if it warrants it then it can be patched as is seen fit based on the severity.
- It will avoid any inconsistencies in behavior (critical for compliance tests)
- At the moment we are [quite inconsistent in our builds](https://github.com/adoptium/temurin-build/issues/3013#issuecomment-1598452378) and this would be an opportunity to make things a lot more consistent.

**Comment by sxa** [comment]
Noting that this has been implemented for JDK21 at https://github.com/adoptium/temurin-build/pull/3399
The intention is to look at doing this for other versions which will allow us to be consistent in the bundling across all platform and versions.

**Comment by izbyshev** [comment]
Thank you for the fix!

**Comment by gredler** [comment]
Please note: this change removed the option to use `LD_LIBRARY_PATH` / `LD_PRELOAD` with Temurin builds to improve Java runtime performance. I'm not sure if this was considered during the decision-making process.

https://mail.openjdk.org/pipermail/core-libs-dev/2020-July/067868.html

https://www.youtube.com/watch?v=x2cJ08p2l5k

https://aws.amazon.com/blogs/opensource/improving-zlib-cloudflare-and-comparing-performance-with-other-zlib-forks/

**Comment by T3rm1** [comment]
@sxa Any chance to revert this for JDK 25 again? Please use the system's zlib by default so that it's possible to benefit from other libraries that offer huge performance gains over the bundled lib. 
Amazon Corretto uses [`--with-zlib=system`](https://github.com/corretto/corretto-21/blob/a5b14e23a3a9e1edc3da8efa24052db1039b5082/installers/linux/universal/tar/build.gradle#L80)

Here is a great comparison over the potential gains: https://github.com/simonis/zlib-bench/blob/master/Results-ojdk.md
