### ISSUE TITLE
makejdk-any-platform.sh does not complete if ARCHITECTURE not defined

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#2057]
The following happens if you run makejdk-any-platform.sh when no `ARCHITECTURE` environment variable is set (Reproduced on a CentOS6 system)
```
Creating jdk image
Creating legacy jre image
Stopping sjavac server
Finished building targets 'product-images legacy-jre-image test-image' in configuration 'linux-x86_64-normal-server-release'
Should have the source, I'm at /home/sxa/openjdk-build/workspace/home/sxa/jdk11/src/src
'/home/sxa/openjdk-build/workspace/home/sxa/jdk11/src/src/build/linux-x86_64-normal-server-release/images/jdk' found
/home/sxa/openjdk-build/sbin/build.sh: line 519: ARCHITECTURE: unbound variable
```

**Comment by sophia-guo** [comment]
This could also be reproduced on ubuntu. For build-jdk action https://github.com/Adoptopenjdk/build-jdk if ARCHITECTURE environment variable is not set it happened to both ubuntu and mac. 
https://github.com/sophia-guo/build-jdk-original/issues/6

**Comment by hendrikebbers** [comment]
@sxa What do you expect in such case? If you add this information we can convert this in a good first issue :)

**Comment by sxa** [comment]
I woud expect either a quick abort, or for it to be autodetected based on uname.

**Comment by sophia-guo** [comment]
Believe it's fixed by https://github.com/adoptium/temurin-build/pull/2478/, close it.
