### ISSUE TITLE
build.sh does not fail if createArchive() fails to produce an archive

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2261]
**What are you trying to do?**
Run a build testing a new openjdk-build change

**Expected behaviour:**
Build Green and produces an archive

**Observed behaviour:**
Build Green but bug in openjdk-build meant createArchive() had actually failed, build should have Failed
PR build tester thus did not fail

**Any other comments:**

**Comment by andrew-m-leonard** [comment]
PR build tester probably needs to be a little more robust on what archives are produced?

**Comment by sxa** [comment]
Should be fixed by the above PR. We can re-open if that turns out not to be the case :-)
