### ISSUE TITLE
When build fails, fail and don't try to do other stuff :-)

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#2546]
Running a build which had a compile failure in it. It says
```
/home/jenkins/openjdk-build/build-farm/workspace/build/src//make/Main.gmk:109: recipe for target 'hotspot-only' failed
make: *** [hotspot-only] Error 2
OpenJDK make failed, archiving make failed logs
```
All good so far, except that it continues and tries to create a tarball which produces nothing which may slightly confuse the user. This should probably skip the gzip step leaving the failure messages as clear as possible at the end of the log:
```
/home/jenkins/openjdk-build/build-farm/workspace/build/src//make/Main.gmk:109: recipe for target 'hotspot-only' failed
make: *** [hotspot-only] Error 2
OpenJDK make failed, archiving make failed logs
Copying build.log to AdoptOpenJDKLogsArchive
Archiving the build OpenJDK image and compressing with gzip

real	0m0.009s
user	0m0.011s
sys	0m0.004s
Your final archive was created at /home/jenkins/openjdk-build/build-farm/workspace/build/src/build/linux-aarch64-normal-server-release/OpenJDK.tar.gz
Moving the artifact to /home/jenkins/openjdk-build/build-farm/workspace/target/
Failed to make the JDK, exiting
```

**Comment by SehrishHussain** [comment]
@sxa I will be using Docker for the first time you think it's a beginner friendly issue to start with. I'm using Win7, for which Docker Toolbox is required, will it do the job?

**Comment by sxa** [comment]
I'll be honest I don't know as I have a Linux laptop :-) But if docker toolbox will let you run the Linux docker images it should be ok though.

**Comment by zdtsw** [comment]
> The important script for this will be [build.sh](https://github.com/adoptium/temurin-build/blob/master/sbin/build.sh) - you can see in there where the `OpenJDK make failed, archiving make failed logs` message is produced. If you want to replicate this, you should be able to start a build docker container:
> 
> ```
>   docker run -it adoptopenjdk/centos6_build_image
> ```
> 
> Clone this repository:
> 
> ```
>    git clone https://github.com/adoptium/temurin-build
> ```
> 
> Then run a build:
> 
> ```
>    cd build-farm
>    ./make-adopt-build-farm.sh jdk11u
> ```
> 
> However since in most cases it passes, that won't show a problem, so I'd suggest doing something like replacing [this line](https://github.com/adoptium/temurin-build/blob/732e6ff631aba3779d6a8dcf7268cc6538e261c7/sbin/build.sh#L556) with `/bin/false` after you've done the `git clone` command in the docker container which will force it to trigger the error condition, and see if we can modify the process to stop immediately. Good luck!

Not sure using "/bin/false" will expose the error. executeTemplatedFile() will not catch exit 1 from "false". 
Feel like something caused configure-and-build.sh exit non-2 non-3. 
Maybe worth adding debug to see what exitCode return exactly.

**Comment by steelhead31** [comment]
I've managed to replicate the issue... by forcing a returncode of 3 from configure-and-build.sh

  # Execute the build passing the workspace dir and target dir as params for configure.txt
  bash "${BUILD_CONFIG[WORKSPACE_DIR]}/config/configure-and-build.sh" ${BUILD_CONFIG[WORKSPACE_DIR]} ${BUILD_CONFIG[TARGET_DIR]}
  exitCode=$?
  **exitCode=3**

Which gives me the following..

Finished building targets 'product-images legacy-jre-image test-image static-libs-image' in configuration 'linux-x86_64-normal-server-release'
OpenJDK make failed, archiving make failed logs
Copying build.log to TemurinLogsArchive
Copying make-support/failure-logs to TemurinLogsArchive

For some reason, it then goes on to this...

_Archiving the build OpenJDK image and compressing with pigz

real	0m0.004s
user	0m0.003s
sys	0m0.002s
Your final archive was created at /temurin-build/build-farm/workspace/build/src/build/linux-x86_64-normal-server-release/OpenJDK.tar.gz
Moving the artifact to /temurin-build/build-farm/workspace/target/
_

Before finally hitting this...

Failed to make the JDK, exiting

Now to figure out what its doing here.

**Comment by steelhead31** [comment]
@sxa , I believe I have found the root cause of the erroneous messages...

When the configure-and-build.sh script exits with status 3...

Line 580 ( build.sh )

_if [ "${exitCode}" -eq 3 ]; then
    createOpenJDKFailureLogsArchive
    echo "Failed to make the JDK, exiting"
    exit 1_

It jumps to function createOpenJDKFailureLogsArchive()

_596 createOpenJDKFailureLogsArchive() { 
...
625    # Archive logs
626    local makeFailureLogsName=$(echo "${BUILD_CONFIG[TARGET_FILE_NAME]//-jdk/-makefailurelogs}")
627    createArchive "${adoptLogArchiveDir}" "${makeFailureLogsName}"_

Which calls the createArchive function.. which has very specific debug messages for a general function...

1403 createArchive() {
  repoLocation=$1
  targetName=$2

  archiveExtension=$(getArchiveExtension)

  createOpenJDKArchive "${repoLocation}" "OpenJDK"
  archive="${PWD}/OpenJDK${archiveExtension}"

  **echo "Your final archive was created at ${archive}"

  echo "Moving the artifact to ${BUILD_CONFIG[WORKSPACE_DIR]}/${BUILD_CONFIG[TARGET_DIR]}"**
  mv "${archive}" "${BUILD_CONFIG[WORKSPACE_DIR]}/${BUILD_CONFIG[TARGET_DIR]}/${targetName}"
}

Id recommend either making the messages more generic, or having a different function to report the error archives. Any thoughts ?

**Comment by steelhead31** [comment]
@zdtsw it does look like both these issues are related. In this bug the failure archive for the logs is created , but the misleading error messages look like the build itself is successful. The text on the CreateArchive function is misleading, and should be clearer that in the case of failure, its a failure.

**Comment by sxa** [comment]
Yeah the fact that `createArchive` is using `createOpenJDKArchive` isn't ideal since it's error message is really generic so always outputting `Archiving the build OpenJDK image` is somewhat misleading since it's used for things that aren't what I'd consider to be build images in the cae where it hasn't managed to build. Given that much of the text that invokes that function will give an indication of what it's doing anyway we could just remove that message entirely from `createOpenJDKArchive`. I think it was only ever there for information to say whether `pigz` instead of `gzip` had been found, so it's more of a debug statement ...

**Comment by sxa** [comment]
Fixed as part of https://github.com/adoptium/temurin-build/pull/2888
