### ISSUE TITLE
openj9-0.26.0-m2 triage

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2556]
### jdk-16
**aarch64_linux**
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.functional_aarch64_linux/56/consoleFull
```
12:30:03  java.lang.AssertionError: Free Physical Memory size cannot be greater than total Physical Memory Size. expected [false] but found [true]
```
**Raised:** https://github.com/eclipse/openj9/issues/12353
(Also: https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.functional_x86-64_linux/57/#showFailuresLink)

https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.openjdk_aarch64_linux/19/#showFailuresLink
javax/imageio/stream/DeleteOnExitTest.sh.DeleteOnExitTest : **Raised:** https://github.com/eclipse/openj9/issues/12354
javax/imageio/plugins/shared/ImageWriterCompressionTest.java.ImageWriterCompressionTest : Existing: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2373
(Also: https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.openjdk_x86-64_linux/20/#showFailuresLink)
security/infra/java/security/cert/CertPathValidator/certification/ComodoCA.java.ComodoCA : Existing: https://github.com/AdoptOpenJDK/openjdk-build/issues/2527
(Also: https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.openjdk_ppc64le_linux/17/#showFailuresLink)

https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.perf_aarch64_linux/16/consoleFull
```
11:00:45  Benchmark 'gauss-mix' failed with exception:
11:00:45  java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.lang.Object[] java.util.ArrayList.elementData accessible: module java.base does not "opens java.util" to unnamed module @be30f191
11:00:45  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
11:00:45  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
11:00:45  	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
11:00:45  	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
```
Existing: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2253
(Also: https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.perf_ppc64le_linux/16/console, https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.perf_s390x_linux/16/console, https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.perf_x86-64_linux/16/console, https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.perf_x86-64_mac/16/console, https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_sanity.perf_x86-64_windows/52/console, https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.perf_x86-64_windows/16/console)

**ppc64le_linux**
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_sanity.openjdk_ppc64le_linux/54/
java/lang/invoke/lambda/LambdaFileEncodingSerialization.java.LambdaFileEncodingSerialization: Existing: https://github.com/eclipse/openj9/issues/11915
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessInt.java: timeout: **Raised:** https://github.com/eclipse/openj9/issues/12355

**s390x_linux**
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.openjdk_s390x_linux/16/consoleFull:
com/sun/jndi/dns/ConfigTests/Timeout.java.Timeout Existing: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2360

**x86-64_linux**
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.functional_x86-64_linux/57/consoleFull:
testSoftMxDisclaimMemory_1: Memory didn't release back to OS
**Raised**: https://github.com/eclipse/openj9/issues/12356

https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.openjdk_x86-64_linux/20/#showFailuresLink
sun/net/www/protocol/https/HttpsURLConnection/PostThruProxyWithAuth.java.PostThruProxyWithAuth: Existing: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2137#issuecomment-758374845
java/nio/file/attribute/BasicFileAttributeView/UnixSocketFile.java.UnixSocketFile : Existing: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2137#issuecomment-758374845
sun/security/krb5/auto/ReplayCacheTestProc.java.ReplayCacheTestProc, sun/security/krb5/auto/ReplayCacheTestProcWithMD5.java.ReplayCacheTestProcWithMD5 : Existing: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2349

**x86-64_windows**
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_sanity.functional_x86-64_windows/52/consoleFull
cmdLineTester_callsitedbgddrext_openj9_0:
```
15:45:42  Testing: Remove shared cache
15:45:42  Test start time: 2021/04/05 22:45:42 China Standard Time
15:45:42  Running command: "C:/Users/Jenkins/workspace/Test_openjdk16_j9_sanity.functional_x86-64_windows/openjdkbinary/j2sdk-image\\bin\\java"   -Xshareclasses:name=shareddbgext,destroy
15:45:42  Time spent starting: 3 milliseconds
15:45:42  Time spent executing: 95 milliseconds
15:45:42  Test result: FAILED
15:45:42  Output from test:
15:45:42   [ERR] JVMSHRC241E Error: unable to delete shared class cache file
15:45:42   [ERR] JVMSHRC336E Port layer error code = -102
15:45:42   [ERR] JVMSHRC337E Platform error message: (5) Access is denied.
15:45:42   [ERR] JVMSHRC430I Failed to remove current generation of shared class cache "shareddbgext"
15:45:42  >> Success condition was not found: [Output match: destroyed]
```
Re-run: https://ci.adoptopenjdk.net/job/Grinder/8145/console **Green**

Win64 sanity.openjdk aborted after 10hrs, re-running, on 2 nodes, might be Azure cloud specific: https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_sanity.openjdk_x86-64_windows/55/ **Green** on build-alibaba-win2012r2-x64-2
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_sanity.openjdk_x86-64_windows/54/ **Aborted after 10hrs** on test-azure-win2012r2-x64-1

**AIX**
Test_openjdk16_j9_extended.functional_ppc64_aix re-run: https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.functional_ppc64_aix/53/ **Green**

Test_openjdk16_j9_extended.openjdk_ppc64_aix re-run:
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.openjdk_ppc64_aix/17/

**Comment by andrew-m-leonard** [comment]
### jdk-11
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.functional_aarch64_linux/135/#showFailuresLink
org.openj9.test.management.TestOperatingSystemMXBean.runTestOSMXBean Existing: https://github.com/eclipse/openj9/issues/12353

https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.openjdk_aarch64_linux/16/#showFailuresLink
javax/imageio/plugins/shared/ImageWriterCompressionTest.java.ImageWriterCompressionTest : Existing: AdoptOpenJDK/openjdk-tests#2373
javax/imageio/AppletResourceTest.java.AppletResourceTest : Existing: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2357

https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.perf_aarch64_linux/15/ : Abort 10hrs on build-docker-ubuntu1804-armv8-6: Re-run on test-docker-ubuntu1604-armv8l-2: https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.perf_aarch64_linux/16/

**Comment by andrew-m-leonard** [comment]
### jdk-8
Test_openjdk8_j9_extended.functional_ppc64_aix re-run: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.functional_ppc64_aix/118/

**Comment by lumpfish** [comment]
jdk8:
Build job
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-aarch64-openj9/250/consoleFull
Test jobs
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.functional_aarch64_linux/116/consoleFull - UNSTABLE
https://github.com/eclipse/openj9/issues/12038
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.openjdk_aarch64_linux/13/consoleFull - UNSTABLE
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2351
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2349
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2357
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.perf_aarch64_linux/13/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.system_aarch64_linux/199/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_aarch64_linux/114/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux/205/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.perf_aarch64_linux/148/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.system_aarch64_linux/199/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.functional_aarch64_linux/13/consoleFull - SUCCESS

Build job
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-ppc64le-openj9/932/consoleFull
Test jobs
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.functional_ppc64le_linux/113/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.openjdk_ppc64le_linux/19/consoleFull - UNSTABLE
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2351
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.perf_ppc64le_linux/15/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.system_ppc64le_linux/485/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_ppc64le_linux/113/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux/490/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.perf_ppc64le_linux/157/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.system_ppc64le_linux/491/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.functional_ppc64le_linux/33/consoleFull - SUCCESS

Build job
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-openj9/947/consoleFull
Test jobs
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.functional_s390x_linux/116/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.openjdk_s390x_linux/19/consoleFull - UNSTABLE
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2351
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.perf_s390x_linux/15/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.system_s390x_linux/476/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_s390x_linux/116/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux/480/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.perf_s390x_linux/159/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.system_s390x_linux/481/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.functional_s390x_linux/31/consoleFull - SUCCESS

Build job
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-openj9/990/consoleFull
Test jobs
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.functional_x86-64_linux/114/consoleFull - UNSTABLE
https://github.com/eclipse/openj9/issues/10732
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.openjdk_x86-64_linux/29/consoleFull - UNSTABLE
https://github.com/eclipse/openj9/issues/12038
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.perf_x86-64_linux/13/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.system_x86-64_linux/479/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_x86-64_linux/117/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/497/consoleFull - UNSTABLE
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2469
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.perf_x86-64_linux/486/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.system_x86-64_linux/482/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.functional_x86-64_linux/355/consoleFull - SUCCESS

Build job
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-mac-x64-openj9/898/consoleFull
Test jobs
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.functional_x86-64_mac/121/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.openjdk_x86-64_mac/30/consoleFull - ABORTED
Resubmitted as https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/8156
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.perf_x86-64_mac/16/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.system_x86-64_mac/494/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_x86-64_mac/121/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/499/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.perf_x86-64_mac/165/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.system_x86-64_mac/498/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.functional_x86-64_mac/33/consoleFull - SUCCESS

Build job
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-openj9/1034/consoleFull
Test jobs
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.functional_x86-64_windows/109/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.openjdk_x86-64_windows/20/consoleFull - UNSTABLE
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2351
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2470
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2356
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.perf_x86-64_windows/15/consoleFull - UNSTABLE
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2471
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.system_x86-64_windows/469/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_x86-64_windows/108/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-64_windows/476/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.perf_x86-64_windows/150/consoleFull - UNSTABLE
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2471
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.system_x86-64_windows/474/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.functional_x86-64_windows/30/consoleFull - SUCCESS

Build job
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-openj9/887/consoleFull
Test jobs
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.functional_x86-32_windows/109/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.openjdk_x86-32_windows/18/consoleFull - UNSTABLE
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2351
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2470
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2356
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.perf_x86-32_windows/15/consoleFull - UNSTABLE
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2471
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.system_x86-32_windows/150/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_x86-32_windows/110/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-32_windows/475/consoleFull - UNSTABLE
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.perf_x86-32_windows/151/consoleFull - UNSTABLE
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2471
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.system_x86-32_windows/150/consoleFull - SUCCESS
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.functional_x86-32_windows/31/consoleFull - SUCCESS
