### ISSUE TITLE
Miscellaneous Minor Doc Enhancements and Fixes

### ISSUE THREAD

**Issue by M-Davies** [adoptium/temurin-build#2557]
**👾 Description of the issue**
After the effort to [split openjdk-build into two](https://github.com/AdoptOpenJDK/openjdk-build/pull/2463), we find ourselves with some documentation that is out of date, jumbled or outright wrong in some places. This issue intends to amend these irregularities by tidying up the visual features of this repo. Some ideas:
- We have a lot of `.md` files at the root of this repo that could be moved into their own directory (called `docs/` maybe?). NOTE: [SECURITY.md](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/SECURITY.md) and [LICENSE](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/LICENSE) would need to stay as they are special files that GitHub needs to have at the repository root.
- [README.md](https://github.com/AdoptOpenJDK/openjdk-build#readme) contains a few images that are invalid (i.e. they show a blank image). It would be good to have these replaced or removed.
- The Metadata section of the README file above can be removed as it is more a part of the [pipeline](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines#metadata) side of the project instead of the build side.
- [CONTRIBUTING.md](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/CONTRIBUTING.md) could be condensed down to be less wordy. It's probably quite a daunting document to read for new contributors.
- The [FAQ](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/FAQ.md#how-do-i-find-my-way-around-adoptopenjdks-build-automation-scripts) contains an error that states that the `make-adopt-build-farm.sh` script is a `G` script, not a `S` script
- There are probably more that I have missed as this was just from a quick look through.

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [x] Claim this issue: Comment below.
- [x]  Fork the repository in github by simply clicking the 'fork' button.
- [x]  Check out the forked repository
- [x]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [x]  Commit your changes.
- [x]  Start a Pull Request.
- [x]  Done 👍 Ask in comments for a review :)
- [x]  If the reviewer find some missing pieces or a problem they will start a discussion with you and describe the next steps how the problem can be solved.
- [x]  You did it 🎉 We will merge the fix in the master branch.
- [x]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by ljessicc** [comment]
Hi, I am Jessica and I'm new to contributing on projects. I'm currently looking for a first good issue to start contributing and this seems like it could be a good one. I would like to give it a go. Thank you

**Comment by smlambert** [comment]
Welcome @ljessicc !  It is now assigned to you, if you have any questions, please feel free to ask them in this issue.

**Comment by ljessicc** [comment]
Very well. Thank you

**Comment by ljessicc** [comment]
Are the images mentioned in the README.md, the links referring to [slack], [DockerFileCheck]? I have tried finding valid updated links to replace these but I haven't been able to. Should I only delete the links or the whole paragraphs pointing to them?

**Comment by ljessicc** [comment]
Actually I just noticed many of the links in the FAQ.md are invalid

**Comment by M-Davies** [comment]
> Are the images mentioned in the README.md, the links referring to [slack], [DockerFileCheck]? I have tried finding valid updated links to replace these but I haven't been able to. Should I only delete the links or the whole paragraphs pointing to them?

`DockerFileCheck` can probably be deleted, I don't think that job exists anymore after the rejig of the docker pipelines a while back. The image icon url for slack can probably be replaced by any generic one found on google. As for the actual link that the icon will take you too, it is possible to copy a link to a channel in slack by right clicking on the channel. Maybe we could replace the `https://slackin-jmnmplfpdu.now.sh/` part with whatever that link may be?

**Comment by ljessicc** [comment]
Ok. Thanks

**Comment by ljessicc** [comment]
I am done with my changes, please review

**Comment by andrew-m-leonard** [comment]
PR was merged
