### ISSUE TITLE
Problem uninstalling AOJDK 11.0.7_10 OpenJ0.20.0 (x64) LTS  in Windows 10 2H2 x64

### ISSUE THREAD

**Issue by succeedmr123** [adoptium/temurin-build#2572]
**What are you trying to do?**

-to uninstall OLD LTS (to upgrade to a current JDK 11 LTS (11.0.10_9_openj9-0.24.0.msi)) - currently the installer and the associated uninstaller is stuck, impossible to uninstall it

**Expected behaviour:**

Old 11 LTS 11.0.7_10 to be uninstalled smoothly (and replaced with the new one)

**Observed behaviour:**

old AOJDK can not be uninstalled from windows system.

When trying to circumvent by installing new, it fails the same.

It ask for .msi name AOJDK EOJ9 11.0.7_10 (x64) , and when matched - just refuse to proceeds and continues to insist that it is not the right one, although the name and variant is  the exact match of a filename -  downloaded .msi of the 11.0.7.10 build from github.

**Any other comments:**

As I noticed some sub-variants on github -  it would be good to get everything coherent and eradicate .msi uninstall problem for good.

Now, users need a solid manual removal instructions -which was somewhat impossible to find by doing the search engine query. 

Thank you.

**Comment by karianna** [comment]
@succeedmr123 Can you move this to https://github.com/adoptium/installer please?

**Comment by douph1** [comment]
Please give us some log files from the msi
>msiexec /x "C:\MyPackage\Example.msi" /L*V "C:\log\example.log"

Then try to reboot and uninstall.

**Comment by douph1** [comment]
duplicate from https://github.com/adoptium/installer/issues/318

**Comment by succeedmr123** [comment]
@karianna  

uninstall might be tied to both install and uninstall process, so it might be moved to installer as you suggested it it makes it easier
Will try to do that this afternoon -  thanks for pointing to the agreed structure
