### ISSUE TITLE
Smoke test javaVendorVersion failed with jdk8

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/temurin-build#2583]
Smoke test javaVendorVersion failed with jdk8 as no system property `java.vendor.version`

```
14:35:52  	at net.adoptopenjdk.test.VendorPropertiesTest$AdoptOpenJDKPropertiesChecks.javaVendorVersion(VendorPropertiesTest.java:162)
14:35:52  	at net.adoptopenjdk.test.VendorPropertiesTest.vmPropertiesPointToVendor(VendorPropertiesTest.java:84)
14:35:52  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-hotspot_SmokeTests/5/console

Test check javaVendorVersion by `System.getProperty("java.vendor.version")` . 

#2544 add meta data to java.vendor.version for jdk11+. Should jdk8 have system property `java.vendor.version`?  Could someone please confirm this? If not we will need to limit tests to jdk11+. Otherwise this need to be fixed.

**Comment by sophia-guo** [comment]
Similar system property `java.vendor.url.bug`, which isn't enabled for jdk8 with openj9:

15:01:28  FAILED: vmPropertiesPointToVendor
15:01:28  java.lang.AssertionError: expected [https://github.com/AdoptOpenJDK/openjdk-support/issues] but found [null]
15:01:28  	at org.testng.Assert.fail(Assert.java:96)
15:01:28  	at org.testng.Assert.failNotEquals(Assert.java:776)
15:01:28  	at org.testng.Assert.assertEqualsImpl(Assert.java:132)
15:01:28  	at org.testng.Assert.assertEquals(Assert.java:118)
15:01:28  	at org.testng.Assert.assertEquals(Assert.java:453)
15:01:28  	at org.testng.Assert.assertEquals(Assert.java:463)
15:01:28  	at net.adoptopenjdk.test.VendorPropertiesTest$AdoptOpenJDKPropertiesChecks.javaVendorUrlBug(VendorPropertiesTest.java:157)
15:01:28  	at net.adoptopenjdk.test.VendorPropertiesTest.vmPropertiesPointToVendor(VendorPropertiesTest.java:83)
15:01:28  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:01:28  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-openj9_SmokeTests/5/console

**Comment by sophia-guo** [comment]
Try openjdk8 built from upstream https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/download/jdk8u292-b09/OpenJDK8U-jdk_x64_linux_8u292b09_ea.tar.gz 

No java.vendor.version
```
jenkins@test-packet-ubuntu1604-x64-1:~/sophiag/openjdk-8u292-b09/bin$ ./java -XshowSettings

...
    java.vendor = Oracle Corporation
    java.vendor.url = http://java.oracle.com/
    java.vendor.url.bug = http://bugreport.sun.com/bugreport/
    java.version = 1.8.0_292-ea
    java.vm.info = mixed mode
...
```

Try openjdk11 built from upstream https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.11%2B8/OpenJDK11U-jdk_x64_linux_11.0.11_8_ea.tar.gz 

 java.vendor.version = 18.9

```
jenkins@test-packet-ubuntu1604-x64-1:~/sophiag/openjdk-11.0.11_8/bin$ ./java -XshowSettings
...
    java.vendor = Oracle Corporation
    java.vendor.url = https://openjdk.java.net/
    java.vendor.url.bug = https://bugreport.java.com/bugreport/
    java.vendor.version = 18.9
    java.version = 11.0.11-ea
    java.version.date = 2021-04-20
...
```

So probably for jdk8  java.vendor.version system.property is not supported. Could someone confirm that? If that is the case we could just disable test for jdk8.

**Comment by adamfarley** [comment]
According to [this issue](https://bugs.openjdk.java.net/browse/JDK-8216383), the system property "java.vendor.version" was added to JDK10 by [JEP 322](https://bugs.openjdk.java.net/browse/JDK-8192828).

Since [this list](https://openjdk.java.net/projects/jdk8/features) doesn't name JEP 322 as one of the features, I think it's a safe assumption that java.vendor.version isn't supported there.

Advocating the exclusion of this test on JDK8.
