### ISSUE TITLE
Update all references of vendor url https://adoptopenjdk.net/ to https://adoptium.net/

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/temurin-build#2589]
**Description**
Adoptium vendor url https://adoptium.net/ is available going forward we need to update AdoptOpenjdk vendor url  https://adoptopenjdk.net/ to Adoptium https://adoptium.net/

**Tips to solve this particular issue:**

To fix this issue, we need to replace `https://adoptopenjdk.net/` with `https://adoptium.net/` in the repo. Searching `https://adoptopenjdk.net/` in the repo there are 7 matches, [one](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L238) is for build parameter, [the other one ](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/test/functional/buildAndPackage/src/net/adoptopenjdk/test/VendorPropertiesTest.java#L152) is for test, 5 others are documents related.

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).  Note: that you do not need to add yourself to a Contributors.md file as outlined in the detailed instructions.

- [x] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing pieces or a problem they will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🤔❓ Questions**

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue. Please assign me this.

**Comment by himanshu007-creator** [comment]
a small doubt, <code>5 others are documents related.</code> other 5 references are in README.md only right?

**Comment by M-Davies** [comment]
> Hi, i would like to work on this issue. Please assign me this.

You're assigned 🙂 

> a small doubt, 5 others are documents related. other 5 references are in README.md only right?

There's a couple in other `.md` documents too https://github.com/AdoptOpenJDK/openjdk-build/search?q=https%3A%2F%2Fadoptopenjdk.net%2F
