### ISSUE TITLE
Update all references of support url github.com/AdoptOpenJDK/openjdk-support to github.com/adoptium/adoptium-support

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/temurin-build#2590]
**Description**
[The repository](https://github.com/AdoptOpenJDK/openjdk-support) is used to track issues raised by end-users against the adoptopenjdk binaries has been transferred to [adoptium](https://github.com/adoptium/adoptium-support) . We need update all references to adoptium. 

### **Update: only two links left see comment https://github.com/adoptium/temurin-build/issues/2590#issuecomment-926662756**

**Tips to solve this particular issue:**

To fix this issue, we need to replace `https://github.com/AdoptOpenJDK/openjdk-support` with `https://github.com/adoptium/adoptium-support` in the repo. Searching `https://github.com/AdoptOpenJDK/openjdk-support` in the repo there are 7 matches, [two of them](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L239, https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L240) are for build parameter, [one of them](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/test/functional/buildAndPackage/src/net/adoptopenjdk/test/VendorPropertiesTest.java#L157) is for test, others are documents related.

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).  Note: that you do not need to add yourself to a Contributors.md file as outlined in the detailed instructions.

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing pieces or a problem they will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🤔❓ Questions**

**Comment by ljessicc** [comment]
Hi, I could take care of this

**Comment by ljessicc** [comment]
Please review the updated support references. Thank you

**Comment by M-Davies** [comment]
Are [these](https://github.com/AdoptOpenJDK/openjdk-build/pull/2584) the references you are referring to?

**Comment by ljessicc** [comment]
@M-Davies  No, the support references.

**Comment by M-Davies** [comment]
I'm not sure what you are referring to in that case 🙂

**Comment by ljessicc** [comment]
I changed the existing URL https://github.com/AdoptOpenJDK/openjdk-support with github.com/adoptium/adoptium-support. Tried doing a pull request but was seeing a "There isn’t anything to compare" message. I merged master branch to the forked repo and did another pull request, so I hope it goes through.

**Comment by M-Davies** [comment]
Ah I see, I think you might have still been on your branch for https://github.com/AdoptOpenJDK/openjdk-build/pull/2584 when you pushed the changes that updated the URL. So now the changes you made to the URL are now included in that pull request too. It's not a problem, as I can just link that PR to this issue too.

**Comment by ljessicc** [comment]
@M-Davies Oh OK, Thank you

**Comment by sxa** [comment]
@ljessicc Are you still working on this?

**Comment by sophia-guo** [comment]
Update: some of the link has been updated. There are still two hyperlinks left in the file security/README.md.

[support-issues]: https://github.com/AdoptOpenJDK/openjdk-support/issues/13 
[tsc-decision]: https://github.com/AdoptOpenJDK/openjdk-support/issues/13#issuecomment-635400251

**Comment by totorororo** [comment]
I can work on this

**Comment by totorororo** [comment]
Please review

**Comment by smlambert** [comment]
Closed via https://github.com/adoptium/temurin-build/pull/2739
