### ISSUE TITLE
Precision enhancement to vendor version smoke test

### ISSUE THREAD

**Issue by adamfarley** [adoptium/temurin-build#2608]
***Summary***
We automatically skip the check for the vendor name in the -version output from non-Hotspot JDK8 builds in [VendorPropertiesTest.java](https://github.com/adoptium/temurin-build/blob/95b8cddd15457a115e887bace5a8faa47a89de2d/test/functional/buildAndPackage/src/net/adoptopenjdk/test/VendorPropertiesTest.java#L71).

@keith-ca has requested a modification here to make the "skip" logic more precise.

***Original Comment:***

If it's (the code that provides vendor name in JDK8 -version) only missing from OpenJ9 and JDK8, then I suggest a clearer (and more accurate) condition would be
```
    jdkVersion.usesVM(VM.OPEN9) && !jdkVersion.isNewerOrEqual(9)
```

_Originally posted by @keithc-ca in https://github.com/adoptium/temurin-build/pull/2602#discussion_r623251847_

**Comment by keithc-ca** [comment]
This seems appropriate given https://github.com/adoptium/temurin-build/pull/2602#discussion_r623245682:

> The vendor name is only absent from builds which are both OpenJ9 and JDK8.

**Comment by adamfarley** [comment]
Seems reasonable. PR raised.

https://github.com/adoptium/temurin-build/pull/2610
