### ISSUE TITLE
Add jdk17 experimental risc-v openjdk nightly based on jdk-sandbox

### ISSUE THREAD

**Issue by joeyleeeeeee97** [adoptium/temurin-build#2625]
Only experimental build and nightly tests for now, add a jdk11-riscv based on https://github.com/openjdk/jdk-sandbox/tree/riscv-port-branch.

Why we need this:
- Kepp testing openjdk riscv build quality 
- Give an internal experimental build for **developer**

**Comment by sxa** [comment]
@joeyleeeeeee97 Does this build natively or via a cross-compile? (@M-Davies do you have insight given the tag you've added?)

**Comment by sxa** [comment]
Looks like that code base id a JDK17 (as per title) rather than JDK11 as per the description so we'll ideally need to get hold of a JDK16/17 as a boot JDK before pushing this forward

**Comment by joeyleeeeeee97** [comment]
> @joeyleeeeeee97 Does this build natively or via a cross-compile? (@M-Davies do you have insight given the tag you've added?)

Cross-compile.

**Comment by joeyleeeeeee97** [comment]
> Looks like that code base id a JDK17 (as per title) rather than JDK11 as per the description so we'll ideally need to get hold of a JDK16/17 as a boot JDK before pushing this forward

Yes. Where could I start an issue to add a JDK16 boot JDK to build-image?

**Comment by feilongjiang** [comment]
> Yes. I didn't find the right place to update adoptopenjdk/centos6_build_image.

@joeyleeeeeee97 Maybe you can add JDK16/17 as boot JDK at https://github.com/adoptium/infrastructure/blob/master/ansible/Dockerfile.CentOS6

**Comment by sxa** [comment]
It needs to be added into https://github.com/adoptium/infrastructure/blob/793eac15bf0cb46ec92f67d83e6537d7ca9feac5/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml#L90 - the `adoptopenjdk_install` role isn't invoked for JDK16 yet so if you can put in a PR to make that change it should fix this :-)

**Comment by sxa** [comment]
The above PR is currently set to build natively instead of cross-compiling as I had some additional issues building in the cross-compile environment. We can adjust that later if required :-)

**Comment by smlambert** [comment]
Noting that there will be a minor update in TKG to mark riscv as a 'mixed' platform (not the case for the openj9 riscv build) - we believe that was causing issues when running tests on this platform and JDK_IMPL (FYI @sxa).

**Comment by sxa** [comment]
Thanks @smlambert -I haven't looked in detail at the output from the tests on https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17/job/jdk17-linux-riscv64-hotspot other than to see that most of them, including the Smoke test is failed. We'll see how it looks after the TKG update is done :-)

**Comment by smlambert** [comment]
https://github.com/adoptium/TKG/pull/226 TKG change is merged.  Example grinder is: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1058/

**Comment by sxa** [comment]
LGTM - we still need some tweaks to the smoke tests and other bits, but we're now live and have some test output, therefore closing :-D
