### ISSUE TITLE
openJDK version for win XP

### ISSUE THREAD

**Issue by maurolm2** [adoptium/temurin-build#2632]
Unsure where to raise something? Here are some of the common places:
- If your issue is due to the way OpenJDK is built, then this is the repository to raise it in - Describe your problem below
- If your issue is related to our installers (as opposed to tgz/zip downloads) raise it in [installer](https://github.com/adoptium/installer/)
- If your issue is related to and end-user visible issue with the JDK, or an underlying java bug, please raise it in [adoptium-support](https://github.com/adoptium/adoptium-support/issues)

**Problem description:**
NEW AROUND

can anyone tell me what openJDK VERSION should I install to run on win XP /
tks

**Comment by karianna** [comment]
See https://adoptopenjdk.net/supported_platforms.html

**Comment by maurolm2** [comment]
tks for quick answer!
sort of new around

that link shows  then there s no way to run it on winXP?

abs
Mauro
51 99961 3785
51  3222 1710

Em 21/5/2021 14:56, Martijn Verburg escreveu:
