### ISSUE TITLE
Bisheng cross-compilation collect artifacts failed

### ISSUE THREAD

**Issue by feilongjiang** [adoptium/temurin-build#2635]
Thank you for reporting a broken build! Please fill in the following details:
- **Jenkins link to the failing log:** https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-riscv64-bisheng/23/consoleText
- **Which platforms (OS+arch) are affected:** CentOS6, x86_64 (cross-compilation for RISC-V)

Bisheng cross-compilation pipeline failed at the stage `Copy artifacts from another project`:

```
Unable to find project for artifact copy: build-scripts/utils/cross-compiled-version-out This may be due to incorrect project name or permission settings; see help for project name in job configuration.
```

**Comment by andrew-m-leonard** [comment]
seems to be working now..? @sxa

**Comment by sxa** [comment]
As far as I can tell it is passing when the access controls on the `build-scripts` folder are removed, so we will need to understand why it needs that access. I have reinstated the access controls after running that test.

**Comment by andrew-m-leonard** [comment]
See jenkins doc on permissions for copyArtifact: https://plugins.jenkins.io/copyartifact/#CopyArtifactPlugin-Permissionstocopyartifact

**Comment by feilongjiang** [comment]
In https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/cross-compiled-version-out, it only allows `/build-scripts/jobs/jdk11u/jdk11u-linux-riscv64-openj9` to copy artifacts, maybe that's the reason why bisheng cross-compilation failed?

**Comment by andrew-m-leonard** [comment]
Yes, seems to have fixed it adding /build-scripts/jobs/jdk11u/jdk11u-linux-riscv64-bisheng to the permission to copy artifacts
