### ISSUE TITLE
adoptium/jdk8u mirror not being mirrored

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2638]
Looks like the mirror job for jdk8u is still pointing at adoptopenjdk/openjdk-jdk8u and is failing to mirror as well:
https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/git-hg-jdk8u/1134/console
```
+ git push upstream --all
To github.com:AdoptOpenJDK/openjdk-jdk8u.git
 ! [rejected]              dev -> dev (non-fast-forward)
error: failed to push some refs to 'git@github.com:AdoptOpenJDK/openjdk-jdk8u.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by sxa** [comment]
I believe https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/job/git-hg-jdk8u/ is the job that is supposed to mirror to the adoptium repo, although if that's failing and still reporting a green status we should look at fixing that so we can be alerted of failures more easily.

**Comment by andrew-m-leonard** [comment]
@sxa i've fixed the jenkins job configuration so it does not ignore the merge.sh bad rc: https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/job/git-hg-jdk8u/65/console

**Comment by andrew-m-leonard** [comment]
Looks like flags.m4 change upstream to support MacOS clang is conflicting with our Adopt patch for the same... i'm recreating locally to check
@gdams fyi

**Comment by andrew-m-leonard** [comment]
Merge conflict resolved
