### ISSUE TITLE
PROPOSAL: Use "temurin" as an alternate VARIANT option from hotspot

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#2671]
Putting the feelers out for this one. Thoughts in here sprung out as part of the changes proposed in https://github.com/adoptium/temurin-build/pull/2670/files#diff-bf1a71b6b982bb100bd797f1aac5049b232b43398baf9494c8f2823c62c8aa82

### Reasons for doing it:

- It would make it simpler for third parties use our scripts to build alternate variants. At the moment they would have to use the disable-adopt-branch-safety option if they don't have Adopt/Termurin-proprietory things like our marker files, which it would be nice not to need for end-users trying our scripts.
- We could default the `hotspot` VARIANT to build from the upstream skara repositories
- At the moment anyone who uses our scripts to build from our repositories will produce a binary that calls itself `Temurin` in the version output and other vendor properties. This is something we should discourage to avoid confusion
- If we have other Adoptium project members who wish to support our binaries we should make it easy to use our build scripts to build and ship with the minimal amount of adjusting of parameters or potential trademark infringements, so having a "default HotSpot" option without any of the temurin-specifics would assist with that - it would come out as totally vanilla openjdk unless explicitly overriden - and we could provide good guidance on the 
- It would likely make building alternates like Loom, Panama with our scripts etc. a bit simpler

### Reasons against doing it:

- It's an extra codepath that should be maintained, although we can reasonably easily run it periodically to check, potentially just using `VagrantPlaybookCheck`

**Comment by jerboaa** [comment]
A huge +1 from me. It would allow folks to use the scripts to produce vanilla OpenJDK builds fairly easily and that would be very beneficial. I could see myself help testing those code branches on a regular basis.

**Comment by karianna** [comment]
Are we conflating the VM variant with the vendor here?  I'm pretty sure we had some old/long-running issues stating that we needed to add vendor and allow folks to differentiate on that.

**Comment by sxa** [comment]
> A huge +1 from me. It would allow folks to use the scripts to produce vanilla OpenJDK builds fairly easily and that would be very beneficial. I could see myself help testing those code branches on a regular basis.

I remember you hitting some problems a few months ago and needed some of the additional options in such a situation :-)

**Comment by sxa** [comment]
> Are we conflating the VM variant with the vendor here? I'm pretty sure we had some old/long-running issues stating that we needed to add vendor and allow folks to differentiate on that.

This is purely an issue of usability of the builds scripts. At the moment they only take a `VARIANT` at the top level, and if it's set to HotSpot it defaults to Eclipse/Temurin. We could certainly provide a way to make `VENDOR` something that's passed in, but I would be strongly in favour of getting rid of a "HotSpot == Temurin" default in our scripts like https://github.com/adoptium/temurin-build/blob/b376432d8ddc0ecd1d002cb5d8d9167ac85cc9aa/sbin/build.sh#L256 and my gut feel is that using a separate VARIANT would likely be the cleanest way to do it. Bear in mind that all `VARIANT`s we currently support in the build scripts are also HotSpot-based other than Eclipse OpenJ9 so my proposal reflects treating Temurin in a consistent way to the others in a relatively simple way.

Alternative proposals always welcome, but let's make sure we keep it simple, straightforward, and easy for others to integrate any future variants.

**Comment by karianna** [comment]
I agree that Hotspot != Temurin as a default (Temrun should be passed in like any other vendor) but I'd prefer to stop overloading variant in this manner going forward, this seems like the time to make the split between variant and vendor (how much appetite with have for this before July PSU I'm not sure).

**Comment by sxa** [comment]
As @jerboaa has just discovered, the presence of our `--with-company-name` [patch](https://github.com/adoptium/jdk8u/commit/5762756c219acb60f0ef1ada0e8a1656cf6d7574#diff-7e9cac5274688c2aeb265de88b0026348d3f7aeee6019f99ab8f52ce28e6d3c8) also makes it hard for people to build from their own JDK8 repository as it doesn't have that option that the build scripts expect.

**Comment by karianna** [comment]
> As @jerboaa has just discovered, the presence of our `--with-company-name` [patch](https://github.com/adoptium/jdk8u/commit/5762756c219acb60f0ef1ada0e8a1656cf6d7574#diff-7e9cac5274688c2aeb265de88b0026348d3f7aeee6019f99ab8f52ce28e6d3c8) also makes it hard for people to build from their own JDK8 repository as it doesn't have that option that the build scripts expect.

@jerboaa Is this patch something that you think jdk8u would accept in time?  I honestly can't remember if we tried.

**Comment by jerboaa** [comment]
As mentioned on slack this is a patch which shouldn't be needed at all since 8u212:

https://bugs.openjdk.java.net/browse/JDK-8193764
https://bugs.openjdk.java.net/browse/JDK-8189761

Use `--with-vendor-name` instead. That's the upstream configure option to use.

**Comment by jerboaa** [comment]
Except for this version output change, I guess. That's not possible in plain 8u:

https://github.com/adoptium/jdk8u/compare/master..dev#diff-ee823353863b571a03eb346d7e1975d5752e78ca4cfb0ae2ce57772e2811f31fR109

**Comment by jerboaa** [comment]
https://github.com/adoptium/jdk8u/compare/master..dev#diff-362e955b86dcc01922130656ff6ee4934c8d85795f6d13bf4378efef8e9a6da1R112-R115

These should be: `--with-vendor-url` and `--with-vendor-bug-url`

**Comment by sxa** [comment]
NOTE: Ref #2817 ensure that the `-without-version-xxx` parameters (and the equivalent for JDK8) are included in the docs once the separate HotSpot build is in place.

**Comment by sxa** [comment]
Going to add a list of PRs that have gone in this week as a result of these changes for historic reference in case anyone needs to implement something similar:
- pipe:@sxa - [Initial ci-jenkins-pipeline changes](https://github.com/adoptium/ci-jenkins-pipelines/pull/226)
- bld:@sxa - [Initial temurin-build changes](https://github.com/adoptium/temurin-build/pull/2818)
- pipe:@sxa - [Output filename was still coming out as `temurin` - switched back for compatibility](https://github.com/adoptium/ci-jenkins-pipelines/pull/241)
- build:@sxa - [Adjust auto-download of boot JDK to use `hotspot` in API and not `temurin` if `VARIANT=temurin`](https://github.com/adoptium/temurin-build/pull/2853)
- pipe:@sxa [Change public visibility of pipeline jobs so that `temurin` ones are visible and not `hotspot`](https://github.com/adoptium/ci-jenkins-pipelines/pull/240)
- pipe:@sophia-guo - [Use `buildConfig.VARIANT` instead of `jdk_Version` to set `JDK_IMPL` for test jobs](https://github.com/adoptium/ci-jenkins-pipelines/pull/245)
- installer:@sxa [windows installers did not understand "temurin" as `JVM` parameter (Mapped to hotspot)](https://github.com/adoptium/installer/pull/438)

@sophia-guo @smlambert If we have any other fixes relating to this change to use `temurin` instead of `hotspot` in the build pipelines please add them into this list, or just mention this issue in the corresponding PR - thanks :-)
