### ISSUE TITLE
the latest tag only have amd64 platform

### ISSUE THREAD

**Issue by wangxufire** [adoptium/temurin-build#2686]
**What are you trying to do?**
use buildx build multi platform images based on adoptopenjdk/openjdk16:latest
**Expected behaviour:**
can works
**Observed behaviour:**
ERROR: no match for platform in manifest sha256:a04a5d8b80059f12f8626ee9a70876dc66d510862522bff844330a1bc55ac21b: not found
**Any other comments:**

**Comment by karianna** [comment]
Yep, we're working on releasing the other platforms over the coming weeks.
