### ISSUE TITLE
Eclipse 2021-06 cannot start with Temurin 11.0.12+7 (macOS)

### ISSUE THREAD

**Issue by heklaz** [adoptium/temurin-build#2687]
## Summary

Eclipse 2021-06 cannot start with Temurin 11.0.12+7 on MacOS

## Steps to reproduce

For eclipse, in eclipse.ini I added 

.
.
.
-vm
/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java
.
.
.

It seems that Eclipse Version: 2021-06 (4.20.0) cannot start.

Previous version of java, specified the same way, works
(
-vm
/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java
)

## Expected results

Eclipse to start

## Actual results

Eclipse launcher does not find JNI_CreateJavaVM symbol. See attached screenshot

<img width="257" alt="Screenshot 2021-08-06 at 18 24 53" src="https://user-images.githubusercontent.com/1963912/128716130-1dfa0bd2-e60d-4b13-8e97-6b0552f81431.png">

## Triaging info

Java version:

openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)

What is your operating system and platform?

macOS 11.5.1

How did you install Java?

Used installer (*.pkg) from adoptopenjdk.net

Did it work before?

N/A

Did you test with other Java versions?

Tried with:

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

Reported to Eclipse: https://bugs.eclipse.org/bugs/show_bug.cgi?id=575284

**Comment by gdams** [comment]
I added deep signing here https://github.com/adoptium/temurin-build/pull/2629 with Mikael but clearly this isn't working

**Comment by JD-Veiga** [comment]
> @JD-Veiga can you send me the output of:
> 
> ```
> codesign -v -vvv /Library/Java/JavaVirtualMachines/openjdk16-temurin
> ```

If you still need it:

```
$ codesign -v -vvv /Library/Java/JavaVirtualMachines/openjdk16-temurin
/Library/Java/JavaVirtualMachines/openjdk16-temurin: valid on disk
/Library/Java/JavaVirtualMachines/openjdk16-temurin: satisfies its Designated Requirement
```

**Comment by tmancill** [comment]
Fully expected based on this thread, but this also affects JMC (JDK Mission Control) as well.  Similarly, JMC works when using AdoptOpenJDK-11.0.11+9.

![image](https://user-images.githubusercontent.com/1195611/129405520-a5362a06-036e-47c9-a7f7-d7fe6eb3f29e.png)

**Comment by mbarbero** [comment]
I've tested both .pkg and .tar.gz distributions, and I get the following results:
```
❯ codesign -v -vvv Downloads/jdk-11.0.12+7/
Downloads/jdk-11.0.12+7/: valid on disk
Downloads/jdk-11.0.12+7/: satisfies its Designated Requirement
```

```
❯ codesign -v -vvv Downloads/jdk-11.0.12+7/Contents/MacOS/libjli.dylib
Downloads/jdk-11.0.12+7/Contents/MacOS/libjli.dylib: valid on disk
Downloads/jdk-11.0.12+7/Contents/MacOS/libjli.dylib: satisfies its Designated Requirement
```

```
❯ codesign -v -vvv Downloads/jdk-11.0.12+7/Contents/Home/bin/../lib/server/libjvm.dylib
Downloads/jdk-11.0.12+7/Contents/Home/bin/../lib/server/libjvm.dylib: valid on disk
Downloads/jdk-11.0.12+7/Contents/Home/bin/../lib/server/libjvm.dylib: satisfies its Designated Requirement
```

```
❯ codesign -v -vvv /Library/Java/JavaVirtualMachines/temurin-11.jdk
/Library/Java/JavaVirtualMachines/temurin-11.jdk: valid on disk
/Library/Java/JavaVirtualMachines/temurin-11.jdk: satisfies its Designated Requirement
```

```
❯ codesign -v -vvv /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/MacOS/libjli.dylib
/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/MacOS/libjli.dylib: valid on disk
/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/MacOS/libjli.dylib: satisfies its Designated Requirement
```

```
❯ codesign -v -vvv /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/../lib/server/libjvm.dylib
/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/../lib/server/libjvm.dylib: valid on disk
/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/../lib/server/libjvm.dylib: satisfies its Designated Requirement
```

Could it be that the requirements are not appropriate? 

I have this for the released binary:

```
❯ codesign -d -r-  /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/MacOS/libjli.dylib
Executable=/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/MacOS/libjli.dylib
designated => identifier "net.temurin.11.jdk" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = JCDTMS22B4
```

@gdams, what is your output once you resigned with LLC codesigning cert?

**Comment by karianna** [comment]
@gdams Do you have a link to the Eclipse bug tracking this issue?

**Comment by anjan713** [comment]
hi I have same issue can anyone suggest how to solve the issue??

**Comment by karianna** [comment]
@gdams Did we need to respin those Mac OS X binaries?

**Comment by thomseno** [comment]
Have the macOS binaries been updated yet?

**Comment by karianna** [comment]
We've done them for 17, so 11, 16, and 8 will follow today or early next week

**Comment by szy54** [comment]
Is there any known workaround? I am also stuck with JDK Mission Control not being able to run.

**Comment by karianna** [comment]
Keeping this open until the respins are done CC @gdams

**Comment by claudionieder** [comment]
I see the same issue with eclipse 4.21 and Temurin-17.0.1+12.
The suggested change of adding <string>-vm</string><string>/Users/claudio/Library/Java/JavaVirtualMachines/temurin-17.0.1/Contents/Home</string> doesn't solve the issue, eclipse will then not start at all without any error message.

% codesign -v -vvv ~/Library/Java/JavaVirtualMachines/temurin-17.0.1                                            2021-11-18 12:20:35
/Users/claudio/Library/Java/JavaVirtualMachines/temurin-17.0.1: valid on disk
/Users/claudio/Library/Java/JavaVirtualMachines/temurin-17.0.1: satisfies its Designated Requirement

% codesign -v -vvv ~/Library/Java/JavaVirtualMachines/temurin-17.0.1/Contents/MacOS/libjli.dylib                2021-11-18 12:21:13
/Users/claudio/Library/Java/JavaVirtualMachines/temurin-17.0.1/Contents/MacOS/libjli.dylib: valid on disk
/Users/claudio/Library/Java/JavaVirtualMachines/temurin-17.0.1/Contents/MacOS/libjli.dylib: satisfies its Designated Requirement

% codesign -v -vvv ~/Library/Java/JavaVirtualMachines/temurin-17.0.1/Contents/Home/bin/../lib/server/libjvm.dylib                                                                                                  2021-11-18 12:33:12
/Users/claudio/Library/Java/JavaVirtualMachines/temurin-17.0.1/Contents/Home/bin/../lib/server/libjvm.dylib: valid on disk
/Users/claudio/Library/Java/JavaVirtualMachines/temurin-17.0.1/Contents/Home/bin/../lib/server/libjvm.dylib: satisfies its Designated Requirement

% codesign -d -r- ~/Library/Java/JavaVirtualMachines/temurin-17.0.1/Contents/MacOS/libjli.dylib                 2021-11-18 12:28:47
Executable=/Users/claudio/Library/Java/JavaVirtualMachines/temurin-17.0.1/Contents/MacOS/libjli.dylib
designated => identifier "net.temurin.17.jdk" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = JCDTMS22B4


I then deleted temurin and replaced it with the lates nightly build

% java -version                                                                                                                                                                                                    2021-11-18 12:39:09
openjdk version "17.0.1-beta" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12-202111162351 (build 17.0.1-beta+12-202111162351)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12-202111162351 (build 17.0.1-beta+12-202111162351, mixed mode)

and when starting eclipse I still get 

The JVM shared library "/Users/claudio/Library/Java/JavaVirtualMachines/temurin-17.0.1/Contents/Home/bin/../lib/server/libjvm.dylib"
does not contain the JNI_CreateJavaVM symbol.

**Comment by karianna** [comment]
I'm unable to replicate the above Latest Eclipse on Mac Os X 12.0.1, Eclipse 2021-09 (4.21.0), Temurin 17.0.1+12

**Comment by claudionieder** [comment]
Thanks for verifying, your answer made me realise what I possibly overlooked. I am on a new Mac with Apple Silicon on which I had transferred the content of the previous one. 

temurin I had already updated to the Apple Silicon Version, for running other Java applications. eclipse I had forgotten.

I now installed eclipse afresh making sure to get the aarch64 version and now it works.

**Comment by wtfiwtz** [comment]
Hi @claudionieder 

You should be able to get it working on ARM64 using Rosetta emulation.
1. Duplicate your Terminal.app / iTerm2.app and mark the version named "Terminal Rosetta" with the 'Open with Rosetta' 
2. Install `oracle-jdk` with brew under x86_64 - `arch -x86_64 brew install oracle-jdk`
3. Set your `JAVA_PATH` - `/usr/libexec/java_home -V` then `export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home"`
4. Run `/ApacheDirectoryStudio.app/Contents/MacOS/ApacheDirectoryStudio`

![image](https://user-images.githubusercontent.com/1445450/192952485-081cdf13-195c-473a-927d-d630d496d5de.png)

Hopefully a M1-friendly Eclipse / Directory Studio binary will be provided in October 2022.  
https://stackoverflow.com/questions/70220737/apache-directory-studio-on-apple-m1-silicon

Cheers,
Nigel

**Comment by psuzzi** [comment]
I saw this issue recently on some Eclipse RCP Apps built for Mac, so I'm adding my solution in case someone like me is searching for a workaround. 

The simple solution is 
* Download an x86 (Intel) version of JDK, and unpack it somewhere
* Open the contents of the Eclipse.app that is not working and edit the info.plist by adding the keys `<string>-vm</string><string>/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java</string>`, where the path above is the path to your x86 JDK for mac

**Comment by erselbey** [comment]
Unfortunately, the solution to this problem is to install x86_64 via homebrew. Idiots couldn't figure this out on ARM64!!!

<img width="708" alt="image" src="https://github.com/adoptium/temurin-build/assets/25445468/f82805f0-4563-40df-979f-5eed8e6dfb57">
