### ISSUE TITLE
Alpine musl builds of Temurin

### ISSUE THREAD

**Issue by brunoborges** [adoptium/temurin-build#2688]
It seems that Project Portola (JEP 386) had very minor changes to make it possible to build OpenJDK for musl libc instead of GNU glibc. Most of the changes were about steps required to build.

Currently, the following OpenJDK builds provide packages for Alpine Linux:

. Amazon Corretto
. Azul Systems' Zulu
. BellSoft Liberica JDK

It would be good to have a build of Eclipse Temurin for Alpine Linux so that the ecosystem could leverage AQAVit's value.

**Comment by jerboaa** [comment]
https://openjdk.java.net/jeps/386 is JDK 16 and better. So I'm for providing those for JDK 16+ builds only (JDK 17 now) unless changes get backported upstream first.

**Comment by gdams** [comment]
The plan is almost certainly to produce MUSL based images. We already produce nightly builds of them.

More information will be available shortly

**Comment by brunoborges** [comment]
> unless changes get backported upstream first.

I used to think that too, @jerboaa, but after looking at JEP 386 and the work that got done, I couldn't see any actual changes other than build instructions. Can you point me to a changeset/PR that shows significant changes ?

**Comment by brunoborges** [comment]
Ok, after digging a bit more with some help from a co-worker, I found this commit: https://github.com/openjdk/jdk/commit/63009f90/

I'm curious as to whether other vendors have backported these changes into their pre-16 branches in order to produce musl binaries, and whether there was ever an attempt to backport these changes to upstream (jdk11u at the very least).

**Comment by karianna** [comment]
We've got Alpine musl based images in the CI/CD pipeline + compliance project so we can now test whatever we build.  The PMC is currently discussing backporting to 11 and 8.

**Comment by karianna** [comment]
PMC has agreed to allow backports to temurin 8 and 11 in parallel to working on the backport upstream at OpenJDK.  You'll soon see one Stephanie Crater working on this starting next week :-).

**Comment by jerboaa** [comment]
@karianna The consensus on the PMC was to get an overall feel for the JDK 8/11 backport upstream first. Then, if the general agreement is affirmative to get it in upstream, proceed with the downstream work. That way it would only be a temporary downstream divergence. Has this been socialized on upstream mailing lists?

**Comment by karianna** [comment]
> @karianna The consensus on the PMC was to get an overall feel for the JDK 8/11 backport upstream first. Then, if the general agreement is affirmative to get it in upstream, proceed with the downstream work. That way it would only be a temporary downstream divergence. Has this been socialized on upstream mailing lists?

It will next week (I'm working with Stephanie today on the mail and getting her set up here).

**Comment by gdams** [comment]
We have now released a JDK17 Alpine Musl build (headless). We plan to backport to JDK11 and JDK8 as well. Closing

**Comment by llamahunter** [comment]
Is there a github issue tracking the backport progress?

**Comment by chris-brace** [comment]
Are there any plans to make a JDK16 alpine build?

**Comment by gdams** [comment]
@chris-brace I can likely push through a JDK16 alpine build

**Comment by chris-brace** [comment]
@gdams Ooo that would really help me but dont do it unless if it would be very onerous for you. Basically its gonna take us some time to migrate to java 17 for various reasons, and in the mean time ops and security really prefer alpine. Thank you in advance :)

**Comment by karianna** [comment]
We'll be tracking the backports for 11 and 8 in their respective jdk8u and jdk11u source repos.  More on this later on this week!

**Comment by llamahunter** [comment]
> We'll be tracking the backports for 11 and 8 in their respective jdk8u and jdk11u source repos. More on this later on this week!

At these locations?
https://github.com/adoptium/jdk11u/tree/alpine-musl
https://github.com/adoptium/jdk8u/tree/alpine-musl

**Comment by karianna** [comment]
Yes but we also need to open the relevant issues

**Comment by llamahunter** [comment]
> Yes but we also need to open the relevant issues

please post links here or on https://github.com/adoptium/containers/issues/72 so that I can subscribe to them.

**Comment by gdams** [comment]
> @gdams Ooo that would really help me but dont do it unless if it would be very onerous for you. Basically its gonna take us some time to migrate to java 17 for various reasons, and in the mean time ops and security really prefer alpine. Thank you in advance :)

@chris-brace Alpine for JDK16 is now available on the website! We're working hard on getting JDK11 and JDK8 backports in place

**Comment by chris-brace** [comment]
@gdams Thank you!!
