### ISSUE TITLE
How to actually cross-compile (macOS x86_64/Arm64)?

### ISSUE THREAD

**Issue by balthisar** [adoptium/temurin-build#2690]
The documentation indicates that I can cross compile with `makejdk-any-platform.sh`, and even mentions `--cross-compile`, but that seems to only skip java version checks.

Currently I use `makejdk-any-platform.sh` separately on Arm64 macOS and x86_64 macOS, but I'd like to build everything on Intel (specifically using Github actions).

What should we add to the command line switches to build the other arch? 

Thanks!

**Comment by karianna** [comment]
We haven't completed the work at Temurin for these cross-compile use cases.  Once we get the Apple M1 and Windows on Arm infra in place we'll update the build scripts accordingly.  In the meantime, you may be able to get some joy out of github.com/microsoft/openjdk-aarch64

**Comment by balthisar** [comment]
JDK-17 builds just fine on my M1 Mac with that JDK-16 bootstrap, and it's actually shipping (this was with your build script from the last week or so of AdoptJDK before the change). It's definitely building the Arm64 architecture, and I've even lipo'd all of the bits together and I'm currently shipping a product with the fat JDK. Seriously. The right arches run on the right arches, including Rosetta.

The only hiccup for me is I have to build Arm64 on my M1 Mac instead of cross-compiling it.

(`jdeps` and `jlink` leave me with a pretty light JRE, so I can't say that the entire JDK actually _runs_ on M1, but the parts that I'm left with work absolutely perfectly with the jars I need to use.)

**Comment by sxa** [comment]
> github.com/microsoft/openjdk-aarch64

(To be clear, Adoptium does build on this platform and we've been publishing nightly development builds of macos on arm via the API at  https://api.adoptium.net/v3/binary/latest/17/ea/linux/aarch64/jdk/hotspot/normal/adoptium - we just haven't done any GA releases yet. Hopefully we'll be able to do so for JDK17.)

As you've probably guessed from your experiences, we currently build natively on an M1 so haven't had a need to add the cross compile support. I'm not too familiar with the macos compilers but if you're willing to produce a patch I'd personally be happy to include it. Based on experiences with other products it seems it's generally quicker to compile on the M1 chips, but I accept that for the github actions use case that's not necessarily suitable :-)

**Comment by gdams** [comment]
@balthisar I think you just need `--openjdk-target=aarch64-apple-darwin`. I'll close for now and you can reopen if you have further questions
