### ISSUE TITLE
Link for download

### ISSUE THREAD

**Issue by genamiga** [adoptium/temurin-build#2691]
Hello, I am trying to download the zip for jdk-16.0.2+7 JRE HotSpot for Windows x64 but the link is for 16.0.1+9

**Comment by genamiga** [comment]
Hello, I am trying to download the zip for jdk-16.0.2+7 JRE HotSpot for Windows x64 but the link is for 16.0.1+9

**Comment by karianna** [comment]
The JREs are still being built (which is why you're seeing an old one).
