### ISSUE TITLE
Can't get it to install on Raspberry Pi

### ISSUE THREAD

**Issue by tjc1199** [adoptium/temurin-build#2695]
Wanting to install arm32 openjdk-16.0.1+9

This is what I'm doing:
![putty-jdk](https://user-images.githubusercontent.com/90068736/132064359-84abfc6b-160b-4fd2-a6a9-a4a9928658b9.PNG)
![putty-jdk-2](https://user-images.githubusercontent.com/90068736/132064368-2615abba-d77d-4ba5-b143-d82bec3a6951.PNG)

I don't know why it isn't working. May be a stupid question, but definitely need help

**Comment by karianna** [comment]
In step 6 you need to replace the `<codename>` in the snippet below with the actual code name of your distro.

`echo "deb [signed-by=/usr/share/keyrings/adoptopenjdk-archive-keyring.gpg] https://adoptopenjdk.jfrog.io/adoptopenjdk/deb <codename> main" | sudo tee /etc/apt/sources.list.d/adoptopenjdk.list`

That codename snippet is usually recorded in _/etc/os-release_ and can be extracted on Debian by running `cat /etc/os-release | grep VERSION_CODENAME | cut -d = -f 2` and on Ubuntu by running `cat /etc/os-release | grep UBUNTU_CODENAME | cut -d = -f 2`.

**Comment by tjc1199** [comment]
> In the instructions, for step 6 you need to replace the `<codename>` place holder with the actual code name of your distro.
> 
> That codename is usually recorded in _/etc/os-release_ and can be extracted on:
> 
> * Debian by running `cat /etc/os-release | grep VERSION_CODENAME | cut -d = -f 2`
> * Ubuntu by running `cat /etc/os-release | grep UBUNTU_CODENAME | cut -d = -f 2`.

THANK YOU. I glazed right over that
