### ISSUE TITLE
Upgrade GH Actions to use setup-java 2 and grab latest Java 17 for tip builds

### ISSUE THREAD

**Issue by karianna** [adoptium/temurin-build#2704]
@karianna Thanks for the review!

Build failures seem to be caused by:
```
warning: unknown enum constant Feature.SEALED_CLASSES
warning: unknown enum constant Feature.SEALED_CLASSES
```
That suggests the JDK 18 build uses a too old JDK 17 boot JDK. Uses 17+20. Should be 17+24 or better. See:
https://bugs.openjdk.java.net/browse/JDK-8260517

Either way, unrelated failures.

_Originally posted by @jerboaa in https://github.com/adoptium/temurin-build/issues/2702#issuecomment-915043130_

**Comment by gdams** [comment]
The build jobs actually use the API. I'll do some digging but I think we just need to switch to the Adoptium api to get the latest nightly builds.

**Comment by gdams** [comment]
Yup, see all the references in https://github.com/adoptium/temurin-build/search?q=api.adoptopenjdk.net&type= that need updating.

**Comment by karianna** [comment]
> Yup, see all the references in https://github.com/adoptium/temurin-build/search?q=api.adoptopenjdk.net&type= that need updating.

Will do this post-release - I think much of that YAML needs updating to use the `setup-java` action
