### ISSUE TITLE
Tomcat 9 Stopped - A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by akyenni** [adoptium/temurin-build#2716]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f060c51f829, pid=34770, tid=40921
#
# JRE version: OpenJDK Runtime Environment (13.0.1+9) (build 13.0.1+9)
# Java VM: OpenJDK 64-Bit Server VM (13.0.1+9, mixed mode, tiered, z gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x1022829]  call_catch_cleanup_one(PhaseIdealLoop*, LoadNode*, Node*)+0x4b9
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /usr/local/tomcat9/bin/hs_err_pid34770.log
#
# Compiler replay data is saved as:
# /usr/local/tomcat9/bin/replay_pid34770.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-build/issues

**Comment by akyenni** [comment]
> # A fatal error has been detected by the Java Runtime Environment:
> # SIGSEGV (0xb) at pc=0x00007f060c51f829, pid=34770, tid=40921
> # JRE version: OpenJDK Runtime Environment (13.0.1+9) (build 13.0.1+9)
> # Java VM: OpenJDK 64-Bit Server VM (13.0.1+9, mixed mode, tiered, z gc, linux-amd64)
> # Problematic frame:
> # V [libjvm.so+0x1022829] call_catch_cleanup_one(PhaseIdealLoop*, LoadNode*, Node*)+0x4b9
> # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
> # An error report file with more information is saved as:
> # /usr/local/tomcat9/bin/hs_err_pid34770.log
> # Compiler replay data is saved as:
> # /usr/local/tomcat9/bin/replay_pid34770.log
> # If you would like to submit a bug report, please visit:
> # https://github.com/AdoptOpenJDK/openjdk-build/issues

[replay_pid34770.log](https://github.com/adoptium/temurin-build/files/7168450/replay_pid34770.log)
[hs_err_pid34770.log](https://github.com/adoptium/temurin-build/files/7168451/hs_err_pid34770.log)

**Comment by karianna** [comment]
Java 13 is no longer supported - you'll need to move to Java 17 (out this week or next)
