### ISSUE TITLE
Provide source archives as part of the releases

### ISSUE THREAD

**Issue by jerboaa** [adoptium/temurin-build#2728]
It would be great to have a "source" link on the [releases page](https://adoptium.net/releases.html). This helps users figure out what changed and get access to sources of a particular release right away.

Related issues:
Build support: https://github.com/adoptium/temurin-build/issues/2698
API: https://github.com/adoptium/api.adoptium.net/issues/176

**TODO**:
- Enable the `--create-source-archive` in https://github.com/adoptium/ci-jenkins-pipelines
- Figure out a way how to publish/promote the source archive snapshot (I'd expect it would need some deduplication).
- Actually use the new API on the website and provide source links akin to the [upstream releases](https://adoptopenjdk.net/upstream.html) page

**Comment by sxa** [comment]
NOTE: As per discussion earlier we should consider the impact of enabling this option on the space required on the jenkins server. I would suggest that we only produce the source archive on one platform (e.g. Linux/x64) and ship from that build only. Another option would be to have a separate "Create source bundle" job to pull from. The former seems a bit easier to me and utilises the existing options, albeit slightly less "clean" by having to do it on a particular source archive.

Given the above, we should also consider when / whether to include it when doing point releases (many of which are repackaging on a subset of platforms)

**Comment by jerboaa** [comment]
Enable `--create-source-archive` on Linux x64: https://github.com/adoptium/ci-jenkins-pipelines/pull/198
Tag `sources` tarball as such in metadata: https://github.com/adoptium/ci-jenkins-pipelines/pull/199

**Comment by jerboaa** [comment]
Final piece of this is getting a link added on the main page. Tracked with: https://github.com/adoptium/adoptium.net/issues/213

**Comment by jerboaa** [comment]
> Final piece of this is getting a link added on the main page. Tracked with: [adoptium/adoptium.net#213](https://github.com/adoptium/adoptium.net/issues/213)

This is now done. Closing this epic.
