### ISSUE TITLE
"!Settled JDK version does not match" in JDK18 smoke tests

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#2749]
Thank you for reporting a broken build! Please fill in the following details:
- **Jenkins link to the failing log:** https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-x64-hotspot_SmokeTests/
- **Which platforms (OS+arch) are affected:** Most - probably all
- **If you look at the historic logs, does the problem appear to be specific to one machine?** No
- **Link to any upstream project bug report (e.g. [OpenJ9](https://github.com/eclipse-openj9/openj9/issues)/[JBS](https://bugs.openjdk.java.net/browse))** m/a

```
01:27:47  /home/jenkins/workspace/build-scripts/jobs/jdk/jdk-aix-ppc64-hotspot_SmokeTests/aqa-tests/TKG/../TKG/envSettings.mk:30: *** DETECTED_JDK_VERSION value is 18, settled JDK_VERSION value is 17. JDK_VERSION value does not match. Please reset or unset JDK_VERSION.  Stop.
01:27:47  gmake[1]: Leaving directory '/home/jenkins/workspace/build-scripts/jobs/jdk/jdk-aix-ppc64-hotspot_SmokeTests/aqa-tests/TKG'
```

**Comment by karianna** [comment]
Tried entering no version on https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-x64-hotspot_SmokeTests/40/console but that failed.
