### ISSUE TITLE
MacOS JDK18 cannot retrieve head version info

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#2751]
Thank you for reporting a broken build! Please fill in the following details:
- **Jenkins link to the failing log:** https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-mac-x64-hotspot/483/console
- **Which platforms (OS+arch) are affected:** MacOS
- **If you look at the historic logs, does the problem appear to be specific to one machine?** Probably not, but I've only run once since another fix went in
- **Link to any upstream project bug report (e.g. [OpenJ9](https://github.com/eclipse-openj9/openj9/issues)/[JBS](https://bugs.openjdk.java.net/browse))** n/a

This will be another failure due to the expiration of the root certificate used by LetsEncrypt at the end of last month.
```
13:14:16  Building an exploded image for signing
[Pipeline] sh
13:14:17  + ./build-farm/make-adopt-build-farm.sh
13:14:17  This appears to be JDK Head. Querying the Adopt API to get the JDK HEAD Number (https://api.adoptium.net/v3/info/available_releases)...
13:14:17    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
13:14:17                                   Dload  Upload   Total   Spent    Left  Speed
13:14:17  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
13:14:17  curl: (60) SSL certificate problem: certificate has expired
13:14:17  More details here: https://curl.haxx.se/docs/sslcerts.html
```

**Comment by sxa** [comment]
Do the build machines have the same setup i.e. with two versions of `curl`? I guess the older 7.54.0 is in `/usr/bin` but what was the location of the other one that you pointed the symlink to?

We should check the mac machines (especially the build machines) and see if the same fix works on there (Put the link in place, then run a [JDK18 build job](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-mac-x64-hotspot/) on the machine) and if that works look at adjusting the playbook accordingly.

**Comment by sxa** [comment]
> The updated curl may still be needed since it solves the certificates problems unrelated to the download of the bootjdk 17,

Yep absolutely I think we should still put in a fix for that reason, and it will allow the download to progress when we get to JDK19 without having to wait until we deploy JDK18 as a boot JDK :-) So I guess we can put in the link conditionally based on either the macos version (easiest if it can't be updated) or explicitly checking the version of curl in `/usr/bin` to see if it needs to be superceded by an entry in `/usr/local/bin`.

**Comment by andrew-m-leonard** [comment]
This looks fixed now..
