### ISSUE TITLE
Smoke tests do not appear to be executing on Solaris/x64 builds

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#2757]
Thank you for reporting a broken build! Please fill in the following details:
- **Jenkins link to the failing log:** Any of https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-hotspot_SmokeTests/
- **Which platforms (OS+arch) are affected:** Solaris/x64 ([Solaris/SPARC](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-sparcv9-hotspot_SmokeTests/50/) is ok)
- **If you look at the historic logs, does the problem appear to be specific to one machine?** No
- **Link to any upstream project bug report (e.g. [OpenJ9](https://github.com/eclipse-openj9/openj9/issues)/[JBS](https://bugs.openjdk.java.net/browse))** n/a

Solaris/SPARC output:
```
21:23:02  TEST TARGETS SUMMARY
21:23:02  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
21:23:02  PASSED test targets:
21:23:02  	Java_Version_0
21:23:02  
21:23:02  TOTAL: 1   EXECUTED: 1   PASSED: 1   FAILED: 0   DISABLED: 0   SKIPPED: 0
21:23:02  ALL TESTS PASSED
21:23:02  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```
Solaris/x64 output:
```
19:36:08  TEST TARGETS SUMMARY
19:36:08  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
19:36:08  TOTAL: 0   EXECUTED: 0   PASSED: 0   FAILED: 0   DISABLED: 0   SKIPPED: 0
19:36:08  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Comment by sophia-guo** [comment]
'SPEC' : 'sunos_x86-64' has not been added to ottawa.csv so TKG doesn't know it.

**Comment by karianna** [comment]
Still seems to be an issue.

**Comment by andrew-m-leonard** [comment]
Looks ok now.
Temurin jdk8u Solaris smoke tests running
Hotspot jdk8u Solaris smoke test correctly ran the last time hotspot build was run
