### ISSUE TITLE
Repro-Build: jdk-18 HOTSPOT_BUILD_TIME and HOTSPOT_BUILD_USER not reproducible

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2761]
On MacOS a difference in libjvm.dylib is apprent in the compiled https://github.com/adoptium/jdk/blob/0e14bf70cf6e482a2ec7d13ed37df0bee911740d/src/hotspot/share/runtime/abstract_vm_version.cpp#L273
both HOTSPOT_BUILD_TIME and HOTSPOT_BUILD_USER are not going to be deterministic.

**Comment by andrew-m-leonard** [comment]
The "user" used for building the JDK gets embedded in libjvm binary object:
https://github.com/adoptium/jdk/blob/fe6a2020873fe1eb8d4236dc1db3008f485f3195/make/autoconf/basic.m4#L98

Needs overriding to a "standard" name for reproducible builds or removing.

**Comment by magicus** [comment]
For reproducible builds, do not rely on the adhoc version string provided by configure. Use `--with-version-opt=reproducible` (or whatever).

**Comment by magicus** [comment]
For hotspot build time, use `--with-hotspot-build-time`.

I think I need to document all this tribal knowledge...

**Comment by andrew-m-leonard** [comment]
> For reproducible builds, do not rely on the adhoc version string provided by configure. Use `--with-version-opt=reproducible` (or whatever).

I am using that option, however the HOTSPOT_BUILD_USER is not configurable currently? 
I think I did discover the --with-hotspot-build-time

My thoughts on this one now, is maybe adding a --with-build-user=<xxx>

**Comment by magicus** [comment]
Yeah, you are correct. We'd need to add something for that. Yes, maybe a `--with-build-user`, that sounds generic enough to be used in other locations.

**Comment by andrew-m-leonard** [comment]
Fix merged upstream for --with-build-user configure option : https://github.com/openjdk/jdk/commit/f41e768bba2b2ce3b3cc5813ccb1ac4984dcefbd
