### ISSUE TITLE
Performance of AIX pipelines is becoming a bottleneck

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#2762]
**What are you trying to do?** Monitor nightly pieplines

**Expected behaviour:** Pipelines complete within a reasonable amount of time to allow daily triage

**Observed behaviour:** AIX pipelines are taking longer than most of the others.

**Any other comments:**

**Comment by aixtools** [comment]
What AIX systems (at OSUOSL) are not available atm?

 From what I can see at a high level: OJDK01 and OJDK02 have run in the 
last week, but their average use is quite low (although OJDK02 seems to 
have a hung process, as it is always running something)

For the others (ojdk03,04,05,06): Processor usage for the last 4 hours:

Last week:

* ojdk03: not in use

* ojdk04,05,06 are used (and 05 seems to have a hung(?), at least 
long-running background process.

Note: ojdk01 and 02 are on a PWR8 and have 6VP, OJDK03-06 are on a 
POWER9 and have 3VP each.

Can you check and see if there are large time differences between a full 
suite run on either 01-02 compared to 05 (or 06) which, iirc, are also 
AIX 7.1?

If there are I can increase the VP - but back in the day, when I was 
watching the systems I did not see them actually use the full processor 
(1 HW thread is less than (approx) 40% use on P9). For reference, 
one-thread on P7 was roughly 65% workload capacity, 2 HW threads were 
90-95%). P8 - 4 HW threads is roughly 90-95% utilization. Never had the 
opportunity to deep-dive P9 utilization with 4 versus 8 HW threads, but 
my guesstimate is 6 HW threads (per processor) is needed to reach 80-85% 
utilization of a core.

Regards,
Michael

**Comment by sxa** [comment]
Since we're in release week at the moment we have disabled the nighly testing so it won't be easy to verify the effects if adding `odjk03` back in. But we'll see if it makes a difference once it's re-enabled. Some of the tests such as extended.openjdk will now split themselves up and run across multiple machines so we should be able to make good use of all the hosts generally.

I suspect once we get all the testing re-enabled we need to see why, for example, https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.openjdk_ppc64_aix/ has wait times of around five hours a lot of the time. As you suggest I do not expect that most of the systems are VP limited.

**Comment by sxa** [comment]
Thanks for the analysis. From what I can now see the OpenJ9 jobs are taking about [7-8 hours](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-openj9/buildTimeTrend), so is likely limited by the build time plus the run time of sanity.system on that platform. zLinux and Windows/x64 jdk17u pipelines are currently taking a little longer. There's no indication that we're seeing specific problems with AIX as a result of this now (It may be that enabling ojdk03 did the trick, but we now have other systems available!)

I've marked the `test-ibm-` systems [-1](https://ci.adoptopenjdk.net/computer/test-ibm-aix71-ppc64-1/) and [-2](https://ci.adoptopenjdk.net/computer/test-ibm-aix71-ppc64-2) offline since we've got machines at OSUOSL to replace the ones we had there, so we can keep an eye on it over the next couple of weeks and if it stays at the same level we can close this.

**Comment by aixtools** [comment]
Question: I see adopt03 is offline - but cannot find any issue: On the node page I see: p8-aix1-adopt03.osuosl.org | XLC16 issues (tag removed), not recommended to build jdk13+).

What issue or issues?

**Comment by sxa** [comment]
No idea - I'm happy for it to be put back online to verify whether it is now ok. I expect it was https://github.com/adoptium/infrastructure/issues/2334 though

**Comment by sxa** [comment]
Looks consistent with other platforms at the moment so I'm going to close this.
