### ISSUE TITLE
Repro-Build: jdk-18 jdk.javadoc not always deterministic due to missing element-list-<ver> txt files

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2780]
A intermittent problem with the make dependencies means the jdk.javadoc element-list-<ver>.txt generation can remove the src defined element|package-list-<7,8,9,10>.txt files. Is easily recreatable by using --with-jobs=1 causing jdk.javadoc "gendata" to always occur after "java" module build dependency.
Fix: https://github.com/andrew-m-leonard/jdk-1/commit/dbc32c117238b329c2044d6e13aa92280ea7d47c

**Comment by andrew-m-leonard** [comment]
Ref #2594

**Comment by magicus** [comment]
@andrew-m-leonard Oh, you found the cause for this! That's great! We just closed https://bugs.openjdk.java.net/browse/JDK-8276654. Do you think you can reopen it and offer your fix for it?

**Comment by andrew-m-leonard** [comment]
> @andrew-m-leonard Oh, you found the cause for this! That's great! We just closed https://bugs.openjdk.java.net/browse/JDK-8276654. Do you think you can reopen it and offer your fix for it?

@magicus sure, in-progress: https://github.com/openjdk/jdk/pull/6278

**Comment by andrew-m-leonard** [comment]
Fixed upstream: https://github.com/openjdk/jdk/pull/6278
