### ISSUE TITLE
Create a CycloneDX SBOM for the full reproducible build_info

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2785]
Issue: https://github.com/adoptium/temurin-build/issues/2753
investigates the required extended dependencies that determine a given build binary output.
This issue is to take that research and create a new CycloneDX SBOM for that full "build info".

The intended use case this should then satsify is:
"Given a full CycloneDX SBOM for an Adoptium reproducible binary, a 3rd party will be able to setup those required dependencies and build a reproducible identical binary"

**Comment by zdtsw** [comment]
i think this issue should be closed? 
we can discuss more detail what need to be in sbom in https://github.com/adoptium/temurin-build/issues/3013

**Comment by andrew-m-leonard** [comment]
Yes we can discuss in #3013
