### ISSUE TITLE
SSLHandshakeException getting after build jdk8 for linux x86 

### ISSUE THREAD

**Issue by k7295** [adoptium/temurin-build#2786]
I built the jdk8u312 for Linux x86 using https://github.com/adoptium/temurin-build and when I trying to using on the app in my CentOS7 x64, I'm getting this issue:
<img width="1016" alt="Screen Shot 2021-11-02 at 15 58 19" src="https://user-images.githubusercontent.com/15851474/139950654-fa6bc5ce-b506-4da1-b99a-2766b5e95fa2.png">
But if I use the JRE from  https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u302-b08/OpenJDK8U-jre_x64_linux_hotspot_8u302b08.tar.gz I don't get the issue.
Before build the binaries I the script for creating new certs:  https://github.com/adoptium/temurin-build/blob/0829acbf6e6118b8afe50e5a554e2c144cfa7999/security/README.md  
and then run this command `./makejdk-any-platform.sh -J /usr/lib/jvm/java-1.7.0-openjdk --custom-cacerts true --build-variant hotspot jdk8u`
Am I doing something wrong?  I suspect that could be a flag that I'm missing or something like that on the build process

**Comment by k7295** [comment]
I made this issue before: https://github.com/adoptium/temurin-build/issues/2783, but It was closed even before waiting for my answer or waiting for confirmation that is working/fixing now

**Comment by karianna** [comment]
Reopened the original
