### ISSUE TITLE
Migrate JDK8u Mirror to Skara

### ISSUE THREAD

**Issue by gdams** [adoptium/temurin-build#2798]
@jerboaa made me aware of https://mail.openjdk.java.net/pipermail/jdk8u-dev/2021-December/014457.html

Essentially we will now be able to us https://github.com/openjdk/jdk8u for future releases so my proposal is to migrate our mirror away from Mercurial and switch to the Skara scripts which we know work so well for JDK11+

**Comment by jerboaa** [comment]
+1

I guess aarch32 would be the odd one out?

**Comment by gdams** [comment]
It would be, do you know if there's any plans to move that port to GitHub? Presumably, it's just a case of applying the patches to the new `monojdk8u` style repo

**Comment by jerboaa** [comment]
I don't know. Best to ask here: https://mail.openjdk.java.net/mailman/listinfo/aarch32-port-dev It's a separate port and project.

**Comment by gdams** [comment]
> 
I don't know. Best to ask here: https://mail.openjdk.java.net/mailman/listinfo/aarch32-port-dev It's a separate port and project.

Thanks I'll post a message

**Comment by gdams** [comment]
I have provisionally setup https://github.com/adoptium/jdk8u_skara. I need to work on bringing our patches over

**Comment by gdams** [comment]
JDK8u Mercurial repo has now been renamed to `jdk8u_hg` and archived

**Comment by gdams** [comment]
`jdk8u_skara` has now been renamed to jdk8u and should now be the default project cloned by builds

**Comment by gdams** [comment]
Kicking off a test pipeline to verify that everything is in working order https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1886/
