### ISSUE TITLE
EPIC: Create CycloneDX SBOM for current Adoptium MetaData JSON

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2814]
Adoptium builds currently generate a MetaData JSON file with version and dependency build info. This EPIC covers the tasks required to create the necessary CycloneDX tooling and scripting to provide the same MetaData as A CycloneDX SBOM json file.

**Comment by smlambert** [comment]
The single task in this epic is completed, so closing.
