### ISSUE TITLE
Monitor jdkXXu-dev repositories for breaking changes on AIX

### ISSUE THREAD

**Issue by backwaterred** [adoptium/temurin-build#2868]
Updates and development (usually backports) for released versions of OpenJDK happen in jdkXXu-dev repositories which are periodically merged to a jdkXXu repo. This means that breaking changes can be caught earlier in the jdkXXu-dev repo than in the jdkXXu repo. Normally breaking changes should not be merged to the dev repo in the first place, but for platforms supported by Adoptium which are not build by OpenJDK, surprises can occur. I believe the only platform that fits this criterion at the moment is AIX, and an example of a 'surprise' failure is given below [1].

A solution to this issue would be to add a regular build for some subset of the dev repositories  on AIX. There is one dev repo for each released version, so it's likely too much fuss to build them all; I think building LTS versions should be sufficient. That would mean builds for the following repos:

- [jdk8u-dev](https://github.com/openjdk/jdk8u-dev)
- [jdk11u-dev](https://github.com/openjdk/jdk11u-dev)
- [jdk17u-dev](https://github.com/openjdk/jdk17u-dev)

As my role is to support AIX on ppc, I am willing to regularly monitor these builds for failing output and create issues and fixes as needed.

More information on the merge schedule for jdk11u can be seen in the Timelines section of [this page](https://wiki.openjdk.java.net/display/JDKUpdates/JDK11u).

---

[1] The timing looks about right for this to have happened last December (2021) with an issue I was involved in resolving. I believe [the merge on Dec 8](https://github.com/openjdk/jdk11u/commit/9b96ac982e755a820a7b830521a68fa32167a52f) from 11u->11u-dev brought changes that broke the jdk11u build on AIX, then a build issue was reported on Dec 17th [here](https://github.com/adoptium/temurin-build/issues/2807) which was later fixed.

**Comment by sxa** [comment]
We had a cautious amount of positivity to this in the PMC call today, but we felt that ideally we should maybe have a way of providing feedback direct to the OpenJDK community in the future.

For now I've implemented https://ci.adoptopenjdk.net/job/AIX-jdk11-dev-build/ for JDK11 only and set that to run on a timer to run daily except at the weekends. Note that this comes with a disclaimer that it's a best effort basis, it only runs a build, no tests, and we won't be monitoring it ourselves etc. - I'll look at modifying it later to support all three versions either as a multi-config job or as three separate jobs.

While it won't currently run any tests it would still be possible to pass the output from these builds into a Grinder job or similar to execute any suite we want - it may make sense to automate `sanity.openjdk` on these jobs at some point as a basic test. Let's see how it goes.

I'll keep this open for further discussion and until I've got it running for the other release lines.

**Comment by backwaterred** [comment]
Thanks for discussing this, and creating the build. I've set up an IFTTT to monitor for failures.

I can certainly understand that you would want feedback to go directly to the OpenJDK community. It would be a shame if I went on vacation, the build broke, and no one knew about it because I'm the only one checking. I'm not sure what form a solution to this issue would take, but I'm happy to work with the Adoptium team to find something better. For now, I will keep an eye out for any failures and create issues or email the OpenJDK mailing list(s) as appropriate.

**Comment by gdams** [comment]
FYI @sxa I've modifed the job to include ` --custom-cacerts false` (we likely want the build to use the default OpenJDK cacerts to stay as close to the upstream build process as possible)

**Comment by sxa** [comment]
> FYI @sxa I've modifed the job to include ` --custom-cacerts false` (we likely want the build to use the default OpenJDK cacerts to stay as close to the upstream build process as possible)

Yeah I'm fine with that - I was planning to propose making that the default for `hotspot` builds as opposed to `temurin` along with removing any other temurin specifics that are still in there now that the split has been mostly working well.

**Comment by backwaterred** [comment]
The build failure on yesterday appears to have resolved itself, so I'm just some notes here for future reference. The build seemed to be proceeding normally when the last console message was printed at 16:14. The next line in the output comes at 23:56 and indicates that the build was killed by an 8 hour timeout. I wonder if it was paused, preempted and starved by higher priority builds, or otherwise blocked from continuing. Today's build succeeded.

The failing build log is here: https://ci.adoptopenjdk.net/job/AIX-jdk11-dev-build/11/consoleText

**Comment by sxa** [comment]
Closing as it's been complete for a while :-)
