### ISSUE TITLE
Update xlc compiler version for jdk11 builds on AIX

### ISSUE THREAD

**Issue by backwaterred** [adoptium/temurin-build#2882]
Due to some recent changes related to the Harfbuzz library version used to build jdk11, building jdk11 will now require xlc version 16.1. This change is expected to remedy the build break first observed [here](https://ci.adoptopenjdk.net/job/AIX-jdk11-dev-build/17/).

Further discussion on this issue and the changes required can be found at the links below:

- https://bugs.openjdk.java.net/browse/JDK-8282588
- https://mail.openjdk.java.net/pipermail/ppc-aix-port-dev/2022-March/004145.html

**Comment by sxa** [comment]
I've managed to get this to build outside the build process but I had to adjust the memory limit below 7000 in `aix.sh` in order for it to build on the "adopt06" machine with XLC16 FP 11. We will now look at deploying that on the main temurin build machines in order to recover the builds.

**Comment by backwaterred** [comment]
Good news. Thanks for your work on this @sxa!

**Comment by sxa** [comment]
JDK11 is now building with XLC16. Closing.
