### ISSUE TITLE
jdk11u Dragonwell builds fail due to incorrect --with-version-build=0-GA

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2889]
The openjdk version-build with "-GA" is not valid, causing subsequent build failure:
```
18:13:44  * For target hotspot_variant-server_libjvm_objs_abstract_vm_version.o:
18:13:44  ./src/hotspot/share/precompiled/precompiled.hpp:339:4: error: 'GA' was not declared in this scope
18:13:44   #endif // !DONT_USE_PRECOMPILED_HEADER
```

The --with-version-build value I think is inferred from the Dragonwell version.txt value, which was changed back on the 8th Feb to add the -GA: https://github.com/alibaba/dragonwell11/commit/f2096179cdbf51fd62769bd7574a3c4aa3f45367

I suspect these lines needs some extra filtering: https://github.com/adoptium/temurin-build/blob/1165bf4a495377e8fce461fe317f5d2f980e2650/sbin/build.sh#L167

**Comment by andrew-m-leonard** [comment]
@zdtsw fyi

**Comment by zdtsw** [comment]
I'll take a look and see if can fix it in build.sh getOpenJdkVersion()
