### ISSUE TITLE
Solaris JDK8u builds broken

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#2894]
Thank you for reporting a broken build! Please fill in the following details:
- **Jenkins link to the failing log:** [SPARC](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-sparcv9-temurin/42/console) / [x64](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-hotspot/793/console) (NOTE: [x64 seems intermittent](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-hotspot/))
- **Which platforms (OS+arch) are affected:** Solaris (x64 and SPARC)
- **If you look at the historic logs, does the problem appear to be specific to one machine?** No
- **Link to any upstream project bug report (e.g. [OpenJ9](https://github.com/eclipse-openj9/openj9/issues)/[JBS](https://bugs.openjdk.java.net/browse))**

On SPARC it started failing between jobs [23](https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-temurin/23) and [25](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-sparcv9-temurin/25/) (commit hashes 0d71b30 and 8ebd3a7). The build 24 in between was build from source in `https://github.com/calderast/jdk8u_skara` so I'm going to tag @calderast and @gdams to check if anything related to the Alpine changes which went live on March 10th could have made a difference here.

This diff between those two commits appears to include the line with the `git status --porcelain` command which I think is what's causing the shell error although that appears to have been put in during [this change four years ago](https://github.com/adoptium/jdk8u/commit/054b85b1f65254b2d3d2a1d343e14d8eabd1af40) so it's not immediately clear what has caused the failure since the 10th of March (Same day that the [Alpine JDK8 pipeline changes](https://github.com/adoptium/ci-jenkins-pipelines/pull/221) were merged)

**Comment by steelhead31** [comment]
Have done extensive investigations into this issue, and the problem line appears to be line 312 in this file
https://github.com/adoptium/jdk8u/blob/master/make/common/MakeBase.gmk 

`      "$$(if test -n "$$( $(GIT) status --porcelain)"; then printf '+'; fi)"`

This appears to have been introduced a while ago, but for reasons unknown, we have only just recently picked up this change: https://github.com/adoptium/jdk8u/commit/054b85b1f65254b2d3d2a1d343e14d8eabd1af40

As a temporary workaround we could install mercurial on the solaris vagrant machines, until a more formal resolution can be found, I'll continue investigating to see if an alternate solution is possible.

**Comment by sxa** [comment]
https://github.com/adoptium/jdk8u/commit/5a50a589500f56c64b67048981c528cde8e69a0e is the commit that brought this into our codebase but it's not clear why we didn't have it previously

**Comment by jiekang** [comment]
Noting:
02d748d75f (tag: jdk8u332-b04_adopt) has the change in MakeBase

while later on:

e52e33b504 (tag: jdk8u332-b05_adopt) does not

**Comment by sxa** [comment]
The bulid can be repaired by forcing the shell used to be `bash` with `make SHELL=/bin/bash images`

**Comment by jiekang** [comment]
The tagged _adopt commits all have the change so I wonder if the merge conflict commit is a red herring:

https://github.com/adoptium/jdk8u/blob/jdk8u332-b04_adopt/make/common/MakeBase.gmk#L312
https://github.com/adoptium/jdk8u/blob/jdk8u332-b05_adopt/make/common/MakeBase.gmk#L312
https://github.com/adoptium/jdk8u/blob/jdk8u332-b06_adopt/make/common/MakeBase.gmk#L312

**Comment by jerboaa** [comment]
Yes it is. It's caused by the backport of https://bugs.openjdk.java.net/browse/JDK-8280754 new in 8u332.
