### ISSUE TITLE
Enable reproducible builds on MacOS aarch64 jdk-19

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2899]
1) Test reproducible builds for MacOS aarch64 jdk-19 via Jenkins
2) Ensure reproducible across multiple nodes
3) Ensure reproducible between Jenkins build and a native aarch64 MacOS MBPro

**Comment by andrew-m-leonard** [comment]
Done some initial tests on jdk-19 MacOS x64:
- Apple codesign seems to introduce non-determinism in .dylibs
- Ran a job without "codesign", but still using double stage pipeline code (make & assemble), and that still shows non-determinism in .dylibs
- Remove double Mac pipeline staging, and then builds are "identical"

**Comment by andrew-m-leonard** [comment]
Looking like Apple codesign is the issue, a blog on possible resolutions: https://www.smileykeith.com/2021/10/05/codesign-m1/

**Comment by andrew-m-leonard** [comment]
Building from different workspace folder paths produces non-deterministic builds, most likely due to debug info differences, that were resolved for gcc by PRs:
- https://github.com/openjdk/jdk/pull/8124
- https://github.com/openjdk/jdk/pull/8177
These need equivalent for clang on Mac

**Comment by andrew-m-leonard** [comment]
Removing Signature to verify reproducible builds doesn’t quite get there due to the fact we sign jpackageapplauncher, which since that is built into jdk.jpackage jmod causes its jmod “hash” to change which gets embedded into java.base.jmod… Seems the signing of the native .dylib's doesn't cause a different "hash".

**Comment by andrew-m-leonard** [comment]
Possible workarounds for the jpackageapplauncher signing non-determinism:
1. After unzipping jmods and removing all Signatures, make compare "exceptions" for jmods/java.base.jmod.unzipped/classes/module-info.class and lib/modules
2. Build a "non-signed"  JDK along side the "signed" one, and use the "non-signed" one for reproducible verification.

**Comment by andrew-m-leonard** [comment]
I've managed to work a usable solution:
1. First remove all the codesign signatures, including from within jmods and the modules JImage. To achieve this:
- For every jmod within the JDK fully extract it using "jmod extract", and remove original .jmod file
- Fully expand the 'modules' JImage using the jdk.internal.jimage.BasicImageReader, and remove original 'modules' file
- Then remove all signatures from executables using 'codesign --remove-signature'
2. (1) leaves just a couple of exception cases due to the differences caused by different module hash codes for the jdk.jpackage jmod:
- SystemModules class
- java.base/module-info.class
To compare these we "javap" de-compile them to compare class code, ignoring the bipush code differences.
3. The resultsing JDK directory can then successfully perform a direct diff comparison

remove_sig.sh:
```
#!/bin/bash

set -eu

JDK_DIR="$1/"
TOP_DIR=$(pwd)

javap_exception_case() {
  echo "javap converting 'exception' case $1"
  local classFile="$1"
  mv "${classFile}" "${classFile}.class"
  javap -c -constants -l -p "${classFile}.class" | grep -v bipush > "${classFile}.javap"
  rm "${classFile}.class"
}

echo "Removing non-deterministic signatures from $JDK_DIR"

if [ ! -d "${JDK_DIR}/Contents" ]; then
  echo "$JDK_DIR does not contain the MacOS JDK Contents directory"
  exit 1
fi

echo "Unpacking jmods, containing Signed dylib's"
FILES=$(find "${JDK_DIR}" -type f -path '*.jmod')
for f in $FILES
  do
    echo "Unpacking jmod $f"
    dir=$(dirname "$f")
    filename=$(basename "$f")
    unzipped_dir="$dir/$filename.unzipped"
    mkdir "$unzipped_dir"
    cd "$unzipped_dir"
    jmod extract ../$filename
    rm ../$filename
    cd "$TOP_DIR"
  done

echo "Expanding the 'modules' Image"
java --add-exports java.base/jdk.internal.jimage=ALL-UNNAMED ExpandJImage "${JDK_DIR}/Contents/Home/lib/modules"
rm ${JDK_DIR}/Contents/Home/lib/modules

echo "Removing Signatures from all executeables"
FILES=$(find "${JDK_DIR}" -type f -path '*.dylib' && find "${JDK_DIR}" -type f -path '*/bin/*' && find "${JDK_DIR}" -type f -path '*/lib/*' -not -path '*/modules_expanded/*' && find "${JDK_DIR}" -type f -path '*/jpackageapplauncher*')
for f in $FILES
  do
    echo "Removing any signature from $f"
    codesign --remove-signature $f
  done

javap_exception_case "${JDK_DIR}/Contents/Home/lib/modules_expanded/java.base/jdk/internal/module/SystemModules\$0.class_entry"
javap_exception_case "${JDK_DIR}/Contents/Home/lib/modules_expanded/java.base/jdk/internal/module/SystemModules\$all.class_entry"
javap_exception_case "${JDK_DIR}/Contents/Home/lib/modules_expanded/java.base/jdk/internal/module/SystemModules\$default.class_entry"
javap_exception_case "${JDK_DIR}/Contents/Home/jmods/java.base.jmod.unzipped/classes/module-info.class"
javap_exception_case "${JDK_DIR}/Contents/Home/lib/modules_expanded/java.base/module-info.class_entry"

echo "SUCCESSFUL Signature removal"
```

**Comment by theRealAph** [comment]
Looks good. In general we're going to have to decide for ourselves what "effectively identical" means. If a platform actually requires nondeterminism we'll have to put up with it. The ability for anyone to verify the binaries by removing signatures is valuable.

On proprietary platforms it may be hard for us to control what goes in to a build anyway. On Linux systems, at least, all the binary packages need for a build will be available in all the versions, pretty much forever. I don't think we can guarantee that for Mac. So we'll have to do what we can.

**Comment by andrew-m-leonard** [comment]
```
< dbg1/jdk-19+1-debug-image/jdk-19+1/Contents/Home/bin/jlink.dSYM/Contents/Resources/DWARF/jlink:       file format Mach-O arm64
< UUID: A7F74139-3C93-3505-9C3C-4547C674AEA0 (arm64) dbg1/jdk-19+1-debug-image/jdk-19+1/Contents/Home/bin/jlink.dSYM/Contents/Resources/DWARF/jlink
---
> dbg2/jdk-19+1-debug-image/jdk-19+1/Contents/Home/bin/jlink.dSYM/Contents/Resources/DWARF/jlink:       file format Mach-O arm64
> UUID: F4758C32-5866-3604-B3C1-09F7DF3DE534 (arm64) dbg2/jdk-19+1-debug-image/jdk-19+1/Contents/Home/bin/jlink.dSYM/Contents/Resources/DWARF/jlink
```

debugimage's differ due to different UUID, which will be because of the different Signature content.

**Comment by andrew-m-leonard** [comment]
As expected use of the same Xcode version when re-building is necessary.

**Comment by andrew-m-leonard** [comment]
Comparing a Signed Jenkins build with a locally built non-signed build differs because the __LINKEDIT vmsize of the binaries will differ as the Signed binaries are longer thus making vmsize different.
==> This means to achieve a successful comparison the locally built JDK must be built and signed locally in the same manner as Jenkins built JDK. ie:

1. BUILD_ARGS=$BUILD_ARGS --make-exploded-image
2. build-farm/make-adopt-build-farm.sh
3. Create a local MacOS self-signed Certificate (KeychainAccess->Certificate Assistant->Create a Certificate, Identity type=Self-Signed, Certificate type=Code Signing)
4. Sign all executables with "codesign -s <cert> <file>" in:
- build/**/hotspot/variant-server/**/*
- build/**/support/modules_cmds/**/*
- build/**/support/modules_libs/**/*
- build/**/jdk/modules/jdk.jpackage/jdk/jpackage/internal/resources/jpackageapplauncher
5. BUILD_ARGS=$BUILD_ARGS --assemble-exploded-image
6. build-farm/make-adopt-build-farm.sh

**Comment by andrew-m-leonard** [comment]
Required scripts:
compare_mac_jdks:
```
#!/bin/bash

set -e

echo "Comparing JDKs $1 and $2, using CERT $3"

if [ ! -d "$1" ]; then
  echo "$1 does not exist"
  exit 1
fi

if [ ! -d "$2" ]; then
  echo "$2 does not exist"
  exit 1
fi

if [ "x$3" == "x" ]; then
  echo "No local Certificate specified"
  exit 1
fi

# Expand JDK so Signatures can be removed and compared
bash expand_jdk.sh "$1"
bash expand_jdk.sh "$2"

# Remove any extended app attr
xattr -c "$1"
xattr -c "$2"

# Remove any signatures
bash remove_sig.sh "$1"
bash remove_sig.sh "$2"

# Sign both with same local Certificate
bash sign_temp.sh "$1" "$3"
bash sign_temp.sh "$2" "$3" 

# Remove local Certificate, this adjusts __LINKEDIT vmsize identically
bash remove_sig.sh "$1"
bash remove_sig.sh "$2"

diff -qr "$1" "$2"

echo "SUCCESS: JDKs are identical"
```

expand_jdk.sh:
```
#!/bin/bash

set -eu

JDK_DIR="$1/"
TOP_DIR=$(pwd)

javap_exception_case() {
  echo "javap converting 'exception' case $1"
  local classFile="$1"
  javap -p -c -l -s -constants "${classFile}" | grep -v bipush > "${classFile}.javap"
  rm "${classFile}"
}

echo "Expanding: $JDK_DIR"

if [ ! -d "${JDK_DIR}/Contents" ]; then
  echo "$JDK_DIR does not contain the MacOS JDK Contents directory"
  exit 1
fi

echo "Unpacking jmods, containing Signed dylib's"
FILES=$(find "${JDK_DIR}" -type f -path '*.jmod')
for f in $FILES
  do
    echo "Unpacking jmod $f"
    dir=$(dirname "$f")
    filename=$(basename "$f")
    unzipped_dir="$dir/$filename.unzipped"
    mkdir "$unzipped_dir"
    cd "$unzipped_dir"
    jmod extract ../$filename
    rm ../$filename
    cd "$TOP_DIR"
  done

echo "Expanding the 'modules' Image"
#java --add-exports java.base/jdk.internal.jimage=ALL-UNNAMED ExpandJImage "${JDK_DIR}/Contents/Home/lib/modules"
jimage extract --dir "${JDK_DIR}/Contents/Home/lib/modules_expanded" "${JDK_DIR}/Contents/Home/lib/modules"
rm ${JDK_DIR}/Contents/Home/lib/modules

javap_exception_case "${JDK_DIR}/Contents/Home/lib/modules_expanded/java.base/jdk/internal/module/SystemModules\$0.class"
javap_exception_case "${JDK_DIR}/Contents/Home/lib/modules_expanded/java.base/jdk/internal/module/SystemModules\$all.class"
javap_exception_case "${JDK_DIR}/Contents/Home/lib/modules_expanded/java.base/jdk/internal/module/SystemModules\$default.class"
javap_exception_case "${JDK_DIR}/Contents/Home/jmods/java.base.jmod.unzipped/classes/module-info.class"
javap_exception_case "${JDK_DIR}/Contents/Home/lib/modules_expanded/java.base/module-info.class"

echo "SUCCESSFUL Expand"
```

remove_sig.sh:
```
#!/bin/bash

set -eu

JDK_DIR="$1/"
TOP_DIR=$(pwd)

echo "Removing non-deterministic signatures from $JDK_DIR"

if [ ! -d "${JDK_DIR}/Contents" ]; then
  echo "$JDK_DIR does not contain the MacOS JDK Contents directory"
  exit 1
fi

FILES=$(find "${JDK_DIR}" -type f -path '*.dylib' && find "${JDK_DIR}" -type f -path '*/bin/*' && find "${JDK_DIR}" -type f -path '*/lib/*' -not -path '*/modules_expanded/*' && find "${JDK_DIR}" -type f -path '*/jpackageapplauncher*')
for f in $FILES
  do
    echo "Removing any signature from $f"
    codesign --remove-signature $f
  done

echo "SUCCESSFUL Signature removal"
```

sign_temp.sh:
```
#!/bin/bash
set -eu
echo "Signing executable files"
TMP_DIR="$1"
CERT="$2"
FILES=$(find "${TMP_DIR}" -perm +111 -type f -o -name '*.dylib'  -type f || find "${TMP_DIR}" -perm /111 -type f -o -name '*.dylib'  -type f)
for f in $FILES
do
       echo "Signing $f"
       dir=$(dirname "$f")
       file=$(basename "$f")
       codesign -s "$CERT" --options runtime -f --timestamp "$f"
done
```

**Comment by andrew-m-leonard** [comment]
An interesting discovery, the difference in app binary uuid seems related the the length of the build directory folder name. So builds in the following two directories will produce identical uuid's and JDKs, as both paths are 71 characters long!:
```
/Users/jenkins/workspace/build-scripts/jobs/jdk/jdk-mac-aarch64-temurin
/Users/jenkins/andrew_ws/temurin-build-aaaaaaaa-jjj-ggg-lllllll-gggaaaa
```

The binary artifacts to produce the library are identical, so I am suspecting a rather odd non-determinsim in OSX ld64 linker. Others have found similar issues: https://bugs.chromium.org/p/chromium/issues/detail?id=1068970

I've tried to test in a standalone testcase, but a basic HelloWorld.c linked in different directories works fine, so I suspect something unique with the complex compilation and linking for openjdk.

**Comment by sxa** [comment]
@andrew-m-leonard As per other issue is this now effectively "done" as far as the june 2022 plan is concerned? I think you've moved over to Windows now so I'm guessing this is close enough to complete now?

**Comment by andrew-m-leonard** [comment]
jdk-20 (head) is now MacOS producible using the above comparison scripts to compare.
The following issue will create a temurin-build script to perform the comparison : https://github.com/adoptium/temurin-build/issues/3015
