### ISSUE TITLE
Sources archive coming out with _x64_linux_hotspot in the filename

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#2909]
**What are you trying to do?** Download platform-neutral source archive for a release 

**Expected behaviour:** Archive is downloaded in a plaform neutral fashion

**Observed behaviour:** Filename has `_x64_linux_hostpot` in the name

**Any other comments:** While we do build it along with the x64_linux build it is a generic source archive - we do not provide one per platform. Naming it as x64_linux has the potential to be confusing. For previous releases it has come out without that (may have been manually renamed) but for this release it has not. 
As an example: The xlinux pipeline for [17.0.3+10](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/348/artifact/target/linux/x64/temurin/) has x86_linux in the name, but the one in [17.0.2+8](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/284/artifact/target/linux/x64/hotspot/) is not showing it - potentially it was renamed manually at some point. The most recent pipeline output is at https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/lastSuccessfulBuild/artifact/target/linux/x64/temurin.
I'm going to aim to fix up the April releases but we really need to adjust the pipelines so the sources tarball does not come out with a platform name in it, as it's very easy to release with the x64_linux name in it in the current scenario. Since we have already released the April releases with the wrong name, I have manually renamed them in github and uploaded a new sha256 file with the correct name in it.

**Comment by steelhead31** [comment]
I'll pick this up, looks like something that needs fixing ahead of the next release.

**Comment by steelhead31** [comment]
This element of build.sh is never being applied..
createSourceArchive() {
  local sourceDir="${BUILD_CONFIG[WORKSPACE_DIR]}/${BUILD_CONFIG[WORKING_DIR]}/${BUILD_CONFIG[OPENJDK_SOURCE_DIR]}"
  local sourceArchiveTargetPath="$(getSourceArchivePath)"
  local tmpSourceVCS="${BUILD_CONFIG[WORKSPACE_DIR]}/${BUILD_CONFIG[WORKING_DIR]}/tmp-openjdk-git"
  local srcArchiveName
  **if echo ${BUILD_CONFIG[TARGET_FILE_NAME]} | grep -q temurin -; then**
