### ISSUE TITLE
Windows & AIX build fails: cyclonedx-lib\build.xml fails

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2927]
Enabling CycloneDX seems to have broken Windows ?
https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-temurin/56/console
```
18:57:48  Should have the source, I'm at /cygdrive/j/jenkins/tmp/workspace/build/src
18:57:48  ADDING IMAGE TYPE
18:57:48  ===RELEASE FILE GENERATED===
18:57:48  Buildfile: \cygdrive\j\jenkins\tmp\sbin\..\cyclonedx-lib\build.xml does not exist!
18:57:48  Build failed
```

Build on AIX jdk-17 also fails:
https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-temurin/44/console
```
14:00:53  compile:
14:00:53      [mkdir] Created dir: /home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-aix-ppc64-temurin/cyclonedx-lib/build/classes
14:00:53      [javac] /home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-aix-ppc64-temurin/cyclonedx-lib/build.xml:101: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
14:00:53  
14:00:53  BUILD FAILED
14:00:53  /home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-aix-ppc64-temurin/cyclonedx-lib/build.xml:101: Unable to find a javac compiler;
```
Possibly AIX node build-osuosl-aix71-ppc64-1 does not jave a javac compiler available?
Same failure jdk-18, also on same AIX node.

**Comment by zdtsw** [comment]
debugging on windows job.

**Comment by zdtsw** [comment]
similar to this error: https://stackoverflow.com/questions/7516206/cant-locate-build-xml-file-when-running-ant-through-a-shell-script

**Comment by zdtsw** [comment]
so we have two problems:
- ant build
- later when run "java" with ant build result

**Comment by andrew-m-leonard** [comment]
@Haroon-Khel Looking at AIX node build-osuosl-aix71-ppc64-1, it looks as though it is using the location defined by the node configuation variable JDK8_BOOT_DIR, which points at /usr/java8_64/jre, which the name would indicate is a JRE and not a JDK, hence no compiler? Could we upgrade it to a JDK please?

**Comment by zdtsw** [comment]
```
09:08:22  C:\openjdk\jdk-8/bin/java -cp J:\jenkins\tmp\cyclonedx-lib\build\jar\temurin-gen-sbom.jar;J:\jenkins\tmp\cyclonedx-lib\build\jar\cyclonedx-core-java.jar;J:\jenkins\tmp\cyclonedx-lib\build\jar\jackson-core.jar;J:\jenkins\tmp\cyclonedx-lib\build\jar\jackson-dataformat-xml.jar;J:\jenkins\tmp\cyclonedx-lib\build\jar\jackson-databind.jar;J:\jenkins\tmp\cyclonedx-lib\build\jar\jackson-annotations.jar;J:\jenkins\tmp\cyclonedx-lib\build\jar\json-schema.jar;J:\jenkins\tmp\cyclonedx-lib\build\jar\commons-codec.jar;J:\jenkins\tmp\cyclonedx-lib\build\jar\commons-io.jar; temurin.sbom.TemurinGenSBOM --createNewSBOM --jsonFile J:\jenkins\tmp\workspace\target\metadata\sbom.json --name Temurin --version 19-beta+22-202205170623
09:08:23  DEBUG DONE!
09:08:23  org.cyclonedx.exception.ParseException: Unable to parse BOM from Reader
09:08:23  	at org.cyclonedx.parsers.JsonParser.parse(JsonParser.java:92)
09:08:23  	at temurin.sbom.TemurinGenSBOM.readJSONfile(Unknown Source)
09:08:23  	at temurin.sbom.TemurinGenSBOM.addMetadata(Unknown Source)
09:08:23  	at temurin.sbom.TemurinGenSBOM.main(Unknown Source)
09:08:23  Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
09:08:23   at [Source: (FileReader); line: 1, column: 0]
09:08:23  	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
09:08:23  	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4688)
09:08:23  	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4586)
09:08:23  	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3561)
09:08:23  	at org.cyclonedx.parsers.JsonParser.parse(JsonParser.java:90)
09:08:23  	... 3 more
09:08:23  Exception in thread "main" java.lang.NullPointerException
09:08:23  	at temurin.sbom.TemurinGenSBOM.addMetadata(Unknown Source)
09:08:23  	at temurin.sbom.TemurinGenSBOM.main(Unknown Source)
```
feel like this is something in the cyclonedx-lib

**Comment by zdtsw** [comment]
this is very strange https://github.com/CycloneDX/cyclonedx-core-java/blob/8efaa9135e60f20c226b2b5c68c2bb6bd585a457/src/main/java/org/cyclonedx/generators/json/BomJsonGenerator13.java#L77
so when we call `String json = bomGen.toJsonString();` even exception, still it returns "" which wont work in the next step.

**Comment by zdtsw** [comment]
also think we should use [CycloneDxSchema.Version.VERSION_14](https://cyclonedx.org/schema/bom-1.4.schema.json) than [CycloneDxSchema.Version.VERSION_13](https://cyclonedx.org/schema/bom-1.3.schema.json)

**Comment by zdtsw** [comment]
now for some funny reason I am able to reproduce this on my local RHEL:
```
[build/jar]$ java -cp temurin-gen-sbom.jar:cyclonedx-core-java.jar:jackson-core.jar:jackson-dataformat-xml.jar:jackson-databind.jar:jackson-annotations.jar:json-schema.jar:commons-codec.jar:commons-io.jar: temurin.sbom.TemurinGenSBOM --verbose --createNewSBOM --jsonFile b.json --name Temurin --version 19-beta+22-202205180908
SBOM is emtpy string
DEBUG sbom.json START: 
DEBUG sbom.json DONE
```

**Comment by zdtsw** [comment]
I still do not know what exactly is the problem:
what can be found so far, on my local RHEL is same as what is observed in Jenkins on Windows, that createBom() did not really create a bom which written into a Json file, which leads to the next step for addMetadata() cannot read a empty json file and cause eception in readJSONfile()
I have tried to upgrade to 7.1.4 (even I do not see the code has been much changed since 7.0.0 in java-core) and still the same.
Local java I am using is 
```
java --version
openjdk 18.0.1 2022-04-19
OpenJDK Runtime Environment Temurin-18.0.1+10 (build 18.0.1+10)
OpenJDK 64-Bit Server VM Temurin-18.0.1+10 (build 18.0.1+10, mixed mode, sharing)
```

**Comment by zdtsw** [comment]
for some magic reason, it is working now https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-temurin/82/console
with commit a366a42dc933983abb378747a0710528be0dc633
