### ISSUE TITLE
jdk8u-solaris-sparcv9-temurin : Unable to find a suitable JAVA_HOME to build the cyclonedx-lib

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2942]
https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-sparcv9-temurin/65/console
```
22:10:41  Unable to find a suitable JAVA_HOME to build the cyclonedx-lib
```

Maybe Solaris machine needs a suitable JDK or environment setting?

**Comment by zdtsw** [comment]
i take a look
