### ISSUE TITLE
hotspot、openj9

### ISSUE THREAD

**Issue by tonycody** [adoptium/temurin-build#2947]
Formerly AdoptOpenJDK, the Eclipse Adoptium Temurin™ project.

but,https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=openj9 support hotspot and openj9.

The version of Temurin submitted to Sdkman does not show whether it is based on Hotspot or OpenJ9?

https://sdkman.io/jdks#tem

<img width="721" alt="image" src="https://user-images.githubusercontent.com/6773121/170421267-a25c7ba7-3de5-49cf-a520-034ba0a61da1.png">

**Comment by karianna** [comment]
OpenJ9 is no longer supplied by this project, instead you can get Semeru binaries (effectively the same thing) from IBM.  Please contact SDKman for how they are bringing that in.
