### ISSUE TITLE
Temurin Mac jdk11+ Info.plist has different JVMVendor values depending which build method you use

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2949]
jdk11+ Info.plist contains:
Built via Jenkins using --make-exploded/assemble-image two stage method:
```
                <key>JVMVendor</key>
                <string>Eclipse Adoptium</string>
```
Built standalone just using standard invocation:
```
                <key>JVMVendor</key>
                <string>Eclipse Temurin</string>
```

The reason being the make/codesign/assemble-exploded steps for jdk11+  in sbin/build.sh setPlistValueForMacOS() does nothing because BUILD_CONFIG[VENDOR] gets set in:
https://github.com/adoptium/temurin-build/blob/20b03b2ffcb660460a1a64d5b0a5577331c0778a/sbin/build.sh#L1816
which never gets called doing a 
https://github.com/adoptium/temurin-build/blob/20b03b2ffcb660460a1a64d5b0a5577331c0778a/sbin/build.sh#L1789

**Comment by smlambert** [comment]
Related: https://github.com/adoptium/temurin-build/pull/2705, https://github.com/adoptium/temurin-build/issues/2664

**Comment by andrew-m-leonard** [comment]
I suspect then this code needs an only if jdk8:
https://github.com/adoptium/temurin-build/blob/20b03b2ffcb660460a1a64d5b0a5577331c0778a/sbin/build.sh#L1215

**Comment by andrew-m-leonard** [comment]
I've updated the description to reflect the problem.
