### ISSUE TITLE
SBOM metadata labels the image as a jdk

### ISSUE THREAD

**Issue by johnoliver** [adoptium/temurin-build#2958]
The sbom metadata, such as:

https://github.com/adoptium/temurin17-binaries/releases/download/jdk17u-2022-05-27-19-32-beta/OpenJDK17U-sbom_aarch64_alpine-linux_hotspot_2022-05-27-17-01.tar.gz.json

have the binary_type set to jdk. This incorrectly labels them as a jdk archive.

**Comment by smlambert** [comment]
FYI @andrew-m-leonard
