### ISSUE TITLE
Dual master node context causing old Mac and Windows artifacts to remain

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2959]
It seems with the 2 master nodes "Jenkins" and "C3jenkins", we are getting previous build artifacts for Windows and Mac, eg:
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-temurin/93/artifact/workspace/target/
```
  | OpenJDK-jdk_x64_windows_hotspot_2022-05-28-03-30.msi | May 31, 2022, 5:56:10 PM | 166.44 MB | view
  | OpenJDK-jdk_x64_windows_hotspot_2022-05-28-03-30.msi.json | May 31, 2022, 6:01:13 PM | 27.52 KB | view
  | OpenJDK-jdk_x64_windows_hotspot_2022-05-28-03-30.msi.sha256.txt | May 31, 2022, 6:01:09 PM | 136 B | view
  | OpenJDK-jdk_x64_windows_hotspot_2022-05-28-03-30.zip | May 28, 2022, 7:20:55 AM | 186.78 MB | view
  | OpenJDK-jdk_x64_windows_hotspot_2022-05-28-03-30.zip.json | May 31, 2022, 5:54:46 PM | 27.52 KB | view
  | OpenJDK-jdk_x64_windows_hotspot_2022-05-28-03-30.zip.sha256.txt | May 28, 2022, 7:29:06 AM | 136 B | view
  | OpenJDK-jdk_x64_windows_hotspot_2022-05-31-15-24.msi | May 31, 2022, 5:56:18 PM | 166.44 MB | view
  | OpenJDK-jdk_x64_windows_hotspot_2022-05-31-15-24.msi.json | May 31, 2022, 6:01:16 PM | 27.52 KB | view
  | OpenJDK-jdk_x64_windows_hotspot_2022-05-31-15-24.msi.sha256.txt | May 31, 2022, 6:01:10 PM | 136 B | view
  | OpenJDK-jdk_x64_windows_hotspot_2022-05-31-15-24.zip | May 31, 2022, 5:34:29 PM | 186.79 MB | view
  | OpenJDK-jdk_x64_windows_hotspot_2022-05-31-15-24.zip.json | May 31, 2022, 6:01:12 PM | 27.52 KB | view
  | OpenJDK-jdk_x64_windows_hotspot_2022-05-31-15-24.zip.sha256.txt | May 31, 2022, 5:42:46 PM | 136 B | view
```
I think this is because previously with just one Jenkins master the "sign_build" stage cleared all of the workspace/target out, prior to the create_installer_windows|mac stages, but now if those run on the other master they are not removed...

**Comment by sxa** [comment]
Do you know where that clearup is occurring? Sounds like it's potentially occurring on a machine that isn't the one the pipeline is using...

I've dropped the number of executors on the jenkins controller to zero which should stop anything targetted for `master` (Other than the lightweight jobs that don't use an executor from running on it any more and will re-run the pipeline and see what happens...

**Comment by andrew-m-leonard** [comment]
@sxa I believe the problem is that there is **no** clearup happening for buildMac/WindowsInstaller stage that occurs on the builtin|master context

**Comment by sxa** [comment]
@andrew-m-leonard I've re-enabled the executor on the build-in node (Note that it is NOT labelled as `master`)
If you need to fiddle around with which of the two have master feel free but I'd recommend logging changes in here as you do it :-)
