### ISSUE TITLE
MacOS JDKs are missing the NOTICE file

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2972]
The MacOS JDKs are missing the "NOTICE" file which is generated from https://github.com/adoptium/temurin-build/blob/master/sbin/NOTICE.template
All other platforms have this in the JDK archive.

I suspect it's due to the way MacOS is done in a 2 stage explode & assemble for codesign in the Jenkins pipelines...
If I build as a single phase like other platforms, the NOTICE is generated.

**Comment by andrew-m-leonard** [comment]
I reckon this PR merged today should resolve this: https://github.com/adoptium/temurin-build/pull/2951

**Comment by gdams** [comment]
@andrew-m-leonard can this be closed now?

**Comment by andrew-m-leonard** [comment]
yes fixed
