### ISSUE TITLE
Container start fails with insufficient memory on ubuntu:jammy

### ISSUE THREAD

**Issue by alexbde** [adoptium/temurin-build#2974]
**What are you trying to do?**

Hi! Using the latest version of `eclipse-temurin:8-jre` (same as `:8u332-b09-jre-jammy`) as base image starting our (Spring Boot) applications fails. The root cause seems to be the upgrade from underlying `ubuntu:focal` to `ubuntu:jammy`.

**Expected behaviour:**

The application starts.

**Observed behaviour:**

The application start fails with following message:

```
Picked up JAVA_TOOL_OPTIONS: -javaagent:/<redacted>.jar
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
```

Downgrading to `eclipse-temurin:8-jre-focal` (same as `:8u332-b09-jre-focal`) solves the issue.

**Any other comments:**

Flyway has got the same issue with `eclipse-temurin:11-jre`: https://github.com/flyway/flyway/issues/3457 and solved it by downgrading/pinning to focal-based `:11.0.14.1_1-jre`: https://github.com/flyway/flyway-docker/pull/87.

**Comment by karianna** [comment]
@alexbde are you running in a Docker container?

**Comment by alexbde** [comment]
`docker version` output from one of our Docker swarm worker nodes:

```
Client: Mirantis Container Runtime
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        105e9a6
 Built:             Mon May 17 16:27:50 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Mirantis Container Runtime (this node is not a swarm manager - check license status on a manager node)
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       1a7d997
  Built:            Mon May 17 16:25:14 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by alexbde** [comment]
@karianna okay, thank you very much!

**Comment by karianna** [comment]
Do reopen this if that doesn't work (but we've have ~5 reports of this over the past week, so I'm pretty sure :-)

**Comment by jmmAVGO** [comment]
FWIW (I'm not the OP!) my team was encountering a similar issue using 20.10.9 this week; upgrading to 20.10.17 seems to have made the issue disappear for us

**Comment by RealStickman** [comment]
Older versions of podman seem to suffer from the same issue, as you can read in the issue mentioned just above.  
Upgrading to the latest version of podman fixed it.

**Comment by holgerstolzenberg** [comment]
Same for us in another context but the key info here is that we switched our Temurin based JDK `eclipse-temurin:17.0.3_7-jre` to a focal based image `eclipse-temurin:17.0.3_7-jre-focal`.

Side note: The Docker upgrade did not work for us, it had no effect.

**Comment by pschichtel** [comment]
Given that the symptom seems to be that too little memory is configured for some memory region, is it possible that any of you are using java's cgroup support to calculate memory limits based on docker's resource limits? I remember seeing a similar issue a while (1-2 years) back, when I configured a resource limit too small. We are not affected by this issue, but we are running on alpine-based images and we use explicit -Xmx values.

**Comment by holgerstolzenberg** [comment]
> is it possible that any of you are using java's cgroup support to calculate memory limits

Yes - we are using this feature.

**Comment by bhaugeea** [comment]
The upgrade worked for me. Thanks!

**Comment by lerminou** [comment]
Neither the upgrade or an older base image worked, please reopen it
