### ISSUE TITLE
Enable reproducible builds on Windows x64 jdk-20

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2978]
- Test reproducible builds for Windows x64 jdk-19 via Jenkins
- Ensure reproducible across multiple nodes and build directories

**Comment by andrew-m-leonard** [comment]
jdk-20 built temurin WIndows x64 are identically reproducible on the same build machine, if the binaries are not signed.

Signed JDK binaries are different, much like for MacOS.

They are signed using the Eclipse signing service:
https://github.com/eclipse-cbi/org.eclipse.cbi/blob/dd82d290ba8695cf6b08fb3b1acba042889bec17/webservice/signing/windows/src/main/java/org/eclipse/cbi/webservice/signing/windows/OSSLCodesigner.java#L66

Which uses open source osslsigncode: https://github.com/mtrojnar/osslsigncode

osslsigncode has a -remove_signature option, which we maybe able to use to remove the signature to do a comparison.

**Comment by andrew-m-leonard** [comment]
Successful reproducible Win64 JDK comparison can be achieved by:
1. Download, build and install osslsigncode from here: https://github.com/mtrojnar/osslsigncode
2. Run the following bash script against both unzipped JDK.zip binaries to be compared:
```
#!/bin/bash

JDK_DIR="$1"

if [ ! -d "${JDK_DIR}" ]; then
  echo "$JDK_DIR does not exist"
  exit 1
fi

echo "Removing all osslsigncode Signatures from ${JDK_DIR}"
FILES=$(find "${JDK_DIR}" -type f -path '*.exe' && find "${JDK_DIR}" -type f -path '*.dll')
for f in $FILES
  do
    echo "Removing signature from $f"
    if osslsigncode remove-signature $f $f.unsigned ; then
        rm $f
        mv $f.unsigned $f
	echo "  ==> Successfully removed signature from $f"
    else
	echo "  ==> $f contains no signature"
    fi
  done

echo "Successfully removed all osslsigncode Signatures from ${JDK_DIR}"
```
3. Compare both unsigned jdk dirs:
```
diff -r jdk1 jdk2
```

**Comment by andrew-m-leonard** [comment]
The fix level of MSVC toolkit is important for reproducibility, it must be identical, even a "fix level" version makes a difference. So for example using 19.27.29112 compared to 19.27.29111, will be non-reproducible.

In an attempt to ensure identical toolkits, I am testing creating an offline toolkit network installation using the instructions here: https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2022

**Comment by andrew-m-leonard** [comment]
To create a installation layout using vs_community.exe, the latest version is required: https://aka.ms/vs/16/release/vs_community.exe
Using the current infrastructure reference one does not work: https://download.visualstudio.microsoft.com/download/pr/6b655578-de8c-4862-ad77-65044ca714cf/f29399a618bd3a8d1dcc96d349453f686b6176590d904308402a6402543e310b/vs_Community.exe

**Comment by andrew-m-leonard** [comment]
Our temurin builds seem to pickup the vcruntime140.dll from the bootjdk being used:
```
15:22:58  configure: Found vcruntime140.dll at /cygdrive/c/workspace/openjdk-build/jdk-19/bin/vcruntime140.dll using well-known location in Boot JDK
```

I believe that is because the logic in make/autoconf/toolchain_microsoft.m4 searches:
```
$VCToolsRedistDir/$vs_target_cpu/microsoft.vc${VS_VERSION_INTERNAL}.crt

which resolves to:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Redist\MSVC\14.29.30133\x64\microsoft.vc142.crt
```
Which does not exist:
```
./Microsoft Visual Studio/2019/Community/VC/Redist/MSVC/14.16.27012/onecore/x64/Microsoft.VC141.CRT/vcruntime140.dll
./Microsoft Visual Studio/2019/Community/VC/Redist/MSVC/14.16.27012/onecore/x86/Microsoft.VC141.CRT/vcruntime140.dll
./Microsoft Visual Studio/2019/Community/VC/Redist/MSVC/14.16.27012/x64/Microsoft.VC141.CRT/vcruntime140.dll
./Microsoft Visual Studio/2019/Community/VC/Redist/MSVC/14.16.27012/x86/Microsoft.VC141.CRT/vcruntime140.dll
./Microsoft Visual Studio/2019/Community/VC/Redist/MSVC/14.29.30133/arm64/Microsoft.VC142.CRT/vcruntime140.dll
./Microsoft Visual Studio/2019/Community/VC/Redist/MSVC/14.29.30133/onecore/arm64/Microsoft.VC142.CRT/vcruntime140.dll
```

**Comment by andrew-m-leonard** [comment]
It looks like the installation layout only contains the arm64 redist runtime DLLs, even though the layout was created on an x64 box... odd!
Will try re-creating the layout.

**Comment by andrew-m-leonard** [comment]
1. First ensure on the machine you're creating the layout that no VS components/programs are installed, including the ReDist programs.
2. Created the VS2019 layout using the following:
```
vs_community.exe --layout VSLayout2019 --add Microsoft.VisualStudio.Workload.NativeDesktop;includeRecommended;includeOptional --add Microsoft.VisualStudio.Component.VC.Tools.ARM64 --add Microsoft.VisualStudio.Component.VC.ATL.ARM64 --add Microsoft.VisualStudio.Component.VC.MFC.ARM64
```

**Comment by andrew-m-leonard** [comment]
So the explicit VS2019 x64 redist DLLs were not added to the layout because they were not explicitly selected, instead for some reason the 2017 ones were installed. To select the VS2019 ones, we need to explicitly add the x86.x64 VC Tools using:
```
--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64
```

**Comment by andrew-m-leonard** [comment]
@sxa I have recreated the layout with the necessary redist's, vslayout2019.tar.gz is available on my test machine. I we can recreate the test Jenkins node with this please? When installing we may need to also specify:
```
--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64
```
To ensure the 2019 x64 redist's get installed.
thanks

**Comment by sxa** [comment]
@andrew-m-leonard When I run the above command it starts up the GUI installer and gives me options for "Install while downloading" or "Download all, then install". Is that correct? `--noweb` is specified on my command line. Will it do the wrong thing if I let it install?

**Comment by andrew-m-leonard** [comment]
> @andrew-m-leonard When I run the above command it starts up the GUI installer and gives me options for "Install while downloading" or "Download all, then install". Is that correct? `--noweb` is specified on my command line. Will it do the wrong thing if I let it install?

@sxa To run sliently, `--quiet --norestart --wait` need adding, i'm just testing that myself

**Comment by andrew-m-leonard** [comment]
@sxa yes, that worked for me.

**Comment by sxa** [comment]
Thanks - re-running now. Hopefully that won't result it in pulling anything from the web in secret!

**Comment by sxa** [comment]
https://ci.adoptopenjdk.net/computer/build%2Dazure%2Dwin2012r2%2Dx64%2D3%2Dsxa/ now installed and live.

**Comment by andrew-m-leonard** [comment]
Successfully reproduced (except for know CDS archive differences) two jdk-20 Win64 JDKs:
1) First JDK built via Jenkins at ci.adopopenjdk.net (https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-temurin/187/)
2) Second JDK built on a manually setup Windows Server2022 machine, using the same VS2019 Layout as (1)

The comparison script [above](https://github.com/adoptium/temurin-build/issues/2978#issuecomment-1184778371) was updated to handle specific differences caused by:
1) Signed signature presence (requires removal, then both signing with a temporary self-signed, which is then removed, this is to ensure the Windows PE file CheckSum value is identical)
2) Unpacking of "modules" Image, so embedded signed artifacts can have the signatures removed
3) Unpacking of src.zip, so that any differences in Group file permissions between build systems is neutralized.

Differences after script processing of jdk1 and jdk2:
```
anleonar@anleonar-mac Downloads % diff -r jdk1 jdk2
Binary files jdk1/jdk-20+5/bin/server/classes.jsa and jdk2/jdk-20+5/bin/server/classes.jsa differ
Binary files jdk1/jdk-20+5/bin/server/classes_nocoops.jsa and jdk2/jdk-20+5/bin/server/classes_nocoops.jsa differ
diff -r jdk1/jdk-20+5/release jdk2/jdk-20+5/release
15c15
< BUILD_INFO="OS: Windows Server 2012 R2 Version: 6.3"
---
> BUILD_INFO="OS: Windows Server 2022 Version: 10.0"
```

**Comment by andrew-m-leonard** [comment]
Full command with path options:
```
﻿.\vs_community.exe --installPath d:\VS2019 --path shared="d:\VS2019Shared" --path cache="d:\VS2019Cache" --nocache --quiet --norestart --wait --noweb --add Microsoft.VisualStudio.Workload.NativeDesktop;includeRecommended;includeOptional --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.Tools.ARM64 --add Microsoft.VisualStudio.Component.VC.ATL.ARM64 --add Microsoft.VisualStudio.Component.VC.MFC.ARM64
```

**Comment by andrew-m-leonard** [comment]
New repro build of jdk-20+35: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk20/job/jdk20-windows-x64-temurin/23/

**Comment by andrew-m-leonard** [comment]
jdk-20 builds for Win x64 are identically reproducible, when built with the same MS VS2019 install image version.
