### ISSUE TITLE
OS_FULL_VERSION doesn't list Alpine OS version

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#2997]
Noted while reverting from Alpine 3.16 to Alpine 3.15 in https://github.com/adoptium/infrastructure/pull/2628

The recent change to use `OS_FULL_VERSION` in the SBOM (https://github.com/adoptium/temurin-build/pull/2991) means that the OS is [showing as](https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-alpine-linux-x64-temurin/69/consoleFull)
```
16:56:21  BUILD_CONFIG[OS_FULL_VERSION]="Linux 4.15.0-1113-azure : Alpine Linux"
```
which doesn't explicitly list the Alpine version (Only the kernel, which is dependent on the host it's running on)

We should probably modify https://github.com/adoptium/temurin-build/blob/abb4d36cfe18ceb3be70d8b30d28a1eae4262863/sbin/common/config_init.sh#L387 to pull the PRETTY_NAME from `/etc/os-release` or maybe just the whole contents of `alpine-release` which just has the version number bolted on to the end of the current output

**Comment by zdtsw** [comment]
from last night's openjdk8-pipeline build, it looks correctly
```
    "properties" : [
      {
        "name" : "OS_FULL_VERSION",
        "value" : "Linux 4.15.0-1113-azure : Alpine Linux"
      },
```

**Comment by steelhead31** [comment]
> from last night's openjdk8-pipeline build, it looks correctly
> 
> ```
>     "properties" : [
>       {
>         "name" : "OS_FULL_VERSION",
>         "value" : "Linux 4.15.0-1113-azure : Alpine Linux"
>       },
> ```

I'll run it on an alpine docker container this morning, see what it looks like, it may have been running on an actual alpine host, so the kernel may actually have been alpine.

**Comment by sxa** [comment]
> from last night's openjdk8-pipeline build, it looks correctly
>         "value" : "Linux 4.15.0-1113-azure : Alpine Linux"

Why is that correct? It does not list the version of Alpine which was used for the build (Should be 3.15) in the output anywhere (What you've posted is the same as the line I posted in the description)

**Comment by steelhead31** [comment]
This is from my docker build

"properties" : \[  
     {  
       "name" : "OS\_FULL\_VERSION",  
       "value" : "Linux 4.18.0-372.9.1.el8.x86\_64 : Alpine Linux"  
     },

My PR changes it to   
 

"properties" : \[  
     {  
       "name" : "OS\_FULL\_VERSION",  
       "value" : "Alpine Linux v3.14"  
     },

**Comment by sxa** [comment]
Do we have the kernel version listed somewhere else? That is something we should have captured somewhere

**Comment by steelhead31** [comment]
I'll create a seperate issue to add the kernel version to the sbom,   hostnamectl | grep Kernel might be a good information source for it

**Comment by steelhead31** [comment]
@sxa & @zdtsw Im going to return the PR to draft, and look to improve the os(pretty) and kernel version reporting in the one PR, as its all quite inter-related, and quite dependent on context, ie docker vs VM or Tin

**Comment by steelhead31** [comment]
Having spent an hour investigating, can we merge this PR #3007 in, and treat the other as a separate piece of work, its much bigger than I first thought, it will improve the situation for alpine, but not have any impact anywhere else. Im producing a table of what is returned in various scenarios, so we can clearly define the longer term solution.
