### ISSUE TITLE
JDK11 / Win 32 Build Broken

### ISSUE THREAD

**Issue by steelhead31** [adoptium/temurin-build#3008]
The JDK11 build has been failing since 21st June.

https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x86-32-temurin/

Believe this may be due to the change to VS2019, currently investigating 

New build : https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x86-32-temurin/77/

**Comment by steelhead31** [comment]
PR Merged, builds now working.

**Comment by sxa** [comment]
Note: The PR was this one: https://github.com/adoptium/temurin-build/pull/3009
