### ISSUE TITLE
Java -version doesn't work for the latest Java 10 build.

### ISSUE THREAD

**Issue by gaolibj** [adoptium/temurin-build#301]
Try the latest AIX 64 bit build(OpenJDK10-OPENJ9_ppc64_AIX_20180416.tar.gz) for Java 10 here https://adoptopenjdk.net/nightly.html?variant=openjdk10-openj9.    Seems it failed with following error message.  

../jdk10/jdk-10+46> ./bin/java -version
JVMJ9VM011W Unable to load jclse10_29:     0509-022 Cannot load module /afs/rchland.ibm.com/usr8/j9/src/rebuilt/jdk10/jdk-10+46/lib/compressedrefs/libjclse10_29.so.
    0509-026 System error: A file or directory in the path name does not exist.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Library libjclse10_29.so doesn’t shipped in this packages.   -(

Anyone can help to take a look?

**Comment by andrew-m-leonard** [comment]
Extensions issue: https://github.com/ibmruntimes/openj9-openjdk-jdk10/issues/19

**Comment by sophia-guo** [comment]
Extensions issue: https://github.com/AdoptOpenJDK/openjdk-build/issues/264

**Comment by gaolibj** [comment]
FYI.  I didn't do Jlink to get a new jre image in my test and only unzip the packages downloaded and run command 'java -version'.  It failed as my update above.

**Comment by sophia-guo** [comment]
@gaolibj the sdk is broken due to  the reason @andrew-m-leonard mentioned. The broken sdk was unexpectedly published due to the reason I mentioned above.  I believe if you download sdk of April 11, it should be fine.
