### ISSUE TITLE
Create a script to compare reproducible MacOS jdk-19 builds

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3015]
Using the scripts documented here: https://github.com/adoptium/temurin-build/issues/2899#issuecomment-1149963539
Create a temuring-build script to perform the necessary reproducible MacOS comparison.

**Comment by zdtsw** [comment]
I have several questions:
1. is only Mac can run this script?
2. if this should be a part of verification step in Jenkins job, does Jenkins agent have "codesign" installed?
3. where this local cerificate will be if it is from Jenkins agent?

**Comment by andrew-m-leonard** [comment]
> I have several questions:
> 
>     1. is only Mac can run this script?
> 
>     2. if this should be a part of verification step in Jenkins job, does Jenkins agent have "codesign" installed?
> 
>     3. where this local cerificate will be if it is from Jenkins agent?

1. Yes, as requires "codesign"
2. Yes, it's part of Xcode on the build nodes
3. We will need to find one/create one, a similar self-signed cert will do
