### ISSUE TITLE
Successful Builds contain error message: Required context class hudson.FilePath is missing

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3023]
Builds seem to succeed, but end of the console shows error message:
```
11:51:44  Required context class hudson.FilePath is missing
11:51:44  Perhaps you forgot to surround the code with a step that provides this, such as: node
```
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-linux-x64-temurin/108/console

**Comment by andrew-m-leonard** [comment]
Seem to start after the GPG sign stage was added

**Comment by karianna** [comment]
Might help: https://support.cloudbees.com/hc/en-us/articles/4402585187483-How-to-troubleshoot-hudson-FilePath-is-missing-in-a-Pipeline-run
