### ISSUE TITLE
Need a SmokeTest to verify the number of CACerts in the built jdk is correct

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3034]
Verify that:
   num_in_keystore=$("$KEYTOOL" -v -list -storepass changeit -keystore jdk/lib/security/cacerts | grep -c "Alias name:")
matches the number of unique Certificates listed by security/mk-ca-bundle.pl

**Comment by zdtsw** [comment]
so in this case we need to add a counter after `rm "$FILE"`

**Comment by andrew-m-leonard** [comment]
@zdtsw  Yeah so the correct JDK image number of Certs should be "mk-ca-bundle.pl number" - "number of openssl alias duplicates"

**Comment by andrew-m-leonard** [comment]
The SmokeTest needs some new code, the reason being because the output from this script:

    <jdk17 : keystore
    >=jdk17 : src file certs

Both get fed into the OpenJDK build that then import either into the image/jdk/lib/security/cacerts keystore, there is always the possibility that build fails or is incorrect, so we need to ensure it is good. One other issue that concerns me is if say a bug or network glitch occurs in [mk-ca-bundle.pl](https://github.com/adoptium/temurin-build/blob/master/security/mk-ca-bundle.pl) Perl script and say it returns 0 certs, how do we catch that? Should we hard code the expected number (ie.135) as it very rarely changes, or do we have a test that actually checks the expected list like OpenJDK do: https://github.com/adoptium/jdk17u/blob/5de8b78504df916d88c9e01941c4e27bfe49e949/test/jdk/sun/security/lib/cacerts/VerifyCACerts.java#L50

**Comment by andrew-m-leonard** [comment]
I'm actually in favour of adding a similar test to [VeriftCACerts](https://github.com/adoptium/jdk17u/blob/5de8b78504df916d88c9e01941c4e27bfe49e949/test/jdk/sun/security/lib/cacerts/VerifyCACerts.java#L50) to our SmokeTest: https://github.com/adoptium/temurin-build/tree/master/test/functional/buildAndPackage

**Comment by zdtsw** [comment]
on a newly built jdk19 (after the fix of cacerts): 
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk19/job/jdk19-mac-x64-temurin_SmokeTests/17/console

and test failed on an old build 
https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-arm-temurin_SmokeTests/37/console

**Comment by zdtsw** [comment]
for this issue to verify the number is done.
we can create new issue if need to check explicit content of cacerts in the future
