### ISSUE TITLE
Windows 11.0.16 build failed to start due to lacking vcruntime140_1.dll

### ISSUE THREAD

**Issue by toshiona** [adoptium/temurin-build#3052]
```
> java -version
Error: loading: C:\Users\jenkins\OpenJDK11U-jdk_x64_windows_hotspot_2022-07-15-02-48\jdk-11.0.16+7\bin\msvcp140.dll
Error: loading: C:\Users\jenkins\OpenJDK11U-jdk_x64_windows_hotspot_2022-07-15-02-48\jdk-11.0.16+7\bin\server\jvm.dll
```
After copying vcruntime140_1.dll from Temurin 17 build, it worked.
```
> openjdk version "11.0.16-beta" 2022-07-19
OpenJDK Runtime Environment Temurin-11.0.16+7-202207141840 (build 11.0.16-beta+7-202207141840)
OpenJDK 64-Bit Server VM Temurin-11.0.16+7-202207141840 (build 11.0.16-beta+7-202207141840, mixed mode)
```

My environments are Windows Server 2019, 2016 and 2012R2. All of them could recreate the issue.

**Comment by sxa** [comment]
I think I've just hit the same problem ...

**Comment by sxa** [comment]
Initial thoughts is that this is going to have been a result of [switching the build up to VS2019](https://github.com/adoptium/temurin-build/pull/2992). 

@toshiona was the previous GA level 11.0.15 ok for you?

**Comment by toshiona** [comment]
@sxa yes, 11.0.15 GA has no problem.

**Comment by sxa** [comment]
Thanks for confirming - we're going to build 11.0.16 with the earlier visual studio for now to mitigate this.

**Comment by gdams** [comment]
I have backported the fix into jdk11u-dev. It should be in jdk11u mainstream shortly

**Comment by toshiona** [comment]
Thank you @gdams. I worry that the current jdk11u-dev has already been in ramp down and mainstream is 11.0.18.
I think it should be ported to 11.0.17 as well by 'jdk11u-critical-request' or change VS.

**Comment by gdams** [comment]
> Thank you @gdams. I worry that the current jdk11u-dev has already been in ramp down and mainstream is 11.0.18.
I think it should be ported to 11.0.17 as well by 'jdk11u-critical-request' or change VS.

It's unlikely that it will be merged in a critical request as it comes attached to a [much larger backport](https://github.com/openjdk/jdk11u-dev/commit/75b3e45fe9d16a8e29f4fd51f93e01acc9436562).

Adoptium will likely have to build with VS2017 for the next release

**Comment by toshiona** [comment]
@gdams 
Nightly 11 build (Temurin-11.0.17+7-202210131811) still has this problem, which java failed to start without "vcruntime140_1.dll". I'd like to make sure the release build of 11.0.17 doesn't have the issue. Could you double check that, please?

**Comment by gdams** [comment]
@toshiona my [backport](https://github.com/adoptium/jdk11u/commit/2548ed31aeb255a61644885c501667a74f90ebc7) is now in mainstream JDK11u so this should be fixed. I've triggered a build here (https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-temurin/135/) and will post the binary once it's available for you to test

**Comment by gdams** [comment]
Here is a link to a build with the patches in it https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-temurin/135/artifact/workspace/target/OpenJDK11U-jdk_x64_windows_hotspot_2022-11-02-10-44.zip

**Comment by toshiona** [comment]
@gdams Thank you for the updates. Yes, I confirmed that build didn't have this problem. Closing.
