### ISSUE TITLE
sha256.txt files sometimes have full path to the target tarball in it

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#3058]
From Jan2022 retrospective:

Need to sort the checksums `sha256.txt` where some of them seem to have a full path to the file and others don't (Correct option is NOT to have a path name in there). Causes problems for the Linux installer processes (and is also just wrong IMHO)

_Originally posted by @sxa in https://github.com/adoptium/adoptium/issues/104#issuecomment-1031454239_

**Comment by sophia-guo** [comment]
Dup of #2865
