### ISSUE TITLE
How to cross compile

### ISSUE THREAD

**Issue by kerner1000** [adoptium/temurin-build#3059]
I would like to build on `arm64` for `x86_64`.

Currently, I build via

`./makejdk-any-platform.sh --docker --clean-docker-build --create-jre-image jdk18u`

How do I need to adjust my call to build for `X86_64`?

**Comment by karianna** [comment]
See https://github.com/openjdk/jdk/blob/master/doc/building.md#cross-compiling for details.

**Comment by kerner1000** [comment]
Thanks for the link.
Still some questions remain:
+ What are valid params for `--openjdk-target`?
+ Is this compatible with the Docker pipeline? Currenlty I am invoking `./makejdk-any-platform.sh --docker --clean-docker-build`

**Comment by karianna** [comment]
> Thanks for the link. Still some questions remain:
> 
> * What are valid params for `--openjdk-target`?
> * Is this compatible with the Docker pipeline? Currenlty I am invoking `./makejdk-any-platform.sh --docker --clean-docker-build`

Not sure of hte full list for the first but I think `aarch64-linux-gnu` and `x86_64-unknown-linux` work for the two main platforms.

I've not tried it with the Docker builds, in theory it should be OK yes

**Comment by kerner1000** [comment]
Which target do I specify for Mac Intel x86?

**Comment by karianna** [comment]
Maybe try x86_64-unknown-macos or x86_64-unknown-darwin
