### ISSUE TITLE
Adjust release tool to show yellow status when releaseCheck.sh shows error condition

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#3064]
[releaseCheck.sh](https://github.com/adoptium/github-release-scripts/blob/master/sbin/releaseCheck.sh) is executed in the [refactor_openjdk_release_tool](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool) job. At the moment if it fails the checks it's only visible when looking in the console log. We should modify the execution of the job so that it can return a warning status back to the publish job so it will show as a yellow status if the checks fail.

**Comment by jiekang** [comment]
RFE: Clearly state the success or failure in the console log for the entire check in a single string
