### ISSUE TITLE
jdk-11.0.16.1+1 missing `_adopt` tag so cannot be built

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#3067]
See https://github.com/adoptium/jdk11u/tags - the new tag for `jdk-11.0.16.1+1` is mirrored but there is no corresponding `jdk-11.0.16.1+1_adopt` available. The [mirror job](https://ci.adoptopenjdk.net/job/git-mirrors/job/adoptium/job/git-skara-jdk11u) is not showing any failures.

**Comment by zdtsw** [comment]
because tag `jdk-11.0.16.1+1` or `jdk-11.0.16.1-ga` not belong to branch "master" ?

**Comment by andrew-m-leonard** [comment]
Yes @zdtsw jdk-11.0.16.1+1 is not in "master" branch, it is currently a "jdk11.0.16.1" branch.
At some point presumably it might get merged into master, that may cause a problem then, as jdk-11.0.17 builds are now the head.

**Comment by andrew-m-leonard** [comment]
I am guessing upstream might build off of the jdk11.0.16.1 branch , @jerboaa do you you what the intention is?

**Comment by jerboaa** [comment]
@andrew-m-leonard Yes, only on the `jdk11.0.16.1` branch for now. Master was at `11.0.17-dev` at the time of the respin decision so that was the path chosen.

**Comment by gdams** [comment]
closing as we have a workaround

**Comment by sxa** [comment]
Suggest leaving this open until we have the process documented for the future, as there is no information in this issue as to the fix at present.

**Comment by andrew-m-leonard** [comment]
You will need "push" access to the adoptium mirror github repo

1. git clone git@github.com:adoptium/jdk17u.git
2. cd jdk17u
3. git remote add skara git@github.com:openjdk/jdk17u.git
4. git fetch --tags skara
5. git checkout -b jdk17.0.4.1 skara/jdk17.0.4.1
6. git push --tags origin jdk17.0.4.1
7. git fetch --tags origin
8. git checkout -b release_jdk17.0.4.1 origin/jdk17.0.4.1
9. Copy https://github.com/adoptium/jdk17u/blob/release/README.JAVASE .
10. git add README.JAVASE
11. git commit -s -m"Add README.JAVASE"
12. git tag -a "jdk-17.0.4.1+1_adopt" -m "Merged jdk-17.0.4.1+1 into release"
13. git push --tags origin release_jdk17.0.4.1
14. Verify remote repo looks good: https://github.com/adoptium/jdk17u/tags
