### ISSUE TITLE
jdk.compiler.jmod ct.sym non-deterministic on s390xLinux

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3075]
jdk-17 s390xLinux jdk.compiler.jmod differs by ct.sym

Needs investigating:
1. Is same on jdk-19 ?
2. Is it consiostently different?
3.

**Comment by sxa** [comment]
Couple of quick notes - the differences I saw (which resulted in Andrew raising this issue) were between running on two RHEL7 machines. The compiler was GCC 10.3 on both, and the boot JDK was 17.0.4 on both. The shared class cache was also different but that is expected. The following tarballs contain the `jdk.compiler.jmod`, `ct.sym`, `metadata` directory and build log from each of the two builds which show the differences:

[79.tar.gz](https://github.com/adoptium/temurin-build/files/9383846/79.tar.gz)
[77.tar.gz](https://github.com/adoptium/temurin-build/files/9383849/77.tar.gz)

**Comment by sxa** [comment]
`ct.sym` is sensitive to the time zone on the machine which has an hour difference between the two systems. That likely explains the difference.

**Comment by sxa** [comment]
Files that are different based on TZ differences:
```
[sxa@9757757beb16 build-farm]$ diff -r jdk-20+13.4 jdk-20+13
Binary files jdk-20+13.4/jmods/java.base.jmod and jdk-20+13/jmods/java.base.jmod differ
Binary files jdk-20+13.4/jmods/jdk.compiler.jmod and jdk-20+13/jmods/jdk.compiler.jmod differ
diff -r jdk-20+13.4/lib/classlist jdk-20+13/lib/classlist
1206a1207
> sun/util/calendar/ZoneInfoFile$Checksum
Binary files jdk-20+13.4/lib/ct.sym and jdk-20+13/lib/ct.sym differ
Binary files jdk-20+13.4/lib/modules and jdk-20+13/lib/modules differ
Binary files jdk-20+13.4/lib/server/classes.jsa and jdk-20+13/lib/server/classes.jsa differ
Binary files jdk-20+13.4/lib/server/classes_nocoops.jsa and jdk-20+13/lib/server/classes_nocoops.jsa differ
[sxa@9757757beb16 build-farm]$ 
```
