### ISSUE TITLE
jdk-11.0.16.1+1 not available for macOS x64

### ISSUE THREAD

**Issue by jochenberger** [adoptium/temurin-build#3078]
Hi,

there is no jdk-11.0.16.1+1 build available for macOS x64. Is this architecture discontinued or has a build failed?
Is this the relevant pipeline? https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-temurin/

**Comment by sxa** [comment]
As per [the status document](https://github.com/adoptium/adoptium/issues/153) it is still undergoing some final TCK testing and will be available as soon as that is complete - I can assure you it's being actively progressed though :-)
