### ISSUE TITLE
Update release document with various additions

### ISSUE THREAD

**Issue by smlambert** [adoptium/temurin-build#3084]
We should add:
- an example of a code freeze statement shared in release channel to announce that the build repos will be frozen for any changes over and above 
- for pre-release pipelines (the weekend before), launch them with the 'regen test pipelines' parameter = true
- add a note to use the latest aqa-tests release branch and check the values in the aqa-tests/testenv/testenv.properties file in the aqa-tests release branch before launching pipelines

**Comment by smlambert** [comment]
Example freeze announcement (that gets posted to build and release channels):

--- 

It's the Friday before a release week so we will lock down the repositories required for releasing, these are: [temurin-build](https://github.com/adoptium/temurin-build/pulls), [ci-jenkins-pipelines](https://github.com/adoptium/ci-jenkins-pipelines/pulls), [github-release-scripts](https://github.com/adoptium/github-release-scripts/pulls), [containers](https://github.com/adoptium/containers/pulls), [installer](https://github.com/adoptium/installer/pulls).  The freeze applies to any changes over and above those identified in the [release checklist](https://github.com/adoptium/adoptium/blob/main/.github/ISSUE_TEMPLATE/release-checklist.md).  If you need to circumvent the freeze, the process is:
- Add a comment saying "Approval to merge during the lockdown cycle please" and post in the appropriate slack channel for awareness. This can be done before the PR is finalised
- Add a note into this channel saying you are requesting the approval with a link to the comment in the first bullet point
- The comment should have approval from a build approver and a TSC member to indicate that they agree it is critical that it goes in
- The PR can be merged after 2 hours of the post going into the build channel (to give people time to object) ... This delay may be skipped in the case where the delay will result in something breaking within that time.

If you have any you are currently working on that you think will need to get in, please also mention it as a reply to this post so we have awareness.

**Comment by sakshi1215** [comment]
@smlambert Can you please assign this issue to me? Do I need to update https://github.com/adoptium/temurin-build/blob/master/RELEASING.md with the templates or do we have a directory where we are storing such templates?

**Comment by smlambert** [comment]
I have updated the description to not use the word template.  There are no templates to update.  Just need to update the RELEASING.md

**Comment by smlambert** [comment]
Moving to December plan, unassign and need to check what if any updates already went in that satisfy this issue.
