### ISSUE TITLE
Release early access version of Java 8 based on `jdk8u352-b05`

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#3089]
Temurin should build and test a version of JDK8 based on `jdk8u352-b05` which includes a fix for an undefined behaviour bug in `java.lang.ref.reference` (See https://access.redhat.com/articles/6964484). This is a change which can potentially break customers' applications and would benefit from more wide scrutiny and testing before the next version is formally releases. This will be "Maintenance Update 4" for JDK8 as per https://jcp.org/en/jsr/detail?id=337

This should be a beta / early-access deliverable built with options such as `--with-milestone=beta --with-user-release-suffix=ea --with-build-number=b05` and a suitable `aqaReference`

The [openjdk8-pipeline](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline) should be initiated as a nightly build (to avoid it having `--with-milestone=fcs` and therefore not shown as a `beta`) with an `scmReference` of `jdk8u352-b05_adopt` and  `overridePublishName` set to `jdk8u352-b05_ea`

This should allow us to release with a github name of `jdk8u352-b05_ea` and the build will contain the following output from `java -version`:
```
openjdk version "1.8.0_352-beta"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_352-beta-ea-b05)
OpenJDK 64-Bit Server VM (Temurin)(build 25.352-b05, mixed mode)
```

**Comment by sxa** [comment]
@smlambert Can you prep a suitable aqaReference for this please?

**Comment by smlambert** [comment]
@sophia-guo has prepped 0.9.4.2-release branch of aqa-tests which can be used as the aqaReference for this EA build. (thanks Sophia!).

**Comment by sxa** [comment]
Pipelines in progress:
- https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2258/ (Most platforms)
- https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2259/ (Solaris and AIX)

**Comment by sophia-guo** [comment]
Aqa-tests triage issue https://github.com/adoptium/aqa-tests/issues/3947

**Comment by sxa** [comment]
arm32 still awaiting a fix for https://github.com/adoptium/temurin-build/issues/3092

**Comment by sxa** [comment]
Linux/arm32 pipeline in progress: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2269/

**Comment by sxa** [comment]
In addition to the platorms released in the earlier comment from the initial set in https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2258/ I have now published Solaris and AIX from https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2259/

**Comment by sxa** [comment]
In terms of marketing @smlambert will be finalising a blog post with easier to digest links to the ea releases, and in the meantime Andrew Haley has tweeted about it which I have retweeted at https://twitter.com/sxaTech/status/1567562561473626114 so this side of it can now be considered complete.
