### ISSUE TITLE
CA Certs smoke test failure

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#3093]
Thank you for reporting a broken build! Please fill in the following details:
- **Jenkins link to the failing log:** https://github.com/adoptium/temurin-build/runs/8160177641?check_suite_focus=true
- **Which platforms (OS+arch) are affected:** Several in the PR checks
- **If you look at the historic logs, does the problem appear to be specific to one machine?** Seen in Github Actions only
- **Link to any upstream project bug report (e.g. [OpenJ9](https://github.com/eclipse-openj9/openj9/issues)/[JBS](https://bugs.openjdk.java.net/browse))** n/a
```

Sep 02, 2022 5:16:38 PM net.adoptium.test.VerifyCACertsTest isCertNrMatch
INFO: cacerts file: /github/home/JDK/jdk-11.0.17+5/lib/security/cacerts
PASSED: javaVersionPrintsVendor
PASSED: vmPropertiesPointToVendor
PASSED: freetypeOnlyBundledOnCertainPlatforms
FAILED: isCertNrMatch
java.lang.AssertionError: Failed to match CA certs number. expected [135] but found [140]
```

**Comment by zdtsw** [comment]
thats strange I think https://github.com/adoptium/temurin-build/blob/master/test/functional/buildAndPackage/src/net/adoptium/test/VerifyCACertsTest.java#L42 has been updated months ago from 135 to 140

**Comment by zdtsw** [comment]
could that be the branch running GH action need rebase from master?

**Comment by zdtsw** [comment]
from https://github.com/adoptium/temurin-build/actions/runs/3015925747 everything looks fine. 
and no failed runs in the last couple of GH actions
