### ISSUE TITLE
Investigate how to make build more secure when download/install tools during build

### ISSUE THREAD

**Issue by zdtsw** [adoptium/temurin-build#3096]
We have `checkFingerprint()` which uses checksum to verify certain tools we download onto build machine (e.g freemarker, alsa)

But we also have code e.g in `build-farm/platform-specific-configurations/*.sh`  directly download jdk from API server.
It is difficult to use checksum to verify these binaries due to nightly builds. 
Might be more places we are using "curl / wget "  to do similar things.

This ticket is to investigate from security perspective how can we make our builds more stable and secured

**Comment by jiekang** [comment]
Just noting for easier reference, the download from API server is here atm:
https://github.com/adoptium/temurin-build/blob/master/build-farm/platform-specific-configurations/linux.sh#L155

**Comment by zdtsw** [comment]
ref: https://blog.adoptium.net/2022/07/gpg-signed-releases/

**Comment by sxa** [comment]
Looks like only alsa is remaining, and that is covered by a checksum to detect tampering, however https://www.alsa-project.org/files/pub/lib/ provides GPG signatures so we should use those (key ID `A6E59C91`, subject to fixing the GPG problems on Windows and [macos](https://github.com/adoptium/infrastructure/issues/3049).

**Comment by sxa** [comment]
Also has been done in https://github.com/adoptium/temurin-build/pull/3351 and removed (since it's not used) on AIX+Solaris at https://github.com/adoptium/temurin-build/pull/3358.
Closing.
