### ISSUE TITLE
Be able to build with a tag/SHA1 for temurin-build repo, rather than use "master" for branch as default

### ISSUE THREAD

**Issue by zdtsw** [adoptium/temurin-build#3103]
To be able to have reproducible build, we need to have fixed git tag on each repo, including ci-jenkins-pipeline, temurin-build and each jdk source repo.

https://github.com/adoptium/temurin-build/issues/3091 has covered the jdk source repo
this issue is for the temurin-build part.
`   "build_branch": `should be set to a tag

**Comment by zdtsw** [comment]
from what the code we have now, this should be supported already. but we need to verify if it does work.

purely tested git checkout plugin, which works with 
`checkout([$class: 'GitSCM',
                        branches: [ [ name: 'a37292a3408b32fd248c1410a02426635652440c' ] ],
                        userRemoteConfigs: [ [ url: "https://github.com/adoptium/temurin-build.git" ] ]
                    ])`

or 
`
checkout([$class: 'GitSCM',
                        branches: [ [ name: 'mastser' ] ],
                        userRemoteConfigs: [ [ url: "https://github.com/adoptium/temurin-build.git" ] ]
                    ])
`
or
`
checkout([$class: 'GitSCM',
                        branches: [ [ name: '3.0.0' ] ],
                        userRemoteConfigs: [ [ url: "https://github.com/adoptium/temurin-build.git" ] ]
                    ])
`
so, branch name, git tag or even SHA1 all 3 cases are fine

**Comment by zdtsw** [comment]
from the code, since we set `    "USE_ADOPT_SHELL_SCRIPTS": true,` so the really important section is `ADOPT_DEFAULTS_JSON` not  `DEFAULTS_JSON`
and actually whats in the jobs parameter's DEFAULTS_JSON does not matter, because `            repoHandler.setUserDefaultsJson(context, DEFAULTS_JSON['defaultsUrl'])` reads out other parameters from raw.githubsourceontent.com 

so in reality, we do not even need other content except defaultsUrl in the DEFAULT_JSON, 
and can remove "defaultsUrl": "https://raw.githubusercontent.com/adoptium/ci-jenkins-pipelines/master/pipelines/defaults.json", from ADOPT_DEFAULT_JSON
then update
```
"build_branch": "master",
"pipeline_branch": "master",
``` in ADOPT_DEFAULT_JSON to tag or SHA should be enough

**Comment by zdtsw** [comment]
FYI issue @andrew-m-leonard

**Comment by andrew-m-leonard** [comment]
The current limitation when UseAdoptScripts = True, is that the script repos are hard coded in the RepoHandler:
https://github.com/adoptium/jenkins-helper/blob/69c50f5d31ab75c0ed5582e698838ca54cce9407/src/common/RepoHandler.groovy#L24
So checkoutAdoptPipelines() and checkoutAdoptBuild() will always return the master scripts.

The use "User" scripts, (ie.UseAdoptScripts = False) is intended for custom users of the Adopt repros to customize themselves, eg.IBM Semeru build scripts.

We probably need to update the architecture slightly around the UseAdoptScripts logic.

**Comment by andrew-m-leonard** [comment]
Created the VS2019 layout using the following:
```
vs_community.exe --layout VSLayout2019 --add Microsoft.VisualStudio.Workload.NativeDesktop;includeRecommended;includeOptional --add Microsoft.VisualStudio.Component.VC.Tools.ARM64 --add Microsoft.VisualStudio.Component.VC.ATL.ARM64 --add Microsoft.VisualStudio.Component.VC.MFC.ARM64
```

**Comment by zdtsw** [comment]
Can we treat our "tag" build as the `USE_ADOPT_SHELL_SCRIPTS=false` case?
e.g nightly we have "USE_ADOPT_SHELL_SCRIPTS=true" as-is
when release CPU, set "USE_ADOPT_SHELL_SCRIPTS=false" 


Think the names are  confusing:
`DEFAULTS_JSON` is actually for customized config e.g IBM Semeru
`ADOPT_DEFAULTS_JSON` is for adoptium nightly + weekly + release at the moment

**Comment by zdtsw** [comment]
```
https://raw.githubusercontent.com/adoptium/ci-jenkins-pipelines/master/pipelines/gradlew
https://raw.githubusercontent.com/adoptium/ci-jenkins-pipelines/9425e73/pipelines/gradlew
https://raw.githubusercontent.com/adoptium/ci-jenkins-pipelines/april-psu/pipelines/gradlew

```
have the same content , so we can replace master in the `defaultsUrl` with SHA or tag name

**Comment by zdtsw** [comment]
test on https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-x64-temurin/243/console
with parameters: 
![Screenshot from 2022-09-28 10-45-07](https://user-images.githubusercontent.com/915053/192733369-4b6b2dc0-6599-4f99-8429-887301b20b10.png)



need set` --openjdk-build-repo-branch  ` to SHA1 than default "master" coded in temurin-build.
remove  "`PLATFORM_CONFIG_LOCATION`": which is not in use but cause confusion
need to set `USER_REMOTE_CONFIGS-> branch` with SHA1 which is used by helper in func getUserRemoteConfigs to checkout ci-jenkins-pipeline
need to update `DEFAULTS_JSON-> repository` build_branch to temuin-build SHA1 and pipeline_branch to ci-jenkins-pipeline SHA1
need to update   ` DEFAULTS_JSON->defaultsUrl`

**Comment by andrew-m-leonard** [comment]
@zdtsw ^ looks reasonable I think, job looks like it's built with correct repo sha's

**Comment by zdtsw** [comment]
the part I still cannot figure out is how to set the openjdk-jenkins-helper version.
seems everywhere it is hardcoded to use ·@master branch.

**Comment by andrew-m-leonard** [comment]
> the part I still cannot figure out is how to set the openjdk-jenkins-helper version. seems everywhere it is hardcoded to use ·@master branch.

@zdtsw yeah, we'd have to add a new property for that

**Comment by zdtsw** [comment]
to test from openjdk20-pipeline with a small set of targets
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk20-pipeline/60/console

`additionalBuildArgs `use ` --openjdk-build-repo-branch ${temurin-build-sha1}`
uncheck `useAdoptBashScripts`
update ```
defaultsJson``` 's
```
   "defaultsUrl": 
  "repository": {...}
```

this does pass down the --openjdk-build-repo-branch to makejdk-any-platform.sh to the downstream job, but not the other values.

I think the reason is, 
`                            // Triggering downstream job ${downstreamJobName}
                            def downstreamJob = context.build job: downstreamJobName, propagate: false, parameters: config.toBuildParams()`
only does pass down 
```
List<?> toBuildParams() {
        List<?> buildParams = []

        buildParams.add(['$class': 'LabelParameterValue', name: 'NODE_LABEL', label: NODE_LABEL])
        buildParams.add(['$class': 'TextParameterValue', name: 'BUILD_CONFIGURATION', value: toJson()])

        return buildParams
    }
```
so the `defaultsJson` we update in openjdk-pipeline is not part of the `BUILD_CONFIGURATION`. Thus, the downstream job e.g `jdk-alpine-linux-x64-temurin `still use the default value of defaultsJson (when the job was created)

**Comment by zdtsw** [comment]
if ^ is correct, then we are not able (as what we have now in code base) to set tag/SHA1 from a openjdk-pipeline 
what we can do is only to set tag/SHA1 directly in the downstream job per each build.

**Comment by andrew-m-leonard** [comment]
> it feels strange, in https://github.com/adoptium/jenkins-helper/blame/master/src/common/RepoHandler.groovy#L60 sets into a variable "USER_DEFAULTS_JSON" but in ci-jenkins-pipeline script, e.g https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L1224 it only uses "DEFAULT_JSON" seems this setUserDefauiltsJson does not take effects ?

Yeah, agree, I think ReopHandler.setUserDefauiltsJson() is supposed to be retrieved by getUserDefauiltsJson(), but that's not used anywhere other tan the unittest.

**Comment by sxa** [comment]
> if ^ is correct, then we are not able (as what we have now in code base) to set tag/SHA1 from a openjdk-pipeline

As mentioned elsewhere (and duplicating here for record) I do feel that we're missing important functionality by not allowing a SHA to be put in (for temurin-build specifically sine that is the critical stuff that can affect the builds, but applicable to the other repos). With a tag you're limited to things that have been tagged. If I want to rebuild something from two weeks ago I first have to tag it (and have permission to do so) and probably delete that tag afterwards which is all a bit messy. If we had the ability to do a SHA then the tagging would arguably just be a "nice to have" on top as a human readable record e.g. for release builds. (albeit adding an extra step into the process to create it) but I feel the real difference here would be if we were able to make a SHA work as input to our automation.

**Comment by zdtsw** [comment]
> > if ^ is correct, then we are not able (as what we have now in code base) to set tag/SHA1 from a openjdk-pipeline
> 
> As mentioned elsewhere (and duplicating here for record) I do feel that we're missing important functionality by not allowing a SHA to be put in (for temurin-build specifically sine that is the critical stuff that can affect the builds, but applicable to the other repos). With a tag you're limited to things that have been tagged. If I want to rebuild something from two weeks ago I first have to tag it (and have permission to do so) and probably delete that tag afterwards which is all a bit messy. If we had the ability to do a SHA then the tagging would arguably just be a "nice to have" on top as a human readable record e.g. for release builds. (albeit adding an extra step into the process to create it) but I feel the real difference here would be if we were able to make a SHA work as input to our automation.

Maybe the title for this issue is not accurate. 
the goal for this ticket is to make it configurable for both tag and SHA1. From pure git perspective, there is no difference between a tag or a SHA1 both treated as gitref. 
The only limitation lives in the implementation of git plugin:
- checkout works fine with 3 types: branch tag SHA1
- library only works with 2 types: branch and tag

so, we will be able to pass in tag and SHA1 to temurin-build repo and ci-jenkins-pipeline if we finish this issue.

**Comment by andrew-m-leonard** [comment]
I think the "library" changes very infrequently, so I think being able to specifyt a SHA for BUILD_REF, and a tag for LIBRARY_REF, should be sufficient for what @sxa refers to

**Comment by zdtsw** [comment]
> I think the "library" changes very infrequently, so I think being able to specifyt a SHA for BUILD_REF, and a tag for LIBRARY_REF, should be sufficient for what @sxa refers to

Yes I agree. 
For the test I am doing now, I only use SHA for temurin-build and ci-jenkins-pipeline, As for helper repo, I use a branch.
In my PR, it is stated the former two support all there types, but the later one has the limitation.

**Comment by zdtsw** [comment]
Testing https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk20-pipeline/88/console after [code merged](https://github.com/adoptium/ci-jenkins-pipelines/pull/423). 
so far looks fine
-  a small set of platforms
- on jdk20
- change parameters in openjdk20-pipeline 
- keep using releaseType as Nightly for small set of AQA tests
- set SHA for buildReference (which points to the current master's commit)
- set SHA for ciReference (which points to the current mastser's commit)
- set "master" for helperReference ( can have another round of test after making a tag on jenkins-helper repo)
- unticked "userAdopBashScripts"

**Comment by zdtsw** [comment]
created tag [v0.0.1](https://github.com/adoptium/jenkins-helper/releases/tag/v0.0.1) in helper
using it for testing. 
Can make official tag when all tests are done

**Comment by zdtsw** [comment]
TEST3:

https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk20-pipeline/90/console

smaller set of AQA (only x64 linux which finish very quick)
no other changes in the parameters

simulate what we should have for the normal nightly builds

**Comment by zdtsw** [comment]
i will have this issue closed, since we have tested it with the release dry-run and fixed most of the issue.
can create new issue later if anything is not working properly
