### ISSUE TITLE
cacerts count failing

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#3108]
Thank you for reporting a broken build! Please fill in the following details:
- **Jenkins link to the failing log:** https://github.com/adoptium/temurin-build/actions/runs/3180771154/jobs/5184738980
- **Which platforms (OS+arch) are affected:** Most of them
- **If you look at the historic logs, does the problem appear to be specific to one machine?** No - running in github actions
- **Link to any upstream project bug report (e.g. [OpenJ9](https://github.com/eclipse-openj9/openj9/issues)/[JBS](https://bugs.openjdk.java.net/browse))** n/a
```
FAILED: isCertNrMatch
java.lang.AssertionError: Failed to match CA certs number. expected [135] but found [140]
```

**Comment by tellison** [comment]
@sxa I assume this can be closed now?

**Comment by tellison** [comment]
@sxa ping?

**Comment by sxa** [comment]
Looks like it was resolved in https://github.com/adoptium/temurin-build/commit/9f94df3904d79b4153d16301c58a974bfe5db059 so yes this can be closed.
