### ISSUE TITLE
Typos: buildbreak.md needs some typos correcting

### ISSUE THREAD

**Issue by adamfarley** [adoptium/temurin-build#3121]
The following issues have been observed within .github/ISSUE_TEMPLATE/buildbreak.md and need fixing:
- In the "about" field, jenkins should have a capital J.
- "Which platforms (OS+arch) are affected" should have a question mark before the full colon.
- "If you look at the ... specific to one machine?" needs a full colon after the speech mark, but before the asterisks.
- "Link to any upstream project..." also needs a full colon at the end, right before the asterisks.

**Comment by Adeosunomoshalewa** [comment]
I’d like to work on this issue
