### ISSUE TITLE
Typos: feature_request.md needs some typos correcting

### ISSUE THREAD

**Issue by adamfarley** [adoptium/temurin-build#3122]
The following issues have been observed within .github/ISSUE_TEMPLATE/feature_request.md and need fixing:
- "(e.g. Adding a new OpenJDK distribution)" should have a space after it.
- "are made over at the [adoptium]" should be "are made over at the [adoptium repository]".
- "Otherwise, please describe..." Should all be on a single line.

**Comment by yukiyuli** [comment]
Hello @adamfarley , could you assign me to do it?

**Comment by zdtsw** [comment]
ah, ok
you need to make a PR from your repo and branch to original's master.
to merge to your repo's master, wont make it landed to adoptium/temurin-build
