### ISSUE TITLE
Typos: documentation.md needs some typos correcting

### ISSUE THREAD

**Issue by adamfarley** [adoptium/temurin-build#3123]
More "minor grammatical changes" than "typos", but these changes will still makes things clearer. The file is .github/ISSUE_TEMPLATE/buildbreak.md, and the requested changes are:
- The "about" field seems clearer as: "Request for updates to the Temurin build documentation"
- "documented" should have a comma after it.
- "like to see in the documentation" should have a full colon after the last word, but before the asterisks. Or maybe a full stop. Up to you. :)

**Comment by yukiyuli** [comment]
Hello @adamfarley , I want to fix it.

**Comment by zdtsw** [comment]
same as for this one, if you do not want to continue with this issue, I can unassign it from you @yukiyuli

**Comment by yukiyuli** [comment]
I think that I have already submitted the pull request. Please review https://github.com/adoptium/temurin-build/pull/3125. If I need do anything else, feel free let me know.
