### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by zdtsw** [adoptium/temurin-build#3124]
Typo in https://github.com/adoptium/temurin-build/blob/master/RELEASING.md
"only keep termurin variants" => "only keep temurin variatns"

**Comment by yukiyuli** [comment]
Hello @zdtsw ，I want to fix it. Thanks.

**Comment by Emidowojo** [comment]
Hi @zdtsw I'd like to fix this

**Comment by zdtsw** [comment]
> Hi @zdtsw I'd like to fix this

@yukiyuli asked first, so I assign this issue to her this time
