### ISSUE TITLE
Install freetype-2.12.1 at https://ci.adoptopenjdk.net/userContent/freetype

### ISSUE THREAD

**Issue by pshipton** [adoptium/temurin-build#3127]
jdk8 builds get freetype from https://ci.adoptopenjdk.net/userContent/freetype. OpenJ9 builds would like to use freetype 2.12.1 but it's not available. Can we pls get it added, or if there is something I can do to help get it added let me know.

https://github.com/adoptium/temurin-build/blob/master/sbin/prepareWorkspace.sh#L455

**Comment by gdams** [comment]
For a while now I've been considering swapping our FreeType source to the official GitHub org (https://github.com/freetype/freetype), this is actually how it's done upstream (https://github.com/openjdk/jdk8u/blob/master/.github/workflows/submit.yml#L808-L813). Maybe we could change the scipts to do this?

**Comment by pshipton** [comment]
OpenJ9 has started on a different path. We've backported the changes from jdk11 to get the freetype source from jdk8 repo.
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/631
@keithc fyi. I suppose getting it directly from github is another way to go, with just the tag and version in the license needing to be updated any time there is a version change.

**Comment by gdams** [comment]
> OpenJ9 has started on a different path. We've backported the changes from jdk11 to get the freetype source from jdk8 repo.
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/631

That's even nicer, especially if you plan on backporting it upstream?

**Comment by gdams** [comment]
Closing for now as J9 has included the source
