### ISSUE TITLE
UGS doesn't work under MX linux 21.2.1

### ISSUE THREAD

**Issue by Divetheworld** [adoptium/temurin-build#3131]
**What are you trying to do?**
trying to run the program on the system
**Expected behaviour:**

**Observed behaviour:**
the program starts to load but close immediately. however under ubuntu works fine
**Any other comments:**
[hs_err_pid3896.log](https://github.com/adoptium/temurin-build/files/9851897/hs_err_pid3896.log)

**Comment by karianna** [comment]
Java 13 is no longer supported.  Please move to 17 LTS or 19 (latest)
