### ISSUE TITLE
update releasing.md

### ISSUE THREAD

**Issue by zdtsw** [adoptium/temurin-build#3132]
Update https://github.com/adoptium/temurin-build/blob/master/RELEASING.md to reflect the latest job config and release steps
Question: should keep special part for openj9  or just clean it up?

**Comment by gdams** [comment]
> Question: should keep special part for openj9 or just clean it up?

My preference would be to remove it as it's not relevant to the work we do

**Comment by karianna** [comment]
@AdamBrousseau to check if they use it for Semeru

**Comment by AdamBrousseau** [comment]
Thanks for the at. We have forked our own release checklist so please go ahead and cleanup as you see fit. We do check back from time to time to see if Adopt has changed release process that would also be beneficial to us. Thanks.
