### ISSUE TITLE
Smoketest is failing with cacert number mismatch

### ISSUE THREAD

**Issue by zdtsw** [adoptium/temurin-build#3212]
seems after https://github.com/adoptium/temurin-build/pull/3204/ we start to have failing smoketest (see both in GH action check and build pipeline)

`java.lang.AssertionError: Failed to match CA certs number. expected [138] but found [139]`

**Comment by zdtsw** [comment]
For records:

in #3204, we did see 4 certs were removed from certdata.txt
but one of them "SwissSign Platinum CA -G2" was previous skipped, thats why only 3 certs were really removed (compare with 142) new expected number should be 139.

**Comment by smlambert** [comment]
Re-open as dry run build pipeline https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-linux-x64-temurin_SmokeTests/3 still has all smoke tests failing with 

```
java.lang.AssertionError: Failed to match CA certs number. expected [142] but found [139]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at net.adoptium.test.VerifyCACertsTest.isCertNrMatch(VerifyCACertsTest.java:78)
...
```

Is it an issue with the pipeline launch params?

**Comment by zdtsw** [comment]
> Re-open as dry run build pipeline https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-linux-x64-temurin_SmokeTests/3 still has all smoke tests failing with
> 
> ```
> java.lang.AssertionError: Failed to match CA certs number. expected [142] but found [139]
> at org.testng.Assert.fail(Assert.java:96)
> at org.testng.Assert.failNotEquals(Assert.java:776)
> at org.testng.Assert.assertEqualsImpl(Assert.java:137)
> at org.testng.Assert.assertEquals(Assert.java:118)
> at org.testng.Assert.assertEquals(Assert.java:652)
> at net.adoptium.test.VerifyCACertsTest.isCertNrMatch(VerifyCACertsTest.java:78)
> ...
> ```
> 
> Is it an issue with the pipeline launch params?

looks like smoke test did not get regnerated with the new dry-run tag [v2023.01.03](https://github.com/adoptium/temurin-build/releases/tag/v2023.01.03) but was still set to the old `v2023.01.beforereleasetest`

**Comment by zdtsw** [comment]
this is only happening for the release pipeline.
in the normal (nightly, weekly and evaluation) case, it always uses "master" so has no difference.
But for the release pipeline, everytime regenerate with a different tag name, openjdk-pipeline, downstream jobs are all regenerated but smoke test only creates by the first time, does not get re-generate with new tag

**Comment by zdtsw** [comment]
according to this https://github.com/adoptium/ci-jenkins-pipelines/blame/master/pipelines/build/common/openjdk_build_pipeline.groovy#L292
we either can delete all these release smoketest, or disable all of them, then it will get re-generated.

**Comment by smlambert** [comment]
I will proceed to delete all affected Smoketest jobs.

**Comment by zdtsw** [comment]
will close this issue which has resolved the failing smoketest issue.

create https://github.com/adoptium/ci-jenkins-pipelines/issues/585 to tackle smoektest re-generation

**Comment by sophia-guo** [comment]
SmokeTest jobs are generated with either useAdoptShellScipts or default_json https://github.com/adoptium/ci-jenkins-pipelines/blame/master/pipelines/build/common/openjdk_build_pipeline.groovy#L150-L157 depends on the parameter buildConfig.USE_ADOPT_SHELL_SCRIPTS. Before the upstream was tagged smoketests was supposed to run the master branch. As this is not the case any more  we can simply update the smoketest build by passing in the parameter vendorTestBranches with correct  "build_branch": "v****.**", https://github.com/adoptium/ci-jenkins-pipelines/blame/master/pipelines/build/common/openjdk_build_pipeline.groovy#L303-L313.

Also might need to think about if the smoke tests should use the testenv.properties for release as other tests if yes, we might need add smoketests repo and branch info to testenv.properties. 

I can't see the failed job any more (deleted), but I believe either deleted or newly created one are still using the temurin-build master branch.

**Comment by smlambert** [comment]
For the record, we do not need to use testenv.properties for smoketests.  Smoke tests are part of temurin-build, not part of the AQAvit test suite, so are exempt (just as we do not need to use testenv.properties for jck, as the compliance tests are not part of AQAvit).  It is sufficient and correct to pin smoke tests to the temurin-build branch/tag/SHA that is in use.

**Comment by sophia-guo** [comment]
Another thing needs to confirm is smoketest jobs are using aqa-tests, tkg master branch, should we keep it as is? @smlambert

**Comment by smlambert** [comment]
Using master branches for aqa-tests and TKG is fine (and while we do not code freeze, we attempt to not break master branches, so they should always be functioning or 1 revert step away from functioning)

**Comment by sophia-guo** [comment]
Close this as https://github.com/adoptium/ci-jenkins-pipelines/pull/587 is done.
