### ISSUE TITLE
jdk-17 builds will not be reproducible if built with pre jdk-17.0.4 BootJDK

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3232]
Reproducible jdk-17 builds depends on jdk-17.0.4 bootjdk otherwise jrt-fs.jar will not be identical.

We need to ensure boot jdk selection uses jdk-17.0.4

**Comment by sxa** [comment]
@andrew-m-leonard Has this been handled? I thought we had a PR in place to ensure we were building JDK17 with a suitable boot JDK now.

**Comment by andrew-m-leonard** [comment]
Yeah, this is implicitly fixed since we download the latest GA for jdk-17, hence get jdk-17.0.7 now.
@sxa
