### ISSUE TITLE
Add Reproducible Build Comparisons to Jenkins Pipelines 

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3245]
Add the ability in the ci-jenkins-pipelines to support dual build with integrated reproducible build comparison.
Only supported for certain versions: jdk-17+

The following existing toolset: https://github.com/adoptium/ci-jenkins-pipelines/tree/master/tools/reproduce_comparison
provides some tools, these need moving to temurin-build repo.
These are currently being updated/extended with some in-progress work here: https://github.com/andrew-m-leonard/openjdk-build/tree/repro_validate/tooling
note renaming of compareLinux.sh to [linux_repro_build_compare.sh](https://github.com/andrew-m-leonard/openjdk-build/blob/repro_validate/tooling/linux_repro_build_compare.sh)

**Suggested solution:**
- Utilise aqa-test framework to create a new "reproducible-test" job
- test job performs a second build by invoking the standard build job as a sub-job, but passing build_args of --build-reproducible-date "ISO8601 date", where the date is the same date used by the original build
- then compare the two builds, eg: https://github.com/andrew-m-leonard/openjdk-build/blob/4871528098f006f9680d3f3579351fd1ff823a37/tooling/linux_repro_build_compare.sh#L105
- produce a test result which includes the reproducible percentage, eg see: https://github.com/andrew-m-leonard/openjdk-build/blob/4871528098f006f9680d3f3579351fd1ff823a37/tooling/windows_repro_compare.sh#L45

**Comment by zdtsw** [comment]
related to https://github.com/adoptium/ci-jenkins-pipelines/issues/397

**Comment by sophia-guo** [comment]
What is the expected results? Looking at the console output  https://ci.adoptium.net/job/jdk17u-linux-x64-temurin_reproduce_compare/21/console, what issues or other steps should be taken care of ? @andrew-m-leonard

**Comment by andrew-m-leonard** [comment]
@sophia-guo So the scripts need a JDK in the PATH so they can run "jimage" and "jmod". I suggest simply unpacking "original" into a 2nd folder that you then use as a JDK in PATH, so you have 3 folders:
1. originalJdkHome
2. originalHome
3. reproducedHome
and:
export PATH=<path to originalJdkHome>/bin:$PATH

The linux_repro_compare script takes the java home folder as the path, so I think you need to call it as:
./linux_repro_compare.sh temurin /home/jenkins/workspace/jdk17u-linux-x64-temurin_reproduce_compare/original/<jdkTag> temurin /home/jenkins/workspace/jdk17u-linux-x64-temurin_reproduce_compare/reproduced/<jdk-tag>
So you need to query the Jdk home folder.

**Comment by sophia-guo** [comment]
Linux enabled. https://ci.adoptium.net/job/jdk17u-linux-x64-temurin_reproduce_compare/
Platform priority order for comparison: Linux x64, Windows x64, Linux aarch64, Linux ppc64, Linux s390x, Mac x64, Mac aarch64

**Comment by sophia-guo** [comment]
Aarch 64 linux https://github.com/adoptium/ci-jenkins-pipelines/pull/742

**Comment by sophia-guo** [comment]
[Linux ppc64, Linux s390x](https://github.com/adoptium/ci-jenkins-pipelines/issues/758)

**Comment by sophia-guo** [comment]
Window issue [remove signature error message with jdk17 windows-x64](https://github.com/adoptium/temurin-build/issues/3436)
