### ISSUE TITLE
Check sum for JDK 8.362 and 11.0.18 ist not correct 

### ISSUE THREAD

**Issue by AstridS** [adoptium/temurin-build#3250]
Hello,

**What are you trying to do?**
I downloaded JDK 8u362-b09 and 11.0.18 for Windows x64
https://adoptium.net/de/temurin/archive/?version=11
https://adoptium.net/de/temurin/archive/?version=8
I used the link Checksumme, but for both versions, the checksum is not correct.

**Expected behaviour:**
Check sum online is the same as after download.

**Observed behaviour:**
A second try did not help.

**Any other comments:**
Please correct the download or the provided check sum.

Best regards,
Astrid

**Comment by AstridS** [comment]
Hi,
when I use the following links, the check sums are correct:
https://adoptium.net/de/temurin/releases/?version=8
https://adoptium.net/de/temurin/releases/?version=11

So my incident is solved, but you might want to check the links.

Best regards,
Astrid

**Comment by karianna** [comment]
@gdams Could be a website issue?

**Comment by gdams** [comment]
duplicate of https://github.com/adoptium/adoptium.net/issues/769
