### ISSUE TITLE
freemarker download is failing

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#3252]
**What are you trying to do?** Run a build, which invokes https://github.com/adoptium/temurin-build/blame/784af5c903f067fec94195597856b3ef9c70ba5f/sbin/prepareWorkspace.sh#L391 to download https://downloads.apache.org/freemarker/engine/2.3.31/binaries/apache-freemarker-2.3.31-bin.tar.gz

**Expected behaviour:** File is downloaded as it was in builds from the 13th January

**Observed behaviour:** 404 Not found in the next build from the 29th

**Any other comments:** Since this is the first time we have fully disabled the builds during the pipeline and it lasted for two weeks it is not clear when this started occurring.

**Comment by sxa** [comment]
FYI @AdamBrousseau is this affecting you?

**Comment by keithc-ca** [comment]
Freemarker is only needed for UMA builds; OpenJ9 has been using CMake builds for some time: Maybe it's time to stop fetching freemarker?

**Comment by AdamBrousseau** [comment]
We've actually hacked out the freemarker download some time ago on our end. I think probably when it started failing last time. Never followed up on proper solution probably due to lack of priority.
https://github.com/ibmruntimes/temurin-build/commit/5546579e8910f8edf97851405331379bb45c2b6b
https://github.com/ibmruntimes/ci-jenkins-pipelines/pull/28
https://github.com/ibmruntimes/temurin-build/pull/3/

**Comment by sxa** [comment]
@keithc-ca Since I haven't been keeping up with OpenJ9 developments can you clarify something for me: if freemarker is a compile time build dependency why does it make any difference whether it's a CMake or UMA build? Is freemarker always skipped on a CMake build?

**Comment by sxa** [comment]
> Of course, we will need to stop using the configure option --with-freemarker-jar as that expects that the named file exists.

Do you build without that option in the openj9 CI? In which case we should definitely follow that in ours.

**Comment by nitind** [comment]
It's not uncommon for Apache to move all but the current release to archive.apache.org, and FreeMarker is now at v2.3.3**2**.

**Comment by keithc-ca** [comment]
> Do you build without that option in the openj9 CI? In which case we should definitely follow that in ours.

No, most builds don't use that option; (e.g. the [latest jdk11_x86-64_linux build](https://openj9-jenkins.osuosl.org/view/Build_Nightly/job/Build_JDK11_x86-64_linux_Nightly/491/)):
```
20:00:39  + bash configure --with-boot-jdk=/home/jenkins/bootjdks/jdk11 --enable-cuda --with-cuda=/usr/local/cuda-9.0 --with-openssl=fetched --enable-jitserver
```
https://github.com/eclipse-openj9/openj9/pull/16759 will eliminate the other (unnecessary) uses.
