### ISSUE TITLE
Investigate what dependencies make a Linux x64 jdk20 build reproducible 

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3256]
Perform investigative builds to determine the "recipe" for re-producible Linux x64 jdk20 builds.

To evaluate what makes a Linux build reproducible, we'd like to compare the jdk-20 Temurin x64Linux release (or jdk-19.0.2 if jdk-20 not available yet..), with an independently setup x64 Linux VM.

1. Setup or use your local Linux machine/VM, and then use the following comparison script https://github.com/adoptium/ci-jenkins-pipelines/blob/master/tools/reproduce_comparison/compareLinux.sh.
2. Document the differences here...
3.

**Comment by sxa** [comment]
Is this in terms of the minimal things you need on a machine to perform a Temurin reproducible build (captured in https://github.com/adoptium/ci-jenkins-pipelines/pull/599), or which bits are likely to make a difference to the output (e.g. the output from the strace work at #3087)?

**Comment by andrew-m-leonard** [comment]
More the former, but to understand what is required, for example on Windows you must have "VS2019 v.x.y.z", but does not required Windows Server 2012,.....

**Comment by sxa** [comment]
Gotcha. The PR above running explicitly on "CentOS/RHEL6" should be enough to cover this on xLinux.
We should definitely verify on other architectures which need CentOS/RHEL7 as part of this.

**Comment by chandrashritii** [comment]
@andrew-m-leonard I'd love to take this up. Could you please assign this issue to me?

**Comment by andrew-m-leonard** [comment]
We need to add:
   gcc version
   BootJDK
to the current SBOM
