### ISSUE TITLE
Should temurin build versions use --with-version-opt=LTS for LTS versions?

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3270]
Some vendors (in fact i've not found one that doesn't!) use --with-version-opt=LTS which results in version strings being extended with for example "jdk-17.0.6+10-LTS"
See: https://github.com/adoptium/jdk17u/blob/648f3f6a8fe9ea2e00b60710afa44208cfbc2c49/src/java.base/share/classes/java/lang/VersionProps.java.template#L69
```
private static final boolean isLTS =
        "@@VERSION_OPT@@".startsWith("LTS");
```

JEP [322](https://openjdk.org/jeps/322) states:
﻿﻿**If a release is part of a series of releases for which an implementor offers long-term support then the value of $OPT should start with "LTS", e.g., 11.0.2+13-LTS. This will cause "LTS" to be displayed prominently in the output of java --version, etc., more on which below.**

eg.:
**Zulu:**
```
openjdk version "17.0.6" 2023-01-17 LTS
OpenJDK Runtime Environment Zulu17.40+19-CA (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM Zulu17.40+19-CA (build 17.0.6+10-LTS, mixed mode, sharing)
```
**Red Hat:**
```
openjdk version "17.0.6" 2023-01-17 LTS
OpenJDK Runtime Environment (Red_Hat-17.0.6.0+10-1) (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.6.0+10-1) (build 17.0.6+10-LTS, mixed mode, sharing)
```
**Oracle:**
```
java version "17.0.6" 2023-01-17 LTS
Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)
```

**Comment by zdtsw** [comment]
I guess the question is for official releases if Temurin should have '-LTS' appended in the version?

**Comment by karianna** [comment]
Will add to PMC as we know changing version strings can impact subscribers

**Comment by jerboaa** [comment]
https://openjdk.org/jeps/223 introduces API, `Runtime.Version`, for version parsing. Is version output still a concern? If it was, wouldn't the same be a concern for cross-vendor switching?

**Comment by jerboaa** [comment]
There are also jlink plugins which allow switching those:

```
  --vendor-bug-url <vendor-bug-url>
                            Override the vendor bug URL baked into the build.
                            The value of the system property
                            "java.vendor.url.bug" will be <vendor-url-bug>.
  --vendor-version <vendor-version>
                            Override the vendor version string baked into the
                            build,if any. The value of the system property
                            "java.vendor.version" will be <vendor-version>.
  --vendor-vm-bug-url <vendor-vm-bug-url>
                            Override the vendor VM bug URL baked 
                            into the build.  The URL displayed in VM error
```

**Comment by andrew-m-leonard** [comment]
Question came up with regards ensuring the Temurin "metadata" is not affected by the LTS suffix, such that it would affect the API.
May depend on how it is generated.

Needs investigation.

**Comment by andrew-m-leonard** [comment]
@llxia @AdamBrousseau fyi
OpenJ9 does not use --with-version-opt="LTS" for LTS versions either:
```
openjdk version "17.0.6" 2023-01-17
IBM Semeru Runtime Open Edition 17.0.6.0 (build 17.0.6+10)
Eclipse OpenJ9 VM 17.0.6.0 (build openj9-0.36.0, JRE 17 Linux aarch64-64-Bit Compressed References 20230117_370 (JIT enabled, AOT enabled)
OpenJ9   - e68fb241f
OMR      - f491bbf6f
JCL      - 927b34f84c8 based on jdk-17.0.6+10)
```

**Comment by andrew-m-leonard** [comment]
Built Temurin metadata already handles "optional" extra as per JEP223.
API example:
https://api.adoptium.net/v3/version/21%2B32-LTS
```
build | 32
major | 21
minor | 0
openjdk_version | "21+32-LTS"
optional | "LTS"
security | 0
semver | "21.0.0+32.LTS"
```

**Comment by andrew-m-leonard** [comment]
> Just wondering the details of the decision to add this only to 21+ and not for jdk8,11,17?

Purely on the basis of not changing LTS versions that have been out there for some years
