### ISSUE TITLE
Bug: The build healthcheck system is double-counting failures

### ISSUE THREAD

**Issue by adamfarley** [adoptium/temurin-build#3272]
**Summary**

It appears that the system for reporting on the health of overnight builds is somehow counting failures twice.

Example: [https://ci.adoptium.net/job/nightlyBuildAndTestStats_temurin/981//console](https://ci.adoptium.net/job/nightlyBuildAndTestStats_temurin/981//console)

Search for openjdk8-pipeline, see the double entry, and also note that the total failures at the end are "8", despite there being only one set of four failures in the double-printed jdk8 pipeline.

**How it should work**

It should count each failed build only once.

**Next steps**

To look at the code that fetches data from TRSS and figure out why we're receiving two sets of the same data, or why we're duplicating the data we receive.

**Comment by smlambert** [comment]
Likely related to the fact that ci.adoptopenjdk.net got renamed to ci.adoptium.net and we are currently monitoring both in TRSS, so double-counting.  I have not yet deleted the configuration in TRSS that has us monitoring ci.adoptopenjdk.net, as I was testing whether I could just mark the monitoring to "No" but hitting a known bug https://github.com/adoptium/aqa-test-tools/issues/775.  I will remove the ci.adoptopenjdk.net monitoring completely which should fix this issue.

**Comment by adamfarley** [comment]
Thanks Shelley. 🙂

**Comment by smlambert** [comment]
Please keep this open until we confirm its fixed by my changes, I will plan to make those config changes to TRSS on the weekend.

**Comment by adamfarley** [comment]
I double-checked the results, and I'm not seeing the double-counting anymore. Good job Shelley! 😀

**Comment by jobwe** [comment]
adamfarley
