### ISSUE TITLE
update jackson-databind version

### ISSUE THREAD

**Issue by rohangollena** [adoptium/temurin-build#3274]
### we are using the vulnerable version of jackson-databind [here](https://github.com/adoptium/temurin-build/blob/2bac508efe406d485c09af0c518aee9bed6d111b/cyclonedx-lib/build.xml#L25) , the stable versions of jackson-databind is found [here](https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind)

**Comment by sxa** [comment]
Closing as the relevant PR has been merged. Thanks for the report.
