### ISSUE TITLE
Solaris JDK8 builds fail due to "cannot find symbol" SystemMetrics.instance()

### ISSUE THREAD

**Issue by adamfarley** [adoptium/temurin-build#3276]
**What are you trying to do?**

Build JDK8 on Solaris, both x64 and Sparcv9

**Expected behaviour:**

Pass

**Observed behaviour:**

Failure due to:

```
12:19:21  Compiling 9787 files for BUILD_JDK
12:20:01  /export/home/jenkins/sshagent/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-temurin/workspace/build/src/jdk/src/share/classes/jdk/internal/platform/Metrics.java:57: error: cannot find symbol
12:20:01          return SystemMetrics.instance();
12:20:01                 ^
12:20:01    symbol:   variable SystemMetrics
12:20:01    location: interface Metrics
```

[Example failure.](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-temurin/282/console)

**Any other comments:**

[AIX had the same problem](https://github.com/adoptium/temurin-build/issues/3261), but is believed to have been solved in the upstream code base for AIX specifically. Plan A for this issue is to find that solution and port it into the Solaris-specific code.

**Comment by sxa** [comment]
@adamfarley Can this be closed? I believe this has been fully resolved now.

**Comment by adamfarley** [comment]
Yup, all resolved. Thanks. :)
