### ISSUE TITLE
Xerces version 2.7.1 in JDK8

### ISSUE THREAD

**Issue by ashirvadgupta** [adoptium/temurin-build#3294]
Unsure where to raise something? Here are some of the common places:
- If your issue is due to the way OpenJDK is built, then this is the repository to raise it in - Describe your problem below
- If your issue is related to our installers (as opposed to tgz/zip downloads) raise it in [installer](https://github.com/adoptium/installer/)
- If your issue is related to and end-user visible issue with the JDK, or an underlying java bug, please raise it in [adoptium-support](https://github.com/adoptium/adoptium-support/issues)

**Problem description:**
Xerces version 2.7.1 in JDK8

Hi Team, I was just checking xerces version used in jdk8u362 version and i found out that it is 2.7.1.
I got one link where xerces was upgraded to 2.12.1 - https://bugs.openjdk.org/browse/JDK-8260568
but its still showing 2.7.1 for me. Please do check it.
<img width="765" alt="image" src="https://user-images.githubusercontent.com/9796336/226565376-11c8f298-8da7-4e2c-a039-179f16953618.png">

I decompiled rt.jar and found out version is 2.7.1. I think issue number JDK-8260568 is not fixed.
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/9796336/226568639-383de45d-13c1-4001-999c-15eeba597980.png">

**Comment by karianna** [comment]
@ashirvadgupta The Xerces shipped with Java 8 is pinned to that older version for compatibility changes and won't be changed.

**Comment by ashirvadgupta** [comment]
@karianna but this is vulnerable right?

**Comment by karianna** [comment]
It's an internal version that can't be reached from user code.
