### ISSUE TITLE
Populate SBOM with minimal properties to enable reproducible-build

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3314]
The SBOM needs to contain properties that enable a full reproducible re-build.

**Comment by andrew-m-leonard** [comment]
From the previous issue https://github.com/adoptium/temurin-build/issues/3256#issuecomment-1516027059
We concluded we at least need to add
    gcc version
    bootjdk version
This PR needs to update the script around abouts here: https://github.com/adoptium/temurin-build/blob/914459c510d90c27e22ee628f699e39872598f90/sbin/build.sh#L775

**Comment by chandrashritii** [comment]
Got it. I'd like to take this up @andrew-m-leonard Could you please assign this issue to me?

> From the previous issue [#3256 (comment)](https://github.com/adoptium/temurin-build/issues/3256#issuecomment-1516027059) We concluded we at least need to add gcc version bootjdk version This PR needs to update the script around abouts here:
> 
> https://github.com/adoptium/temurin-build/blob/914459c510d90c27e22ee628f699e39872598f90/sbin/build.sh#L775

**Comment by sxa** [comment]
Note that as an absolutely minimum the glibc package version is critical. EVERY different CentOS7 patch level contains a glibc that makes reproducibility incompatible with any other (I tested with the levels included at each CentOS7 patch level on x64)

I suspect most other packages are less sensitive to patches than glibc, but it's always going to be a risk so we should perhaps aim to include the glibc level in the SBOM ASAP and add everything else that comes out of the research as potential dependencies that could cause differences.

**Comment by andrew-m-leonard** [comment]
@chandrashritii So to start with GCC versioning, and additional parts like operating system GLIBC mentioned above. So you'll need to investigate a bit but I'm thinking where the gcc setup occurs here: https://github.com/adoptium/temurin-build/blob/8e18f18fbf427747417b932c78741b0bc8511eed/build-farm/platform-specific-configurations/linux.sh#L315
That we could add some code there to interrogate what the exact version of gcc (gcc --version), and at the same time query the glibc version being used on the build machine, I think "ldd --version".

**Comment by sxa** [comment]
`rpm -q glibc` should be the best way to get the glibc version from any rpm-based LInux distribution. `dpkg -l libc-bin` on Debian/Ubuntu (arm32 and riscv64 are built on Ubuntu, the others are on rpm-based distributions)
