### ISSUE TITLE
Signing: TIMESTAMP server list processing trims 'r' characters

### ISSUE THREAD

**Issue by AdamBrousseau** [adoptium/temurin-build#3337]
**What are you trying to do?**
https://github.com/adoptium/temurin-build/blob/1faf3ecc4903b2f562af15b28c15bff97f46c675/sign.sh#L66

serverTimestamp.properties
```
comodaca=http://timestamp.comodoca.com/authenticode
globalsign=http://timestamp.globalsign.com/scripts/timstamp.dll
isectigo=http://timestamp.sectigo.com
comodocarfc3161=http://timestamp.comodoca.com/rfc3161
startssl=http://tsa.startssl.com/rfc3161
starfieldtech=http://tsa.starfieldtech.com
digicert=http://timestamp.digicert.com
```
The `tr` in that line seems to be behaving differently than intended. It removes `r` character from digicert line. My build tries to use `http://timestamp.digicet.com` and fails.

Not sure if we need a different number of backslashes in that line or if we should try something else like
```
cut -d= -f2 < "$WORKSPACE/$TIMESTAMP_SERVER_CONFIG"
or
dos2unix < "$WORKSPACE/$TIMESTAMP_SERVER_CONFIG" | cut -d= -f2
```

cc @sxa original author https://github.com/adoptium/temurin-build/pull/2409

**Comment by AdamBrousseau** [comment]
In my fork I just removed the `tr` command and it seems to be working.

**Comment by sxa** [comment]
I'm not sure we can guarantee that `dos2unix` is available everywhere. As you say it's likely that the number of backslashes is incorrect. I guess it's quite unusual for it to fallback to the entry so far down in the list! Although if it's parsing the list without the `tr` now then it may be safe to remove it.
