### ISSUE TITLE
Gpg missing from AIX and Solaris machines

### ISSUE THREAD

**Issue by adamfarley** [adoptium/temurin-build#3357]
Thank you for reporting a broken build! Please fill in the following details:
- **Jenkins link to the failing log:**
[JDK17 on AIX](https://ci.adoptium.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-temurin/lastFailedBuild/console)
[JDK21 on AIX](https://ci.adoptium.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk/job/jdk-aix-ppc64-temurin/203/console)
[JDK8 on Solaris Sparc](https://ci.adoptium.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-sparcv9-temurin/lastFailedBuild/console)
[JDK8 on Solaris x64](https://ci.adoptium.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-temurin/lastFailedBuild/console)
- **Which platforms (OS+arch) are affected?:**
AIX, Solaris Sparc, and Solarix x64
- **If you look at the historic logs, does the problem appear to be specific to one machine?:**
No. All machines that reach the configure build step on these platforms see this issue.
- **Link to any upstream project bug report (e.g. [OpenJ9](https://github.com/eclipse-openj9/openj9/issues)/[JBS](https://bugs.openjdk.java.net/browse)):**
Likely connected to this: https://github.com/adoptium/temurin-build/pull/3356
**Error message**
```
13:06:07  BUILD_CONFIG[VENDOR]="Undefined Vendor"
13:06:07  BUILD_CONFIG[WORKING_DIR]="./build/"
13:06:07  BUILD_CONFIG[WORKSPACE_DIR]="/home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-aix-ppc64-temurin/workspace"
13:06:07  build.sh : 11:57:41 : Clearing out target dir ...
13:06:07  rm: cannot remove '/home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-aix-ppc64-temurin/workspace/target/': No such file or directory
13:06:07  build.sh : 11:57:41 : Configuring workspace inc. clone and cacerts generation ...
13:06:07  Checking and downloading Alsa dependency
13:06:07  Checking for ALSA
13:06:07    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
13:06:07                                   Dload  Upload   Total   Spent    Left  Speed
13:06:08  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  966k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 87  966k   87  848k    0     0   647k      0  0:00:01  0:00:01 --:--:--  646k
100  966k  100  966k    0     0   700k      0  0:00:01  0:00:01 --:--:--  700k
13:06:08    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
13:06:08                                   Dload  Upload   Total   Spent    Left  Speed
13:06:09  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0    583      0  0:00:01  0:00:01 --:--:--   583
13:06:09  /home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-aix-ppc64-temurin/sbin/prepareWorkspace.sh: line 307: gpg: command not found
```

**Comment by sxa** [comment]
As far as I can tell neither of these two platforms use ALSA, so the best solution here is to stop downloading it ...
