### ISSUE TITLE
tzdata is quite old in jdks

### ISSUE THREAD

**Issue by asmild** [adoptium/temurin-build#3362]
We faced a need of using Cairo TZ, but it appeared that in JDK the old one is used. We checked via tzupdater.jar and found that current JRE tzdata version is tzdata2022g. But latest one in that moment is tzdata2023c.

**Comment by karianna** [comment]
See https://github.com/adoptium/temurin-build/issues/1057 to resolve.

**Comment by asmild** [comment]
tzupdater doesn't solve my issue, otherwise I wouldn't come. I need new tzdata built-in in binaries.
