### ISSUE TITLE
Add Windows support for building from SBOM script

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3426]
The equivalent of https://github.com/adoptium/temurin-build/blob/master/tooling/linux_repro_build_compare.sh
needs adding for Windows and Mac

**Comment by andrew-m-leonard** [comment]
This is not as straight forward as linux, as it is not as easy to just download a specific version of Xcode or Visual Studio and use it, unlike Linux where we can just download the Adoptium gcc tarball and unzip.

**Comment by steelhead31** [comment]
Current WIP version of the script is here.. [https://github.com/steelhead31/temurin-build/blob/add_win_sbom_repro/tooling/windows_repro_build_compare.sh](https://github.com/steelhead31/temurin-build/blob/add_win_sbom_repro/tooling/windows_repro_build_compare.sh)     , needs some more tweaking to get built binary closer to identical.
