### ISSUE TITLE
remove signature error message with jdk17 windows-x64

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/temurin-build#3436]
Removing all Signatures from compared windows jdk get following error message

https://ci.adoptium.net/view/work-in-progress/job/jdk17u-windows-x64-temurin_reproduce_compare/13/console

```
 /cygdrive/j/jenkins/workspace/jdk17u-windows-x64-temurin_reproduce_compare/temurin-build/tooling/../../original
SignTool Error: CryptSIPRemoveSignedDataMsg returned error: 0x00000057

	The parameter is incorrect.
```

Sign temp signature and remove, no issues. Also seems its intermittently? Works sometime and fails some other time.

**Comment by andrew-m-leonard** [comment]
That usually means the target exe/dll has no signature

**Comment by andrew-m-leonard** [comment]
This is normal, it just means the given library was not signed.
