### ISSUE TITLE
Boot JDK signature verification failing on some EA builds 

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#3457]
Thank you for reporting a broken build! Please fill in the following details:
- **Jenkins link to the failing log:** https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-aarch64-temurin/255/console
- **Which platforms (OS+arch) are affected?:** Several, unclear what the common factor is, but we'll start with Linux/aarch64
- **If you look at the historic logs, does the problem appear to be specific to one machine?:** No
- **Link to any upstream project bug report (e.g. [OpenJ9](https://github.com/eclipse-openj9/openj9/issues)/[JBS](https://bugs.openjdk.java.net/browse)):** n/a

Note that the JDK22 pipeline support was recently reenabled in https://github.com/adoptium/ci-jenkins-pipelines/pull/775#pullrequestreview-1576240485 Linux/x64 did not seem to suffer the same problem. We have had issues in the past with directory name lengths for the signature verification, and aarch64 is certainly longer than x64 ([which is working ok](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-x64-temurin/413/consoleFull)) which may provide a clue although this failure isn't [the same error as before](https://github.com/adoptium/temurin-build/issues/3378).
```
00:30:57  [ unknown] (1). Adoptium GPG Key (DEB/RPM Signing Key) <temurin-dev@eclipse.org>
00:30:57  Please note that the shown key validity is not necessarily correct
00:30:57  unless you restart the program.
00:30:57  
00:30:57  gpg: no valid OpenPGP data found.
00:30:57  gpg: the signature could not be verified.
00:30:57  Please remember that the signature file (.sig or .asc)
00:30:57  should be the first file given on the command line.
```

**Comment by andrew-m-leonard** [comment]
The problem looks to be with the jdk-21+35 EA Bootjdk that is not GPG signed correctly on certain platforms.
The problem I think relates to the pipeline build of it here: https://ci.adoptium.net/job/build-scripts/job/openjdk21-pipeline/175/console
it looks like those platforms actually failed to build, but an "old" tar.gz got archived... i'm thinking the workspace wasn't cleaned so the copy artifact copied an old tarball... need to investigate further

**Comment by andrew-m-leonard** [comment]
https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21/job/jdk21-linux-aarch64-temurin/66/consoleFull
The jdk tarball was built successfully, but no GPG sign occured due to:
```
00:39:56  Execution error: hudson.AbortException: No item named jdk21-linux-aarch64-temurin_reproduce_compare found
```
The [download](https://github.com/adoptium/temurin-build/blob/530e49496c121edfc777a61e3c08da53f05bd345/build-farm/platform-specific-configurations/linux.sh#L174) of the bootjdk.tar.gz.sig, is actually returning:
```
Not Found
```

**Comment by andrew-m-leonard** [comment]
jdk-21+35-ea-beta re-built with missing platforms
