### ISSUE TITLE
Some sbom's missing FreeType version

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3493]
When temurin-build downloads FreeType because it is not on the System, then that gets logged in the SBOM.
However if there is a "System" freetype that is detected, then its details are not stored in the SBOM, ie.
https://github.com/adoptium/temurin-build/blob/751e5c8490e556e6c2db55018b048eb0e2f04eea/sbin/prepareWorkspace.sh#L455

**Comment by sxa** [comment]
Definitely sounds like a bug then, so my checks are failing correctly ;-)

**Comment by andrew-m-leonard** [comment]
@sxa
So our inclusion of FreeType is somewhat "mixed" and hard to understand, i've so far concluded:
- jdk8 will check for existence of installedfreetype directory on the build machine workspace and use that (but it's hard to know what version that lib is..?)
- jdk8 if installedfreetype does not exist, then it downloads into a folder "freetype" the [hard coded](https://github.com/adoptium/temurin-build/blob/751e5c8490e556e6c2db55018b048eb0e2f04eea/sbin/common/config_init.sh#L471) version, and builds it and installs it... then copies to directory installedfreetype. This scenario gets stored in SBOM
- jdk11+ skips checking/downloading "19:06:42  Skipping Freetype", and then default to whatever is the "System" freetype:
```
19:07:17  checking for FREETYPE... yes
19:07:17  checking for freetype... yes (using pkg-config)
19:07:17  Using freetype: system
```

**Comment by andrew-m-leonard** [comment]
@sxa Is there any reason we can't just use "Bundled" everywhere?

**Comment by sxa** [comment]
> @sxa Is there any reason we can't just use "Bundled" everywhere?

I don't know. I haven't really looked into it.
