### ISSUE TITLE
Windows & Mac compiler version in SBOM not in a unique field

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3503]
Currently the SBOM contains a Linux gcc/glibc version field, but there is no similar field for Windows VS C++ and Mac Xcode versions, the values are available from the "Tool Summary" field, subject to some text processing...

**Comment by sxa** [comment]
Thanks for creating this :-)

At the moment I'm having to feed the SBOM through this to pull out the correct compiler name/version from the windows and mac ones:
`jq '.components[0].properties[] | select(.name|test("Build Tools Summary")).value' | sed -e 's/^.*Toolchain: //g' -e 's/\*.*//g'`

Which gives me somethign like this:
- Windows: `microsoft (Microsoft Visual Studio 2019)`
- Mac: `clang (clang/LLVM from Xcode 10.3)`

Once this has been implemented I'll make the corresponding adjustments to the automation in https://github.com/adoptium/temurin-build/issues/3484
