### ISSUE TITLE
ubuntu-jre: no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by ValygarS** [adoptium/temurin-build#3510]
Hi, our Bitbucket Pipelines build for docker container started to fail.

`Step 1/9 : FROM adoptopenjdk/openjdk8:ubuntu-jre

ubuntu-jre: Pulling from adoptopenjdk/openjdk8

ubuntu-jre: Pulling from adoptopenjdk/openjdk8

no matching manifest for linux/amd64 in the manifest list entries`

I can see that "**ubuntu-jre**" tag was updated 2 days ago and currently architecture does not include linux/amd64.
While "**ubuntu-jre-nightly**" tag still includes linux/amd64 architecture.

Is this intended change or a bug?
Thanks

**Comment by karianna** [comment]
adoptopenjdk is no longer supported.  Please move to eclipse temurin images (where adoptopenjdk migrated to).
