### ISSUE TITLE
Fedora 39 support

### ISSUE THREAD

**Issue by bviktor** [adoptium/temurin-build#3525]
Hi, Fedora 39 has finally been released. As of now, the repo:

https://packages.adoptium.net/ui/native/rpm/fedora/

only has the builds up to 38, so I guess it's not an if, but a when question. So I think it'd be useful to have an issue to track the status of its support.

Thanks in advance.

**Comment by DenuxPlays** [comment]
I just use the 38 repo and it works. But yeah waiting ages is annoying

**Comment by bviktor** [comment]
I can't remember if I actually tried to install the older packages or not. In any case, we already have a 39 folder now, so I guess the issue can be closed? But it'd be great if someone from the devs chimed in.

**Comment by DenuxPlays** [comment]
Nope sadly not
![image](https://github.com/adoptium/temurin-build/assets/83671398/b5ea1fa1-6ca1-4566-a8c1-a014fc6700d5)

**Comment by steelhead31** [comment]
I believe support should have been added for 39 for the 2 most recent releases for each JDK version  
  
JDK8.0.402 & JDK8.0.412  
JDK11.0.22 & JDK11.0.23  
JDK17.0.10 & JDK17.0.11  
JDK21.0.2 & JDK21.0.3  
JDK22.0.0 & JDK22.0.1

Also Fedora40 was added in the release last week :)

**Comment by steelhead31** [comment]
Closing as completed
