### ISSUE TITLE
jdk17u Win32 build failure: Cannot open include file: 'sys/statfs.h'

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3527]
jdk17u Win32 builds broken: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-windows-x86-32-temurin/289/console
```
02:10:33  * For target support_test_jdk_jtreg_native_support_libGetXSpace_libGetXSpace.obj:
02:10:33  libGetXSpace.c
02:10:33  c:\workspace\openjdk-build\workspace\build\src\test\jdk\java\io\File\libGetXSpace.c(37): fatal error C1083: Cannot open include file: 'sys/statfs.h': No such file or directory
```

**Comment by sxa** [comment]
Oh that's the one I had to fix for JDK21 - needs `_WIN32` in the `#ifdef` replaced with a generic windows one. I was considering upstreaming that but I guess if it's been backported it's even more critical now

**Comment by sxa** [comment]
In discussion with Andrew about getting this fixed upstream since I have a patch that works.

**Comment by sxa** [comment]
Upstream PR to jdk22 codebase (draft until bug is created) https://github.com/openjdk/jdk/pull/16628/checks?check_run_id=18622446178
Testing against the same patch applied to the jdk17u codebase:
- [x64](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-windows-x64-temurin/391)
- [x86-32](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-windows-x86-32-temurin/292)
- [aarch64](https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk17u/job/jdk17u-evaluation-windows-aarch64-temurin/53)

**Comment by sxa** [comment]
Fix now in `jdk17u-dev`

**Comment by sxa** [comment]
Upstream patche merged therefore closing.
