### ISSUE TITLE
[SBOM] Add information about the job that generated the attested artifacts

### ISSUE THREAD

**Issue by netomi** [adoptium/temurin-build#3533]
The sbom should contain also a reference to the build that produces the artifact and provenance, e.g. the jenkins build url.

This information could be captured as property, e.g.

- name: "Build URL"
- value: "https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-aix-ppc64-temurin_SmokeTests/2/"

Furthermore, the sbom should capture information how the pipeline script was generated, i.e. include the following:

- reference the ci-jenkins-pipelines repo with digest
- reference the script that was used to generate the pipeline file

**Comment by netomi** [comment]
To give a reference how this is currently handled by SLSA. Here is an excerpt of the attestation produced for the slsa builder docker image as published here:

https://github.com/slsa-framework/slsa-github-generator/releases/download/v1.9.0/slsa-builder-docker-linux-amd64.intoto.jsonl

The reference to the actual build job is captured in metadata -> buildInvationId

![image](https://github.com/adoptium/temurin-build/assets/1048055/643366e5-f2ef-4ead-95f0-de2dc356816f)

to access the run you have to use figure out the url yourself:

https://github.com/slsa-framework/slsa-github-generator/actions/runs/5945355419-1

**Comment by sxa** [comment]
The `BUILD_URL` environment variable that gets passed from jenkins should be adequate for this.
There's also `RUN_DISPLAY_URL` but that redirects to a BlueOcean view.
We should also look at making sure that the release pipelines don't get deleted where possible, other than the attached artefacts (which will be stored in GitHub as well as on the parent pipeline)
