### ISSUE TITLE
[SBOM] Add information about the build environment / runner

### ISSUE THREAD

**Issue by netomi** [adoptium/temurin-build#3534]
Adding information about the jenkins runner itself that executes the build would allow to identify the exact build environment that has been used during a build.

The idea would be to include information like:

- docker image with digest that is being used to spin up the runner
- ansible playbook that was used to build the docker image (might not be needed if we have the above)

**Comment by sxa** [comment]
We could add the contents of the `NODE_NAME` environment variable too.

**Comment by sxa** [comment]
I believe this is good to close with the above PR
