### ISSUE TITLE
[SBOM] Capture all tools with their version / digest that are downloaded during a build

### ISSUE THREAD

**Issue by netomi** [adoptium/temurin-build#3535]
The sbom should capture all external tools with their version / digests that are downloaded during the build. This mainly concerns the cyclonedx tools / dependencies.

Ideally, in the long run, there should not be a need to download these tools externally for each build, but they could be hosted in a tool repository that is checked out using a defined commit during the build to avoid relying on external services as much as possible.

**Comment by sxa** [comment]
PR fo reht CycloneDX now merged, build.getDependencies re-run to pick up the new version, so #3538 can proceed
