### ISSUE TITLE
linux_repro_build_compare.sh get 'Could not determine one of the variables - run with sh -x to diagnose'

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/temurin-build#3542]
Rebuild the jdk by linux_repro_build_compare.sh and get 'Could not determine one of the variables - run with sh -x to diagnose'.

Looking at the code seems the the setting for variables need to update. https://github.com/adoptium/temurin-build/blob/master/tooling/linux_repro_build_compare.sh#L108-L114.

For example: 'configure_arguments' is not in SBOM json file.

**Comment by sophia-guo** [comment]
@andrew-m-leonard

**Comment by andrew-m-leonard** [comment]
@sophia-guo This script currently uses the SBOM "metadata" file not the SBOM json, it's something that needs changing
see issue https://github.com/adoptium/temurin-build/issues/3425
