### ISSUE TITLE
Temurin JAWT Native Cross Compilation

### ISSUE THREAD

**Issue by tilkinsc** [adoptium/temurin-build#3559]
**Problem description:**
I have a build box of flavor docker linux image. I am writing natives and need to support both windows and linux (and mac in the future). I am not sure a configuration of termurin that will allow me to generate `jdk/include/win32` and `jdk/include/linux` headers and `jdk/lib/jawt.so` and family and `jdk/lib/jawt.dll` and family. How do you suggest I tackle this problem? My concern here is that I don't want a build of temurin where one version drifts from another, so I am very skeptical about tracking two (possibly) identical builds from the website.

**Comment by karianna** [comment]
You won't be able to build a single JVM that supports all native platforms.  You'll have to build each one separately (there's not cross compile from Linux to Windows that I am aware of).
