### ISSUE TITLE
Openjdk8 native build issue due to freetype

### ISSUE THREAD

**Issue by Rakshiths09** [adoptium/temurin-build#3598]
Hi,
I am trying to build openjdk8 using temurin build scripts in cygwin. Environment is Windows 11 Visual studio code 2022.
Command executed in cygwin
**./makejdk-any-platform.sh --create-jre-image jdk8u**

Freetype is not getting compiled getting these errors

First I got ARCHITECTURE: unbound variable in build.sh
_if [ "${BUILD_CONFIG[OPENJDK_CORE_VERSION]}" = "${JDK8_CORE_VERSION}" ] && [ "${ARCHITECTURE}" = "64" ] && [ "${BUILD_CONFIG[BUILD_VARIANT]}" != "${BUILD_VARIANT_OPENJ9}" ]; then_
I changed to
_if [ "${BUILD_CONFIG[OPENJDK_CORE_VERSION]}" = "${JDK8_CORE_VERSION}" ] && [ "${BUILD_CONFIG[OS_ARCHITECTURE]}" = "x86_64" ] && [ "${BUILD_CONFIG[BUILD_VARIANT]}" != "${BUILD_VARIANT_OPENJ9}" ]; then_

Then got this error:
**configure : Trying to compile freetype sources with PlatformToolset=v143 to to /cygdrive/c/Openjdk8/temurin-build/workspace/libs/freetype/lib64
configure : User specified --with-freetype-src but building freetype failed** 

Thanks & Regards,
Rakshith S

**Comment by karianna** [comment]
@Rakshiths09 in build.sh on line 536 try removing:

jdk8* | jdk9* | jdk10*) addConfigureArg "--with-freetype-src=" "${BUILD_CONFIG[WORKSPACE_DIR]}/libs/freetype" ;;

**Comment by karianna** [comment]
Also the function at line 242 might give you a hint as to why the freetype failed.  The path to the frettype files probably doesn't exist for VS2022, you might be able to update the path

**Comment by karianna** [comment]
Not 100% sure Java 8 builds support using VS2022

**Comment by Rakshiths09** [comment]
Hi @karianna,
Changed the git hash tag for freetype to use version 2.8.1. Tried with VS2019. Build is successfull.
And can I build the jdk and jre with javafx included?

**Comment by karianna** [comment]
> Hi @karianna, Changed the git hash tag for freetype to use version 2.8.1. Tried with VS2019. Build is successfull. And can I build the jdk and jre with javafx included?

You'll need to look at the IcedTea project in the AdoptOpenJDK GitHub Org - I'm not really sure if there are up to date instructions
