### ISSUE TITLE
Installation of temurin-17-jre fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by f-cramer** [adoptium/temurin-build#3618]
**What are you trying to do?**
Installing temurin-17-jre on Ubuntu 22.04.3 on WSL 2
```
$ sudo apt install temurin-17-jre
```

**Expected behaviour:**
Installation succeeds

**Observed behaviour:**
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  adoptium-ca-certificates alsa-topology-conf alsa-ucm-conf fonts-dejavu-extra java-common libasound2 libasound2-data libxi6 libxrender1 libxtst6 p11-kit p11-kit-modules x11-common
Suggested packages:
  default-jre libasound2-plugins alsa-utils
The following NEW packages will be installed:
  adoptium-ca-certificates alsa-topology-conf alsa-ucm-conf fonts-dejavu-extra java-common libasound2 libasound2-data libxi6 libxrender1 libxtst6 p11-kit p11-kit-modules temurin-17-jre x11-common
0 upgraded, 14 newly installed, 0 to remove and 0 not upgraded.
Need to get 31.9 MB of archives.
After this operation, 153 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 p11-kit-modules amd64 0.24.0-6build1 [223 kB]
Get:2 https://adoptium.jfrog.io/artifactory/deb jammy/main amd64 adoptium-ca-certificates all 1.0.2-1 [2304 B]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 p11-kit amd64 0.24.0-6build1 [101 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 alsa-topology-conf all 1.2.5.1-2 [15.5 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libasound2-data all 1.2.6.1-1ubuntu1 [19.1 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libasound2 amd64 1.2.6.1-1ubuntu1 [390 kB]
Err:7 https://adoptium.jfrog.io/artifactory/deb jammy/main amd64 temurin-17-jre amd64 17.0.10.0.0+7
  400   [IP: 52.32.129.26 443]
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 alsa-ucm-conf all 1.2.6.3-1ubuntu1.9 [43.4 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-dejavu-extra all 2.37-2build1 [2041 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 java-common all 0.72build2 [6782 B]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxi6 amd64 2:1.8-1build1 [32.6 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxrender1 amd64 1:0.9.10-1build4 [19.7 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy/main amd64 x11-common all 1:7.7+23ubuntu2 [23.4 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Fetched 2931 kB in 1s (2306 kB/s)
E: Failed to fetch https://adoptium.jfrog.io/artifactory/deb/pool/main/t/temurin-${VERSION}/temurin-17-jre_17.0.10.0.0%2b7_amd64.deb  400   [IP: 52.32.129.26 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by karianna** [comment]
Can you try again, we've manually re-uploaded those packages.

**Comment by f-cramer** [comment]
Unfortunately it still does not work. The error is the same as before.
It seems to me that `apt` can't deal with `${VERSION}` in the url. I already tried to manually escaped the braces, but that only makes it worse, because apt then escapes the percentage sign.
I guess the best solution would be to move the `deb`-file to `temurin-17` like it is is for architectures other then amd64 and to edit `https://adoptium.jfrog.io/artifactory/deb/dists/jammy/main/binary-amd64/Packages` (including the compressed versions) afterwards. Artifactory might also be able to do the last step automatically, but I am not that familiar with it.

**Comment by sxa** [comment]
@f-cramer Have you done an `apt update`? When this was fixed yesterday I verified on a failing system (one that was showing exactly the problem you describe) and a new clean system that it was now resolved for both so this shouldn't be a problem any more .

**Comment by f-cramer** [comment]
I even deleted all cached entries in `/var/lib/apt/lists` before running `apt update`.
Which debian/ ubuntu version did you use for testing? Looking at https://adoptium.jfrog.io/artifactory/deb/dists/jammy/main/binary-amd64/Packages (the one for Ubuntu 22.04) there are multiple entries for `temurin-17-jre` with version `17.0.10.0.0+7`. The first one has the familiar `${VERSION}` as part of its file uri, the second one contains the right uri. Manually deleting the faulty entry solves the problem.

On another note: there are also two entries for `temurin-21-jdk` with version `21.0.2.0.0+13` and both have `${VERSION}` as part of their file uri.

**Comment by steelhead31** [comment]
@f-cramer would you mind trying this again, I've removed the errant files, and am investigating the underlying cause. I believe this should work now..

**Comment by steelhead31** [comment]
Ok, the packages are correct, but the metadata seems incorrect, I'll look into that now

**Comment by steelhead31** [comment]
@f-cramer .. ok .. once more, the package file looks correct now...

**Comment by f-cramer** [comment]
Works now (tested both Ubuntu Jammy and Debian Bullseye). Thanks for the help.
