### ISSUE TITLE
build.getDependency loses version information

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3646]
The artifacts stored in the https://ci.adoptium.net/job/build.getDependency/ have no version info, eg.in the name, which means the SBOM reference has a SHA but no version. For secure dev & reproducible reasons, we should add version information.

**Comment by sophia-guo** [comment]
Dup of https://github.com/adoptium/temurin-build/issues/3593 ?

**Comment by andrew-m-leonard** [comment]
> Dup of #3593 ?

yes thanks Sophia
