### ISSUE TITLE
GPG path lengths too long on RISC-V evaluation builds

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#3659]
Ref: https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk21u/job/jdk21u-evaluation-linux-riscv64-temurin/138/console (A re-run of the previous build to ensure it was running from the latest fixes in temurin-build):
```
10:31:54  GNUPGHOME=/mnt/disk-1/jenkins/workspace/build-scripts/jobs/evaluation/jobs/jdk21u/jdk21u-evaluation-linux-riscv64-temurin/workspace/.gpg-temp
10:31:54   10:31:53 up 51 days, 11:15,  0 users,  load average: 0.27, 0.08, 0.02
10:31:54  gpg: keybox '/mnt/disk-1/jenkins/workspace/build-scripts/jobs/evaluation/jobs/jdk21u/jdk21u-evaluation-linux-riscv64-temurin/workspace/.gpg-temp/pubring.kbx' created
10:32:00  gpg: connecting dirmngr at '/mnt/disk-1/jenkins/workspace/build-scripts/jobs/evaluation/jobs/jdk21u/jdk21u-evaluation-linux-riscv64-temurin/workspace/.gpg-temp/S.dirmngr' failed: File name too long
10:32:00  gpg: keyserver receive failed: No dirmngr
10:32:00  gpg recv-keys attempt has failed. Retrying after 10 second pause...
10:32:18  gpg: connecting dirmngr at '/mnt/disk-1/jenkins/workspace/build-scripts/jobs/evaluation/jobs/jdk21u/jdk21u-evaluation-linux-riscv64-temurin/workspace/.gpg-temp/S.dirmngr' failed: File name too long
10:32:18  gpg: keyserver receive failed: No dirmngr
```
FYI @luhenry @andrew-m-leonard since you've both been doing fixes in this area recently.

Related: https://github.com/adoptium/temurin-build/pull/3643  https://github.com/adoptium/temurin-build/pull/3630

**Comment by luhenry** [comment]
It is https://github.com/adoptium/temurin-build/commit/88fc1e54aed1f11c205236a364fd7453b0cea412 which will override `GNUPGHOME` when not on alpine. @andrew-m-leonard could you please fix/revert?

I also don't understand why it's not enough to set it in `build-farm/platform-specific-configurations/alpine-linux.sh` given it's loaded before `sbin/prepareWorkspace.sh`?

**Comment by andrew-m-leonard** [comment]
> prepareWorkspace

the build-farm/platform-specific-configurations/alpine-linux.sh is only called within a "build-farm" environment (Jenkins). If a user just builds locally using makejdk-any-platform.sh, then prepareWorkspace.sh(checkingAndDownloadingAlsa) will get called but the "build-farm" stuff is not.
