### ISSUE TITLE
ReproducibleCompare tests won't be triggered as dev.system

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/temurin-build#3674]
ReproducibleCompare tests won't be triggered as dev.system as it locates under functional/ folder.
https://ci.adoptium.net/job/Test_openjdk21_hs_dev.system_x86-64_linux/6/consoleFull
`15:19:20       [echo]  build.list is TestConfig/build.xml,system/build.xml `

As discussed in https://github.com/adoptium/temurin-build/issues/3587 we'd like move reproducible compare tests from dev.functional to dev.system but forgot the group is folder related. 

If we'd like to keep those tests as system we need to move those tests to system/ folder under https://github.com/adoptium/temurin-build/tree/master/test @smlambert ?

**Comment by smlambert** [comment]
Yes, while is not strictly necessary, it definitely helps make it clear where tests are categorized so please do move to a tests/system folder
