### ISSUE TITLE
Create a jdk21u s390x Linux DevKit toolchain

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#3700]
Parent: https://github.com/adoptium/temurin-build/issues/3468

Similar to the aarch64 issue at https://github.com/adoptium/temurin-build/issues/3519 this will cover the analysis required to create a devkit for JDK21+ on the Linux/s390x platform. Two options will be explored in parallel:

- Creating a Devkit using Fedora (Should be supported by the devkit process as-is)
- Creating a Devkit using RHEL using out ROSI subscription (May be more difficult as devkit does not explicitly support RHEL for this)

**Comment by sxa** [comment]
As part of this I'm trying to replicate the existing aarch64 centos7 devkit from @andrew-m-leonard 's work  as well as trying on Fedora so I'll log the findings. ABI=our build image

Distro+arch | Notes
---|---
C7ABI aarch64 |Completed successfully
Centos7.6.1810 aarch64 [1] | Completed successfully
Fedora34 aarch64 [2] | GCC 11.3.0; `undefined reference to operator delete(boid*, unsigned long)' in `read-md.c`.  May be due to [missing findutils](https://gcc.gnu.org/legacy-ml/gcc-help/2018-03/msg00017.html).
Fedora39 aarch64 [3] | `configure: error: Link tests are not allowed after GCC_NO_EXECUTABLES`
RH7API s390x | 
Fedora34 s390x | 
Fedora39 s390x | 

[1] - Uses gcc 4.8.5
[2] - Uses gcc 11.3.1
[3] - Uses gcc 13.2.1

It should be possible to download the prerequisite packages on RHEL7 using `yum install --downloadonly --downloaddir=$PWD <package names>` or `reinstall` if it's a package that you've already got. These operations still have to be run as `root` so that yum can get the lock

**Comment by sxa** [comment]
The important ones for the purposes if this issue are the `RH7API s390x` and `Fedora34 s390x (Target F19)` lines which indicate we can build a devkit that targets glibc 2.17 suitable for RHEL7.
I will attempt to verify that they are usable next week.

**Comment by sxa** [comment]
Right summary of devkits:
- RH7 on RH7: Did not work - `libstdc++.a(eh_throw.o)(.note.stapsdt+0x14): error: relocation refers to local symbol "" [9], which is defined in a discarded section`
- RH7 on RH7 without systemtap rpms available to devkit: **SUCCEEDED**
- F19 devkit on F34 (built on F34, without systemtap available during devkit build): Build failure in `systemMemoryBarrier_linux.cpp`: `error: 'SYS_membarrier' was not declared in this scope`
- RH7 devkit on F34 : Same error as previous line
- F19 devkit on RH7: **SUCCEEDED** (and `java -version` runs correctly)

**Comment by andrew-m-leonard** [comment]
excellent @sxa 
Do you have a F19 DevKit I can try building a JDK with to compare...?

**Comment by andrew-m-leonard** [comment]
@sxa i'm having issues with the F19 devkit, it seems some of the executables are picking up GLIBC_2.33 ?
```
﻿[root@s390x-kvm-016 openjdkbuild]# /root/devkit/bin/as --version
/root/devkit/bin/as: /usr/lib64/libc.so.6: version `GLIBC_2.33' not found (required by /root/devkit/bin/as)
```

**Comment by sxa** [comment]
> @sxa i'm having issues with the F19 devkit, it seems some of the executables are picking up GLIBC_2.33 ?

Yeah it hasn't worked as expected - there are still some dependencies coming from the host system for that one unfortuantely.

**Comment by sxa** [comment]
> - F19 devkit on RH7: SUCCEEDED (and java -version runs correctly)

It looks like I'd built the one I gave you was probably the one built with GCC11 on a Fedora34 host and so had some extra dependencies that it shouldn't have had. Now rebuilding with the RH7 system gcc (4.8.5) which should alleviate these errors
```
[sxa@devkitrh7bi s390x-linux-gnu-to-s390x-linux-gnu]$ ./s390x-linux-gnu/bin/ld --version
./s390x-linux-gnu/bin/ld: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./s390x-linux-gnu/bin/ld)
./s390x-linux-gnu/bin/ld: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./s390x-linux-gnu/bin/ld)
./s390x-linux-gnu/bin/ld: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./s390x-linux-gnu/bin/ld)
./s390x-linux-gnu/bin/ld: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./s390x-linux-gnu/bin/ld)
[sxa@devkitrh7bi s390x-linux-gnu-to-s390x-linux-gnu]$ 
```
@andrew-m-leonard There is a new version of in the same directory as the previous one as `F19devkitonF34.s390x.tar.xz`  (I'm keeping the location private for now as I don't want others downloading it while this is still in flux) which you can try.

**Comment by sxa** [comment]
A bit more experimentation - the reason for the `SYS_membarrier` error is because Fedora 19's glibc-headers package doesn't define it in `/usr/include/bits/syscall.h`. If you add a definition of that which is set to 356 (that value can be seen in later versions of fedora or CentOS9-stream in `asm/unistd_64.h `into the file then openjdk will compile ok.

Other things being tried. Note that all devkits referenced here are built without systemtap-sdt:

DK bld on | Devkit | jdk build on | Result
---|---|---|---
RH7bi | RH7 | RH7bi | ✅ 
RH7bi | F19 | RH7bi | ✅
F34 | F19 | F34 | ✅
? | RH7 | F34 | ✅
F28 | F19 | F28 | ✅ [1]
F28 | F19 | RH7bi | ❌ [2]

[1] - Requires glibc2.27 so will not run on a RHEL7 system
[2] -  libstdc++ symbol issues. Can resolve with LD_LIBRARY_PATH=<devkit>/lib64 but causes follow-on errors during compilation of adlc code.

Unfortunately (presumably due to things like glibc being at different patch levels, and it looks like [Fedora 19 came with gcc 4.8.1](https://archives.fedoraproject.org/pub/archive/fedora-secondary/releases/19/Everything/s390x/os/Packages/g/) instead of the 4.8.5 in later CentOS7 releases (For reference [CentOS 7.0.1406](https://vault.centos.org/centos/7.0.1406/os/x86_64/Packages/) had gcc 4.8.2) the builds using a Fedora19 devkit are not binary identical to those build using a RHEL7 devkit.

The only practical options for the devkit are to build and test a devkit on the host the devkit was built on, which should be RHEL7 in the absence of having a Fedora 19 system. The devkit can be from RHEL7 or Fedora 19.

And with that, I'm done :-)

**Comment by sxa** [comment]
Additional tests building openjdk 21 with the built devkits:

devkit | host | identical <sup>[1]</sup> | Runs on RH7?
---|---|---|---
RH7 | RH7bi | ✅ | ✅
RH7 | RH7bi | ✅ | ✅
F19 | RH7bi | ❌ <sup>[2]</sup> | ✅
RH7 | F34 | ✅ | ✅
F19 | F34 | ❌ <sup>[2]</sup> | ✅
RH7 | Ubu22.04 | ✅ | ✅
F19 (From F28) | F34 | ❌ <sup>[3]</sup> | ✅
F19 (From F28) | Ubu22.04 | ❌ <sup>[3]</sup> | ✅

<sup>[1]</sup> - Identical here means that there are no binary differences in anything within the final JDK tarball when comparing with the initial build from the first row in the table.
<sup>[2]</sup> - The builds with the Fedora 19 devkit are not the same but `java -version` runs correctly on RHEL7
<sup>[3]</sup> - The F19 devkit built on Fedora 28 <sup>[4]</sup>is not comparable with the ones from an F19 devkit built on RHEL7, but the jdk build does run on RHEL7, however they are NOT binary reproducible with the ones from the devkit used in the ones with footnote [2]. The two entries here with this footnote are binary identical.
<sup>[4]</sup> - While this was done using a F19 devkit built on Fedora 28 it is assumed that building the same F19 devkit on a later distribution would yield the same results, but this has not been explicitly verified.

**Conclusion:** To build a reproducible JDK you need to use the same devkit - you cannot build a devkit on one host system and expect the results from it to be identical to an "equivalent" devkit built in another environment. Based on this, the preferred option in order to meet the goal of using a devkit to produce something that works on RHEL7 is is to either use a RHEL7 devkit, or a Fedora19 devkit built on a well-defined fixed base OS. However, once we have the devkits produced we are not tied to running them on a RHEL7 system.

**Comment by sxa** [comment]
Next steps:
- Decide on the devkit to use
- Decide how/where to create it
- Incorporate it into the build process

Ideally the last of those will be including it into the build image as a replacement for the GCC11 that we currently install into `/usr/local/gcc11`

**Comment by sxa** [comment]
Some notes from when I was experimenting in case they're useful to others:
- to have a system suitable for building the devkit, install `make git gcc-c++ wget xz bzip2 m4 cpio util-linux gnupg patch bison texinfo file diffutils`
- You may also need `gnupg` on Fedora, plus `utils-linux` for `su` and `bzip2` plus `diffutils` and `patch`
- If you're on a plain CentOS7 or similar system, you'll need to [download and install GNU make 4.1](https://ftp.gnu.org/gnu/make/make-4.1.tar.gz) since the system one is too old
- `make TARGETS=s390x-linux-gnu BASE_OS=Fedora BASE_OS_VERSION=19`
- With Andrew's devkit patches applied, `make TARGETS=s390x-linux-gnu BASE_OS=Centos BASE_OS_VERSION=7.6.1810`
- If on RHEL7 (you probably will be for s390x) create `build/devkit/download/rpms/s390x-linux-gnu-Centos7.6.1810` and then `yum reinstall --downloadonly --downloaddir=build/devkit/download/rpms/s390x-linux-gnu-Centos7.6.1810` followed by the list of package names from Tools.mk **excluding systemtap-sdt**: `glibc glibc-headers glibc-devel cups-libs cups-devel libX11 libX11-devel xorg-x11-proto-devel alsa-lib alsa-lib-devel libXext libXext-devel libXtst libXtst-devel libXrender libXrender-devel libXrandr libXrandr-devel freetype freetype-devel libXt libXt-devel libSM libSM-devel libICE libICE-devel libXi libXi-devel libXdmcp libXdmcp-devel libXau libXau-devel libgcc libxcrypt zlib zlib-devel libffi libffi-devel fontconfig fontconfig-devel kernel-headers`
- To build the JDK on the resulting devkit you'll need some other packages (unless you're using a system set up with our playbooks): `git make procms-ng openssl diffutils autoconf bzip2 curl unzip zip` and `ant` if you want to do the SBoM creation.
- You should then be able to build the JDK with:
  - `git clone https://github.com/adoptium/temurin-build`
  - `cd temurin-build`
  - `./makejdk-any-platform.sh --jdk-boot-dir <somewhere> -configure-args "--disable-warnings-as-errors --with-devkit=<somewhere> --release -freetype-dir bundled jdk21u` - you can also have `--target-file-name something.tar.gz --build-variant temurin --create-sbom` before the `jdk21u` at the end if you so desire.

**Comment by sxa** [comment]
> switching the docker software used on the host back to the default docker from the RHEL repositories

Prototyping this on build-marist-rhel79-s390x-2 which has had the following changes applied:
- Registered via ROSI with the subscription-manager
- `rpm -e docker-ce docker-ce-rootless-extras docker-ce-cli` to remove the ones installed by the playbook
- yum install docker
- Verified that running the image with a volume mount seems to work ok, and that the UIDs are in sync
- Now running a [JDK21 build on the machine](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-s390x-temurin/107/) to verify correct operation.

<details>
<summary>Packages changed from switching from `docker-ca` to `docker`</summary>

```
sxa@fedora:~/rhel7-s390x$ diff packages.dockerce packages.docker
163c163,166
< docker-ce-25.0.5-1.el7.s390x
---
> oci-umount-2.5-3.el7.s390x
> oci-register-machine-0-6.git2b44233.el7.s390x
> device-mapper-persistent-data-0.8.5-3.el7_9.2.s390x
> docker-common-1.13.1-210.git7d71120.el7_9.s390x
355c358,359
< docker-ce-cli-25.0.5-1.el7.s390x
---
> yajl-2.0.4-4.el7.s390x
> oci-systemd-hook-0.2.0-1.git05e6923.el7_6.s390x
473c477,482
< docker-ce-rootless-extras-25.0.5-1.el7.s390x
---
> lvm2-libs-2.02.187-6.el7_9.5.s390x
> python-pytoml-0.1.14-1.git7dea353.el7.noarch
> docker-rhel-push-plugin-1.13.1-210.git7d71120.el7_9.s390x
> lvm2-2.02.187-6.el7_9.5.s390x
> containers-common-0.1.40-12.el7_9.s390x
> docker-client-1.13.1-210.git7d71120.el7_9.s390x
621a631,635
> device-mapper-event-libs-1.02.170-6.el7_9.5.s390x
> device-mapper-event-1.02.170-6.el7_9.5.s390x
> atomic-registries-1.22.1-33.gitb507039.el7_8.s390x
> container-storage-setup-0.11.0-2.git5eaf76c.el7.noarch
> docker-1.13.1-210.git7d71120.el7_9.s390x
sxa@fedora:~/rhel7-s390x$ 
```
</details>

**Comment by sxa** [comment]
OK the "fix" mentioned in the previous comment didn't work. Despite the rename fixing the jenkins connection issues, the machine (`build-2`)  still gave `fork` problems when running a build. I've switched it back to `docker-ce`  and repeating the test to verify if the problems are definitely related to the docker package or an issue with this specific machines which had been disabled previously. In parallel I will continue to run the tests using podman on the test-rhel8 machine.

**Comment by andrew-m-leonard** [comment]
> OK the "fix" mentioned in the previous comment didn't work. Despite the rename fixing the jenkins connection issues, the machine (`build-2`) still gave `fork` problems when running a build. I've switched it back to `docker-ce` [*] and repeating the test to verify if the problems are definitely related to the docker package or an issue with this specific machines which had been disabled previously. In parallel I will continue to run the tests using podman on the test-rhel8 machine.
> 
> [*] - `rpm -e docker docker-common docker-client` then `yum install docker-ce`

I tend to get fork resource errors on my local aarch64 VM, and I either have to reboot it, or build with less "jobs", eg.--with-jobs=4

**Comment by sxa** [comment]
Time for another table I think...

Machine | containers | [devkit build](https://ci.adoptium.net/job/build-scripts/job/utils/job/devkit/job/gcc-11.3.0/job/devkit-gcc-11.3.0-linux-s390x/) | [rhel7 container build](https://ci.adoptium.net/job/rhel7_docker_image_updater/) | [JDK build](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-s390x-temurin/)
---|---|---|---|---
build-rhel79-1 | docker-ce | ok on host | Needs old ROSI_ params | Good
build-rhel79-2 | docker | ok on host | [Good](https://ci.adoptium.net/job/rhel7_docker_image_updater/label=build-marist-rhel79-s390x-2/13/) | Failed
build-rhel79-2 | docker-ce | ? | Would need ROSI_params | ?
test-rhel8-2 | podman | Wrong version | Good | ?

**Comment by andrew-m-leonard** [comment]
Try changing this line https://github.com/adoptium/ci-jenkins-pipelines/blob/e297546378b5fbdb676223eb1ae2a0abe7406679/pipelines/build/common/openjdk_build_pipeline.groovy#L2049
to:
```
dockerRunArg += " --userns keep-id:uid=1002,gid=1003"
```

**Comment by sxa** [comment]
Good shout - I hadn't realised that we had some special logic in there to handle this. It took a bit more effort since podman seems to take quite a while to start up when using extra options like that and therefore hits the 180 second timeout for the docker launch:
```
6:33:57  $ docker run -t -d -u 1002:1003 -e BUILDIMAGESHA= --userns keep-id:uid=1003,gid=1002 -w /home/jenkins/workspace/sxa-jdk21u-s390x -v /home/jenkins/workspace/sxa-jdk21u-s390x:/home/jenkins/workspace/sxa-jdk21u-s390x:rw,z -v /home/jenkins/workspace/sxa-jdk21u-s390x@tmp:/home/jenkins/workspace/sxa-jdk21u-s390x@tmp:rw,z [...] rhel7_build_image.20240327.3efa1fc6 cat
16:36:57  ERROR: Timeout after 180 seconds
```
I got past that by starting up a container with the same options manually, waiting 5-10 minutes for it to run (it feels like it's duplicating the image since it chews up space during that time) after which the images start near-instantly. It will need to be seen whether this causes a problem when the images is rebuilt.

To use RHEL8+podman as per the above proposal we need to either:
1. Adjust the hard coding of uid=1000,gid=1000 to be 1002/1003
2. Do something else to dynamically set the UID correctly in podman
3. Change the UID of the jenkins user (and the rhel7_build_image) on the host system, probably via reprovisioning build-marist-rhel79-s390x-2 as a rhel8 system, prototyping on there with a new image, then look at migrating the second one.

I'm feeling that the reprovisioning option in 3 is good, subject to us being ok with only having one machine able to run the old stuff in the interim (Although the second one has been offline for a while anyway)

**Comment by sxa** [comment]
Suggestion from Severin to use `--userns=keep-id` for the mapping in the future https://github.com/adoptium/ci-jenkins-pipelines/pull/986#discussion_r1547828432

**Comment by sxa** [comment]
> 16:36:57  ERROR: Timeout after 180 seconds

Ref this - it seems to take about 5 minutes on the machine to complete the operation. It's not immediately obvious where that timeout is set (The 3 minutes seems to be from [this PR](https://github.com/jenkinsci/docker-workflow-plugin/commit/8c18b064335c3aafff770aa19f2e40c117c910c5) and can be overridden by `-org.jenkinsci.plugins.docker.workflow.client.DockerClient.CLIENT_TIMEOUT=600` as per [this comment](https://issues.jenkins.io/browse/JENKINS-42322?focusedCommentId=303679&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-303679) but that will require a restart, so we should do it in the next maintenance window.

**Comment by sxa** [comment]
I was hitting a failure due to the RHEL7 devkit not being correctly extracted from the host. In this case when you point `--with-devkit` at the directory (which was present, but empty) it falls back to the system compiler in a somewhat non-obvious way since it fails to notice the absence of the devkit:
```
09:21:14  * Toolchain:      gcc (GNU Compiler Collection)
09:21:14  * Devkit:         /usr/local/devkit/s390x-on-s390x
09:21:14  * C Compiler:     Version 4.8.5 (at /usr/bin/gcc)
09:21:14  * C++ Compiler:   Version 4.8.5 (at /usr/bin/g++)
```
It will then fail to compile and towards the end show messages about untracked files, which have nothing to do with the underlying issue but did confuse me for a while:
```
9:21:37  	bootjdk.tar.gz
09:21:37  	bootjdk.tar.gz.sig
09:21:37  	jdk-20/
09:21:37  	security/
```

**Comment by sxa** [comment]
Note that I have generated a new devkit tarball on the RHEL8 machine with the devkit.info file modified to have the expected line based on the `--with-adoptium-devkit` parameter and modified the rhel7 image creation job to use pick up the new tarball.
```
ADOPTIUM_DEVKIT_RELEASE=s390x-on-s390x.RH7
```
