### ISSUE TITLE
JDK22/mac/x64: No files included in stash 'jmods' 

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#3755]
Thank you for reporting a broken build! Please fill in the following details:
- **Jenkins link to the failing log:** https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk22u/job/jdk22u-release-mac-x64-temurin/4/console
- **Which platforms (OS+arch) are affected?:** Mac (both architectures)
- **If you look at the historic logs, does the problem appear to be specific to one machine?:** Unclear as we have just moved to jdk22u repository, but it's happening in jdk23 sine the build of the 28th March (21st was ok)
- **Link to any upstream project bug report (e.g. [OpenJ9](https://github.com/eclipse-openj9/openj9/issues)/[JBS](https://bugs.openjdk.java.net/browse)):**

**Comment by andrew-m-leonard** [comment]
Fixed by https://github.com/adoptium/ci-jenkins-pipelines/pull/1001
