### ISSUE TITLE
Windows x86 builds are missing

### ISSUE THREAD

**Issue by jpele-tis** [adoptium/temurin-build#3760]
Hello,
We're curious if there's a specific explanation for the absence of Windows x86 builds for the latest versions on compatible "versions" (8, 11, etc.).

![image](https://github.com/adoptium/temurin-build/assets/57767497/baee6694-6083-471d-a78a-59a10a6ccced)

**Comment by karianna** [comment]
Release is still underway, see adoptium.net banner for updates.
