### ISSUE TITLE
Upstream openjdk/jdk(head) now branching releases rather than forking

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3841]
openjdk/jdk(head) will now be doing release branching, no longer forking repositories. See: https://mail.openjdk.org/pipermail/jdk-dev/2024-March/008834.html

This obviously means our jdk(head) mirror and jdk-23+ build-scripts will need updating

We currently have:
- master : Direct mirror of openjdk/jdk(master)
- dev : Merge of Adoptium “patches” with master(HEAD)
- release : Sequential merge of latest jdk-NN+bb tags with Adoptium “patches” and tagged as jdk-NN+bb_adopt

With the branching of the upstream “jdk23” branch, we now have no view of jdk-23, as our “release” branch is now jdk-24+1_adopt, and “dev” is jdk-24(HEAD)

My immediate thought is:
- Add a "release_jdk23" branch, and update skaraMirror.sh to perform the same logic as before but from upstream “jdk23" branch, ie. sequential merging of latest jdk-23+nn tags with Adoptium "patches".
- Add a "dev_jdk23" branch, ie. jdk23(HEAD) merged with Adoptium "patches"
- temurin-build scripts updated for jdk-23+ targets to clone adoptium/jdk and checkout the appropriate "branch"

Thoughts?

**Comment by jerboaa** [comment]
> Seems reasonable - am I right in saying this is purely during the stabilization process and the `u` repositories are still expected to be produced for e,g, 23.0.1 and beyond?

Yes. There will be a separate discussion for update releases (covering the `23u` part) in the future. Let's keep this focused on the stabilization repo change only for now.

**Comment by jerboaa** [comment]
The EA build status messages on slack will need updating too. It currently claims newest build tag for JDK 23 is `24+1`, rather than `23+26`.

**Comment by sxa** [comment]
Re-opening as this is not closed until https://github.com/adoptium/temurin-build/pull/3852 is also merged.
