### ISSUE TITLE
jdk8u win32 failing to build freetype

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3865]
https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-temurin/478/
From freetype.log : 
```
  c1 : fatal error C1083: Cannot open source file: '..\..\..\src\base\ftfntfmt.c': No such file or directory [C:\workspace\openjdk-build\workspace\libs\freetype\builds\windows\vc2010\freetype.vcxproj]
```

ftfntfmt.c does not exist in freetype VER-2-5-3 that we are trying to build !
I think the problem is appearing due to recent change: https://github.com/adoptium/temurin-build/commit/7c3fe8eb949d33674133b2ccbde6ed642d81517a
although not entirely sure why yet

Suspect it's due to: # Don't apply the patch for OpenJ9 (OpenJ9 doesn't need the patch and, technically, it should only be applied for version 2.8.1).

**Comment by judovana** [comment]
So the guilty is I guess:
```
-  if ... [ "${ARCHITECTURE}" = "x64" ]...
+  if [ ... "${BUILD_CONFIG[OS_ARCHITECTURE]}" = "x86_64" ...]
```

Where indeed, it seems visible on various build combinations I'm running (eg https://github.com/adoptium/temurin-build/issues/3863 ) .  You had warrend me:
>  OS_ARCHITECTURE is the "BUILD arch", whereas ARCHITECTURE is the TARGET arch

So maybe that neeeds different arch?

**Comment by judovana** [comment]
Also note, that the GH actions were running in all cases, and passed.

**Comment by andrew-m-leonard** [comment]
> So the guilty is I guess:
> 
> ```
> -  if ... [ "${ARCHITECTURE}" = "x64" ]...
> +  if [ ... "${BUILD_CONFIG[OS_ARCHITECTURE]}" = "x86_64" ...]
> ```
> 
> Where indeed, it seems visible on various build combinations I'm running (eg #3863 ) . You had warrend me:
> 
> > OS_ARCHITECTURE is the "BUILD arch", whereas ARCHITECTURE is the TARGET arch
> 
> So maybe that neeeds different arch?

@judovana this check on build arch was a dubious way of checking for Freetype version 2.8.1 !

**Comment by judovana** [comment]
Indeed. I'm reading your fix for the issue. Surprsingly complex. Tahnx a lot!

**Comment by judovana** [comment]
Actuallyt he difference of 
```
jdk8u x86-32 uses Freetype 2.5.3
jdk8u x64 uses Freetype 2.8.1
```
Completly missed me:(

**Comment by judovana** [comment]
As @sxa is pointing out. The patching should go away :(
