### ISSUE TITLE
Workflow 'CA Certs Update' is not updating certdata.txt

### ISSUE THREAD

**Issue by jmjaffe37** [adoptium/temurin-build#3874]
**What are you trying to do?**
The workflow file [ca-cert-updater.yml](https://github.com/adoptium/temurin-build/blob/master/.github/workflows/ca-cert-updater.yml) is supposed to keep [certdata.txt](https://github.com/adoptium/temurin-build/blob/master/security/certdata.txt) up to date. This workflow runs on a cron job every night. A few days ago, Mozilla updated their `certdata.txt`, but the file in the current repo has not changed.

**Expected behaviour:**
certdata.txt should be updated to the latest file provided by Mozilla

**Observed behaviour:**
certdata.txt is currently set to the previous version (put out by Mozilla ~4 months ago)

**Any other comments:**
The link to the workflow file is incorrect in the README (it points to an old location of the workflow file, so it returns a 404):
https://github.com/adoptium/temurin-build/blob/master/security/README.md

**Comment by gdams** [comment]
The PR was raised here by the bot: https://github.com/adoptium/temurin-build/pull/3872

There were some unrelated CI failures but it should be good to merge. I'll get some approvals now
