### ISSUE TITLE
JDK21u: AIX: Java -version fails when it cannot load libc++.a(shr2_64.o)

### ISSUE THREAD

**Issue by adamfarley** [adoptium/temurin-build#3881]
**What are you trying to do?**

Run the smoke tests for a JDK21 build on AIX.

Example: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-aix-ppc64-temurin_SmokeTests/32/

**Expected behaviour:**

Expected to provide standard Java version output.

**Observed behaviour:**

```
21:30:02  =JAVA VERSION OUTPUT BEGIN=
21:30:02  Error: dl failure on line 533
21:30:02  Error: failed /home/jenkins/workspace/build-scripts/jobs/jdk21u/jdk21u-aix-ppc64-temurin_SmokeTests/jdkbinary/j2sdk-image/lib/server/libjvm.so, because 	0509-022 Cannot load module /home/jenkins/workspace/build-scripts/jobs/jdk21u/jdk21u-aix-ppc64-temurin_SmokeTests/jdkbinary/j2sdk-image/lib/server/libjvm.
21:30:02  	0509-150   Dependent module /usr/jdk-17.0.4+7/../lib/libc++.a(shr2_64.o) could not be loaded.
```

**Any other comments:**

Likely linked to https://github.com/adoptium/temurin-build/pull/3822

**Comment by sxa** [comment]
Change of plan - I've taken the easier approach of removing the xlc13 and xlc16 labels from the machine, so those builds should not get scheduled on it.

**Comment by aixtools** [comment]
is this still the _new_ system - `adopt09`?

**Comment by sxa** [comment]
> is this still the _new_ system - `adopt09`?

Yes.

**Comment by sxa** [comment]
I'm going to leave this machine without the older compiler labels so I'll close this.
