### ISSUE TITLE
Unable to build due to alsa-project.org unavailable

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3932]
https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-x64-temurin/273/console
```
14:57:42  curl: (28) Failed to connect to www.alsa-project.org port 443 after 134442 ms: Connection timed out
```
Nuremburg DC which hosts alsa-project.org is down, no current uptime, ref:
https://github.com/alsa-project/alsa-lib/issues/287#issuecomment-2324779730

Maybe we should have our own mirror/copy of ALSA ?

**Comment by steelhead31** [comment]
Alsa.org is now back up and available again.

**Comment by andrew-m-leonard** [comment]
Created new issue to cover resilience test? https://github.com/adoptium/temurin-build/issues/3936
