### ISSUE TITLE
Create a documented outline of the 3rd party Reproducible Attestation process

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3949]
**Process Outline:**

**At Adoptium:**
1. Temurin release build pipeline runs a new post-build job ("Verify Reproducible") step that verifies the success of the Rebuild_Same_JDK_Reproducibility_Test test
  - The Rebuild_Same_JDK_Reproducibility_Test reproducible nn% is then recorded by the "Verify Reproducible" job and creates a CycloneDX CDXA document with "evidence" from the test, and adds it to the build job artifacts for that platform, and updates the SBOM to reference via a bom-link the new CDXA BOM
2. The Temurin release is published to the temurinNN-binaries along with the SBOM + CDXA
3. The Temurin binary in the Marketplace is marked a **"Reproducible status - nn% - Pending 3rd party verification"**

**A 3rd Party:**
1. A "3rd party" performs an independent "Reproducible Verification Build" (https://adoptium.net/blog/2024/08/adoptium-reproducible-verification-builds/) of the same published Eclipse Temurin release
2. Assuming 100% successful, they record the necessary "evidence" in order to attest to the reproducibility of the Eclipse Temurin binary
3. Using a CDXA json file template (supplied by Eclipse Adoptium), they record the required attestion and evidence
4. The CDXA json file is "Signed" by the 3rd party Certificate. (mechanism??, ideally JSF using a PEM, but that may not be easy for 3rd party...)
5. The 3rd party uses the Adoptium Marketplace to place the Signed CDXA document into the marketplace folder. (**Q: This process implies the 3rd party must be an Adoptium Marketplace Member??**)
6. The receipt of the CDXA document by the Adoptium Marketplace triggers an automated "CDXA Verify Policy", which runs a script to validate the content and signature of the CDXA against the Adoptium binary and Adoptium CDXA.
7. If the "CDXA Verify Policy" is successful, then:
  - The Temurin artifact metadata is updated to record reproducibleVerified=true
  - The Temurin SBOM is updated with a bom-link to the purl of the 3rd party CDXA
  - The Adoptium Marketplace build entry gets a "Reproducible Verified" tick !

**Comment by andrew-m-leonard** [comment]
@tellison @jiekang @mbarbero Can I get your comments on above please? thanks

**Comment by michaelwinser** [comment]
I would change "Un-verified" to "Pending 3rd party verification" or something to that effect. Bonus, a link to "instructions on how to verify" so that any 3rd party could reproduce the build and provide an attestation would be interesting. Handwave. 

Assuming that "%age" is short for percentage, I'm not sure I understand it in this context.

I actually like that Step 5 requires that the verifier be a marketplace member unless the barrier to entry is too high. It changes the "someone verified this" to "someone known to us with some kind of contractual relationship verified this" or even better "Company X verified this." That means a lot to the consumer.

I think the reproducibleVerified attribute will need to be a counter and we will eventually want some way to get the list of verifiers.

We had discussed having a specific release for "reproducible" so that someone could query for builds that were reproducible. That might not be necessary but I do like the idea of a clear release type.

**Comment by andrew-m-leonard** [comment]
> I would change "Un-verified" to "Pending 3rd party verification" or something to that effect. Bonus, a link to "instructions on how to verify" so that any 3rd party could reproduce the build and provide an attestation would be interesting. Handwave.

Yep, changed.

> I actually like that Step 5 requires that the verifier be a marketplace member unless the barrier to entry is too high. It changes the "someone verified this" to "someone known to us with some kind of contractual relationship verified this" or even better "Company X verified this." That means a lot to the consumer.

Agree

> I think the reproducibleVerified attribute will need to be a counter and we will eventually want some way to get the list of verifiers.

Yes, that's probably what we will need

> We had discussed having a specific release for "reproducible" so that someone could query for builds that were reproducible. That might not be necessary but I do like the idea of a clear release type.

So the Adoptium API will be extended to return something like "latest&verified", which will return the latest artifact with reproducibleVerified>0, as opposed to "latest" which will return simply the latest as today.

**Comment by mbarbero** [comment]
Do you envision this as only being a way to a 3rd party to verify Adoptium's builds? It would mean that on page like this

![image](https://github.com/user-attachments/assets/0f911ca4-723e-4e2a-bca7-921532e6b5cb)

no other vendor than Adoptium would get the "verified" tick. Correct?

**Comment by smlambert** [comment]
> no vendor other than Adoptium would receive the "verified" tick. Is that correct?

true at this moment in time, but not necessarily in the future, since changes to support reproducibility were pushed upstream, to allow other distributors to also benefit

**Comment by tellison** [comment]
I'd like to separate out the basic mechanism of recording verification build attestations from the details of a visual depiction of a verification (tick marks etc), and the policy of who we recognise as a trusted verifier (working group members etc). Though I do strongly believe that the mechanism we pick should allow _anyone_ to record a verification attestation.

I propose:
(a) we store reproducibility attestations in a public immutable ledger (such as [Sigstore Rekor](https://docs.sigstore.dev/logging/overview/)) designed for this task, preferably hosted by the Eclipse Foundation itself.
(b) when Adoptium produces a Temurin binary and its associated SBOM, the SBOM contains a fixed attestation ledger URL.

 #### To record reproducible attestations

1. Anyone (including Adoptium) can use the SBOM to reproduce the Temurin binary, and record that fact in metadata. This is suggested above to be CDXA format.
1. Anyone can store their attestation metadata in the immutable ledger.

 #### To query reproducible attestations

1. The SBOM for a build includes the attestation ledger URL. All attestations can be retrieved by querying the ledger.
2. Adoptium will produce a new `api.adoptium.net` path to query the ledger and return the attestations for a build.

 #### Reproducible attestations depictions

1. The website can be updated to use the Adoptium API and depict attestations/verifications of binaries in a visually pleasing manner.
2. The project can decide to make some attestations more prominent (e.g. Working Group members), etc.

p.s. Although I reference Sigstore above, I do note that they don't list CycloneDX Attestations as a [currently supported type](https://github.com/sigstore/rekor/blob/main/pkg/types/README.md) - potentially requiring a [new definition](https://docs.sigstore.dev/logging/pluggable-types/). The store does support Intoto attestations today, but staying with CDX makes sense.

**Comment by mbarbero** [comment]
> Ideally using an Eclipse Founderation Rekor instance would be ideal. Does EF have a Sigstore Rekor instance already @mbarbero @netomi ?

No, we don't host our own Rekor instance, nor we plan to host one currently.

**Comment by andrew-m-leonard** [comment]
For the first pass, I propose we don't use a Rekor ledger, as it does not provide much use beyond what is already available as an Adoptium marketplace Vendor.
To properly leverage Rekor, we will need a more "public" writeable entry to the Adoptium MarketPlace.

**Comment by andrew-m-leonard** [comment]
Useful reference: https://stacklok.com/blog/decoding-rekor-understanding-sigstores-transparency-log

**Comment by andrew-m-leonard** [comment]
The plan for a April 2025 availability for this process following several technical discussions, is as follows:
- A new adoptium github repository will be created which will allow Pull Request contributions by any 3rd party, in which will be a CycloneDX CDXA attestation to the Verified Reproducible Build of a given Temurin JDK release.
- The CDXA document will need to be "signed" by the 3rd party and be validated as a valid CDXA format, with the necessary verification details within it.
- Once "Approved" by Adoptium reviewers, it will be merged into the repository, at which point the adoptium.net API server will discover it, and make the details available by an extended API metadata.
- The adoptium.net website will then also "flag" that the given 3rd party has independently verified the given Temurin JDK release binary.
