### ISSUE TITLE
Architect a "Verified Reproducible Build Attestation" Content

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3950]
Architect a "Verified Reproducible Build Attestation".

Some useful links:
- https://www.cisa.gov/sites/default/files/2024-03/CISA_RSAA_User_Guide_18_March_2024.pdf
- https://cyclonedx.org/capabilities/attestations/
- https://github.com/CycloneDX/specification/blob/master/tools/src/test/resources/1.6/valid-attestation-1.6.json
- https://github.com/in-toto/attestation/blob/main/README.md
- https://www.cisa.gov/resources-tools/resources/secure-software-development-attestation-form (and related DB for attestations and artifacts)
  - TODO, check if similar exists for EU
- https://www.cisa.gov/sites/default/files/2024-04/Self_Attestation_Common_Form_FINAL_508c.pdf
  - TODO, look at fields/requirements of the form and see if all are also valid for verification builds / as opposed to official published build)
- https://www.activestate.com/blog/everything-developers-need-to-know-about-attestations/
- https://cyclonedx.org/docs/1.6/json/#declarations_attestations
  - https://docs.google.com/presentation/d/13QP5Z5MRL-XtxEwTQ-JYy8x5_X884BmdEVkYLHt5PDk/edit#slide=id.g9d2ff71b8c_0_0

**Plan for 1Q 25:**
- [x] #4050
- [ ] #4051
- [ ] #4052
- [ ] #4053

**Comment by smlambert** [comment]
Also:
- https://www.cisa.gov/resources-tools/resources/secure-software-development-attestation-form (and related DB for attestations and artifacts) 
  - TODO, check if similar exists for EU
- https://www.cisa.gov/sites/default/files/2024-04/Self_Attestation_Common_Form_FINAL_508c.pdf 
  - TODO, look at fields/requirements of the form and see if all are also valid for verification builds / as opposed to official published build)
- https://www.activestate.com/blog/everything-developers-need-to-know-about-attestations/
- https://cyclonedx.org/docs/1.6/json/#declarations_attestations

**Comment by tellison** [comment]
[Sigstore](https://www.sigstore.dev/) seems to be a center of gravity in the secure supply chain processes.
We should seriously consider using the formats supported by [Rekor](https://github.com/sigstore/rekor) to be able to use that infrastructure downstream.

**Comment by andrew-m-leonard** [comment]
> [Sigstore](https://www.sigstore.dev/) seems to be a center of gravity in the secure supply chain processes. We should seriously consider using the formats supported by [Rekor](https://github.com/sigstore/rekor) to be able to use that infrastructure downstream.

An interesting read, this is what I understand from reading their various docs:
- CoSign's primary aim is in providing signing of "containers" stored in an OCI Registry.
- CoSign signing process is usually interactive involving opening of a Browser window for Identity verification during the signing
- CoSign keyless signing uses Rekor attestation ledger allowing "Signature" to be "verified" against the Rekor ledger entry identity and timestamp, hence does not require a "key"
- Rekor provides a append only transparency log, for things like attestations
- Rekor provide a public server: https://rekor.sigstore.dev

I take from that we could maybe:
- Using CoSign seems to be specific to keyless "Identity" based Signatures, it's usage for generic blob/artifact signing is not its main aim
- Rekor transparency log provides various pluggable formats including in-toto-attestations : https://github.com/sigstore/rekor/tree/main/pkg/types#currently-supported-types
  - Rekor also support generic types: https://docs.sigstore.dev/logging/sign-upload/
- Using Rekor transparency log, possibly the public one, could be a means for 3rd party reproducible attestation uploading. The public instance is limited to 100Kb attestation blobs
-

**Comment by smlambert** [comment]
https://github.com/in-toto/attestation/issues/82

**Comment by andrew-m-leonard** [comment]
> [in-toto/attestation#82](https://github.com/in-toto/attestation/issues/82) [in-toto/attestation#129](https://github.com/in-toto/attestation/pull/129)

Thanks Shelley, I am going to follow up with some questions to in-toto in their Slack

**Comment by andrew-m-leonard** [comment]
Further research, and references:
- in-toto attestation's are primarily targeted at automated policy engines, like in-toto-verify (and the associated in-toto-run'type interfaces) or Google [Binary-Authorization](https://cloud.google.com/binary-authorization) engine, which capture "attestations at the time of execution" : ref: https://github.com/in-toto/attestation/blob/main/spec/README.md#in-toto-attestation-framework-spec
- CycloneDX 1.6 attestations provide a full metadata declaration for attestations in the CDXA format : https://cyclonedx.org/capabilities/attestations/

**Comment by andrew-m-leonard** [comment]
I am currently thinking of this outline architecture:

1. Temurin build (temiurin-build) constructs a CycloneDX CDXA "provenance" attestation document at the end of the build along side the existing SBOM document, and links the SBOM->CDXA. The "**Adoptium signed**" CDXA will state the "provenance" of the built JDK tarball from an Adoptium "Producer" perspective, ie. something along the lines of a statement with evidence of "reproducible build", eg. binary hashes, and a "re-build" reproducible build evidence log?? Both SBOM and CDXA are published at release time.
2. A 3rd party performs a successful "[Reproducible Verification Build](https://adoptium.net/blog/2024/08/adoptium-reproducible-verification-builds/)", and creates their own "**3rd party signed**" consumer CDXA "provenance" attestation document, which documents their statement of evidence of "reproducible build" for the given Temurin release JDK tarball. The 3rd party then publishes this CDXA attestation document to the Adoptium marketplace: https://adoptium.net/marketplace/.
3. The last step by the Adoptium community as a consequence of a 3rd party publishing a "consumer" CDXA, is to run a "Verify" step, which compares the "producer" CDXA with the "consumer" CDXA, comparing the references and evidence, and upon success then lists the given 3rd party as "attesting" to the reproducibility of the given Temurin JDK release. This last step could also update a "reference", maybe a "bom-link" in the Temurin SBOM, to reference the "verified" consumer CDXA, the "version" number of the SBOM would be incremented by 1, as with accordance to the "[CycloneDX Authorative Guide to SBOMs](https://cyclonedx.org/guides/OWASP_CycloneDX-Authoritative-Guide-to-SBOM-en.pdf)".

**Future:**
- Add capability of 3rd party uploading a CycloneDX CDXA document to the public Sigstore Rekor instance, and allowing the step(3) "Verify" stage to reference the Rekor transparency log entry. The "bom-link" would then reference the Rekor entry.

**Comment by andrew-m-leonard** [comment]
From talking to members of the in-toto community, their suggestion points to looking at https://github.com/in-toto/witness
Which from the front cover looks a possibility.

**Comment by andrew-m-leonard** [comment]
**Option 2:**

- Temurin ci.adoptium.net pipeline produces an in-toto attestation of reproducible-build provenance using the in-toto-witness tooling
- 3rd party performs a Temurin re-build, and produces their own in-toto attestation using in-toto-witness
- Eclipse Adoptium runs an in-toto-policy verification using in-toto-witness that verifies the Adoptium attestation and the 3rd party attestation evidence matches, to attest the claim of an independent Verified Reproducible Build
-

**Comment by andrew-m-leonard** [comment]
Plan for 1Q 25:
- Create a CycloneDX CDXA json document
- Provide a temurin-build cycloneDX tooling CLI to create CDXA

**Comment by andrew-m-leonard** [comment]
@tellison @smlambert @jiekang My thoughts on what is in the CDXA: https://github.com/adoptium/temurin-build/issues/3950#issuecomment-2488344806

**Comment by jiekang** [comment]
I think the Target->component entry should have the full name of the file (e.g. `OpenJDK21U-jdk_x64_linux_hotspot_21.0.5_11.tar.gz`)

Though that made me look at the releases page and now wonder what we should plan for staticlibs, debugimage, testimage, and jre artifacts...

**Comment by smlambert** [comment]
> I think the Target->component entry should have the full name of the file (e.g. OpenJDK21U-jdk_x64_linux_hotspot_21.0.5_11.tar.gz)

Not opposed to the suggestion, but want to mention that the full name of the artifact will feature in the url to the binaries repo

**Comment by andrew-m-leonard** [comment]
> > I think the Target->component entry should have the full name of the file (e.g. OpenJDK21U-jdk_x64_linux_hotspot_21.0.5_11.tar.gz)
> 
> Not opposed to the suggestion, but want to mention that the full name of the artifact will feature in the url to the binaries repo

yes that was my original thought too

**Comment by tellison** [comment]
> > > I think the Target->component entry should have the full name of the file (e.g. OpenJDK21U-jdk_x64_linux_hotspot_21.0.5_11.tar.gz)
> > 
> > 
> > Not opposed to the suggestion, but want to mention that the full name of the artifact will feature in the url to the binaries repo
> 
> yes that was my original thought too

Or preferably, a stable URL link to the asset via the Adoptium API rather than straight to the storage (just to avoid building dependencies on the storage implementation into the CDXA)

e.g. https://api.adoptium.net/v3/binary/version/jdk-21.0.5+11/linux/x64/jdk/hotspot/normal/eclipse

**Comment by andrew-m-leonard** [comment]
A generated example:
```
{
  "bomFormat" : "CycloneDX",
  "specVersion" : "1.6",
  "version" : 1,
  "declarations" : {
    "assessors" : [
      {
        "thirdParty" : true,
        "organization" : {
          "name" : "Acme Inc"
        },
        "bom-ref" : "assessor-1"
      }
    ],
    "attestations" : [
      {
        "summary" : "Eclipse Temurin Attestation",
        "assessor" : "assessor-1",
        "map" : [
          {
            "claims" : [
              "claim-1"
            ]
          }
        ]
      }
    ],
    "claims" : [
      {
        "target" : "target-jdk-1",
        "predicate" : "VERIFIED_REPRODUCIBLE_BUILD",
        "bom-ref" : "claim-1"
      }
    ],
    "targets" : {
      "components" : [
        {
          "type" : "application",
          "bom-ref" : "target-jdk-1",
          "name" : "Temurin jdk-21.0.5+11 x64 Linux",
          "externalReferences" : [
            {
              "type" : "distribution",
              "url" : "https://api.adoptium.net/v3/binary/version/jdk-21.0.5+11/linux/x64/jdk/hotspot/normal/eclipse",
              "hashes" : [
                {
                  "alg" : "SHA-256",
                  "content" : "abcdefg0123456789"
                }
              ]
            }
          ]
        }
      ]
    },
    "affirmation" : {
      "statement" : "Acme confirms a verified reproducible build",
      "signatories" : [
        {
          "organization" : {
            "name" : "Acme Inc"
          },
          "externalReference" : {
            "type" : "website",
            "url" : "https://acme-inc.com"
          }
        }
      ]
    }
  }
}
```

**Comment by andrew-m-leonard** [comment]
And here is the same using XML output:
```
<?xml version="1.0" encoding="UTF-8"?>
<bom serialNumber="urn:uuid:4068785d-f37f-4c56-b0c5-1951d2ec375b" version="1" xmlns="http://cyclonedx.org/schema/bom/1.6">
  <declarations>
    <assessors>
      <assessors bom-ref="assessor-1">
        <thirdParty>true</thirdParty>
        <organization>
          <name>Acme Inc</name>
        </organization>
      </assessors>
    </assessors>
    <attestations>
      <attestation>
        <summary>Eclipse Temurin Attestation</summary>
        <assessor>assessor-1</assessor>
        <map>
          <claims>
            <claim>claim-1</claim>
          </claims>
        </map>
      </attestation>
    </attestations>
    <claims>
      <claim bom-ref="claim-1">
        <target>target-jdk-1</target>
        <predicate>VERIFIED_REPRODUCIBLE_BUILD</predicate>
      </claim>
    </claims>
    <targets>
      <components>
        <component type="application" bom-ref="target-jdk-1">
          <name>Temurin jdk-21.0.5+11 x64 Linux</name>
          <externalReferences>
            <reference type="distribution">
              <url>https://api.adoptium.net/v3/binary/version/jdk-21.0.5+11/linux/x64/jdk/hotspot/normal/eclipse</url>
              <hashes>
                <hash alg="SHA-256">abcdefg0123456789</hash>
              </hashes>
            </reference>
          </externalReferences>
        </component>
      </components>
    </targets>
    <affirmation>
      <statement>Acme confirms a verified reproducible build</statement>
      <signatories>
        <signatory>
          <organization>
            <name>Acme Inc</name>
          </organization>
          <externalReference type="website">
            <url>https://acme-inc.com</url>
          </externalReference>
        </signatory>
      </signatories>
    </affirmation>
  </declarations>
</bom>
```

**Comment by andrew-m-leonard** [comment]
For Q1 '25, the above CDXA.xml will be used: https://github.com/adoptium/temurin-build/issues/3950#issuecomment-2503602280
