### ISSUE TITLE
SBoM content is missing `r` and `n` characters in component package names

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#3960]
**What are you trying to do?** look at the SBoM for e.g. Linux/aarch64 at https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4%2B7/OpenJDK21U-sbom_aarch64_linux_hotspot_21.0.4_7.json

**Expected behaviour:** Components/[n]/properties elements look like this:
```
name	"openssl-libs-1.0.2k-26.el7_9.aarch64"
value	"openssl-libs-1.0.2k-26.el7_9.aarch64"
```

**Observed behaviour:** `r` and `n` characters are absent, suggesting maybe there is an incorrectly escaped translation of package names with `\n` and `\r` operations.
```
name	"opessl-libs-1.0.2k-26.el7_9.aach64"
value	"opessl-libs-1.0.2k-26.el7_9.aach64"
```

**Any other comments:**

**Comment by jiekang** [comment]
Possibly the code around:

https://github.com/adoptium/temurin-build/blame/79bb2763471fbe65ecb101d94e470514024bf7f9/tooling/strace_analysis.sh#L261
