### ISSUE TITLE
how to get the libfreetype version and sourcecode

### ISSUE THREAD

**Issue by whfjam** [adoptium/temurin-build#4006]
**What are you trying to do?**

i have a jdk version  (8.0_202-b08) (build 1.8.0_202-b08)  and i got the shared lib file libfreetype.so.6 in the path jre\lib\amd64 
the shared library cause the app crashed

**Expected behaviour:**

i want to know the version of  libfreetype.so.6 the jdk used or the source code

**Observed behaviour:**

**Any other comments:**

**Comment by karianna** [comment]
@whfjam if it's the shared lib then it's the one your OS provides.  If it's bundled with the JVM then you need to check the source code, look for opnejdk jdk8u on github

**Comment by whfjam** [comment]
I download the jdk from https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u202b08.tar.gz  then the jdk includes the shared lib  libfreetype.so.6  in path jre\lib\amd64， also it is a debug version，there is no source code in jdk，i had searched alot for this just got the message like “the lib is from where the open jdk was built” ，so it  is not from my OS，and also there is no source code in open jdk

**Comment by karianna** [comment]
It's version 2.4.0 for that version of Java.  Please note that we no longer support 8_202
