### ISSUE TITLE
ain't there no new Temurin packages for Debian yet?

### ISSUE THREAD

**Issue by harridu** [adoptium/temurin-build#4010]
**Problem description:**
Would it be possible to include Debian and RPM packages into the regular build and release procedure, to avoid long delays between the release of the *.tar.gz files and the installer packages? Thank you in advance.

I would need a reliable release procedure of Debian packages to schedule regular maintenance updates of my systems.

**Comment by harridu** [comment]
This report is about having **regular** Debian and RPM packages, released in parallel to the *.tar.gz in the temurinxx-binaries repositories.

**Comment by karianna** [comment]
This is already being worked on in the installer repo.
