### ISSUE TITLE
[JDK 24] Enable JEP 493 in Temurin 24 builds

### ISSUE THREAD

**Issue by jerboaa** [adoptium/temurin-build#4035]
Description
-----------------
[JEP 493](https://openjdk.org/jeps/493) has this summary:

```
Reduce the size of the JDK by approximately 25% by enabling the jlink tool
to create custom run-time images without using the JDK's JMOD files. This
feature must be enabled when the JDK is built; it will not be enabled by
default, and some JDK vendors may choose not to enable it.
```

Proposal
-----------------
Add `--enable-linkable-runtime` to Temurin 24 builds so as to enable this feature. It only affects users running `jlink` so as to produce custom runtimes. The nice property would be that the Temurin 24 JDK would ship without `jmods` directory by default. In order to cover cases where a link from the run-time image is not suitable I suggest to also package the jmods image as a separate artefact (like `testimage`, `static-libs` and friends) and make those available for each build via the API for users actually needing them.

Pros
-----------------
By default, the Temurin 24 JDK download shrinks in size without any restrictions in terms of run-time needs. `jlink` users should be able to use it to link custom runtimes.

Cons
-----------------
Certain use-cases might not be possible. For example, cross linking, linking from a modified runtime. See [JEP 493](https://openjdk.org/jeps/493) for details. For those users there would be the option to download the `jmods` artefact separately and get the same features as JDK 23+ had.

**Comment by sxa** [comment]
Test build (locked) with the parameter enabled is at https://github.com/adoptium/temurin-build/issues/4035 if anyone wants to play

**Comment by judovana** [comment]
The jemods  (like testimage, static-libs and friends)  should be also separate rpms subpkg.

**Comment by jerboaa** [comment]
> The jmods (like testimage, static-libs and friends) should be also separate rpms subpkg.

Please file this in https://github.com/adoptium/installer/issues Thanks!

**Comment by jerboaa** [comment]
Agreed to enable this for JDK 24 at the PMC meeting on Wednesday Nov. 13. For now we won't package the jmods image, which might change if there is user-demand.

**Comment by sxa** [comment]
Quick point of note - this is all documented somewhere but we do have multiple options for where such options can be set:
- [The pipeline configs](https://github.com/adoptium/ci-jenkins-pipelines/tree/master/pipelines/jobs/configurations) - probably the easiest to start with as it can be easily added only to the jdk24 one
- [linux.sh and friends in the temurin-build repo](https://github.com/adoptium/temurin-build/tree/master/build-farm/platform-specific-configurations)
- [The stuff in `sbin` in the temurin-build repo](https://github.com/adoptium/temurin-build/tree/master/sbin)

**Comment by jerboaa** [comment]
PR enabling this option is here: https://github.com/adoptium/temurin-build/pull/4039

**Comment by jerboaa** [comment]
> PR enabling this option is here: #4039

I'm working on added smoke tests for this. Any build with it should have this output in `jlink --help`

```
$ ./jdk-24+23/bin/jlink --help | tail -n2
Capabilities:
      Linking from run-time image enabled
```

**Comment by jerboaa** [comment]
PR with a smoke test is here: #4040

**Comment by judovana** [comment]
Just for record, I had added the testing of jmod-less ,age to gihub actions of jlink testsuite. Will merge it once jdk24 is out (it now correctly fails) https://github.com/rh-openjdk/jlinktests/pull/7

**Comment by ingokegel** [comment]
@jerboaa 
> Agreed to enable this for JDK 24 at the PMC meeting on Wednesday Nov. 13. For now we won't package the jmods image, which might change if there is user-demand.

Without JMODs, cross-linking is no longer possible. For example, install4j creates JDK bundles for multiple target platforms on any platforms. Without JMODs being available in some form, we would have to drop Adoptium from the list of supported JDK providers. Would it be an option to publish the JMODs separately as well?

**Comment by ingokegel** [comment]
@jerboaa Thank you, I have created https://github.com/adoptium/adoptium-support/issues/1271
