### ISSUE TITLE
Bug: Repository release branches don't have mandatory PR review

### ISSUE THREAD

**Issue by adamfarley** [adoptium/temurin-build#4045]
**Summary**

Build repo release branches should have a mandatory PR review, and don't.

**Observed behaviour:**

Build repository release branches don't have a mandatory PR review.

This is probably because the settings regex does not match.

**Any other comments:**

Original comment: 

https://github.com/adoptium/temurin/issues/54#issuecomment-2341767847

Put in backlog, assign to Andrew (tech debt - critical)

**Comment by andrew-m-leonard** [comment]
Otterdog pattern for branch selectiojn: https://ruby-doc.org/core-2.5.1/File.html#method-c-fnmatch
