### ISSUE TITLE
release branch approval is currently only 1 review, should it be 2 ?

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#4047]
build repo and aqa-test "release" branch PRs have only 1 approver, should it be 2 ?

**Comment by smlambert** [comment]
we decided for aqa-tests branches that we only needed 1 reviewer, as the PRs being merged into branches should be almost exclusively items cherry-picked from master

**Comment by andrew-m-leonard** [comment]
Completed, decission to use 2 reviews for build repo release branches, now implemented.
