### ISSUE TITLE
Windows Reproducible Build Script - Ant Download And Install Fails

### ISSUE THREAD

**Issue by steelhead31** [adoptium/temurin-build#4062]
**What are you trying to do?**

The windows reproducible build script fails when trying to download and install a version of Ant deduced from the SBOM ( see 

[**https://ci.adoptium.net/job/Test_openjdk21_hs_special.system_x86-64_windows/8/consoleFull**](https://ci.adoptium.net/job/Test_openjdk21_hs_special.system_x86-64_windows/8/consoleFull)

The reproducible build test deduced a requirement of Ant 1.10.5 from the SBOM, however newer machines (  test-azure-win2022-x64-4 )  only have the later Ant Version 1.10.15 installed. The jenkins automated process however has insufficient permissions to install an older version.

**Expected behaviour:**

**Test should run ok with any suitable version of Ant.**

**Observed behaviour:**

**Test fails, when it should either detect a suitable version (  either  1.10.XXXX is allowed or ANY version of Ant is allowed )**

**Any other comments:**

**Comment by andrew-m-leonard** [comment]
Yes, lets relax the ant version
