### ISSUE TITLE
The --openjdk-source-location is broken since PR#2702

### ISSUE THREAD

**Issue by judovana** [adoptium/temurin-build#4065]
The https://github.com/adoptium/temurin-build/pull/2702/files#diff-bf1a71b6b982bb100bd797f1aac5049b232b43398baf9494c8f2823c62c8aa82R519 have enforced the copying of  .git sources, where the `--openjdk-source-location` literally intentionally excludes `.git` from being duplicated.

The basic command of  `./makejdk-any-platform.sh --openjdk-source-location  ~/git/jdk21u/ jdk21u` do not trigger the issue (obviously), but hte `  ./makejdk-any-platform.sh --openjdk-source-location  ~/git/jdk21u/ --create-source-archive  jdk21u
` 
<details>
 <summary>originally reported was </summary>
`./makejdk-any-platform.sh --openjdk-source-location  ~/git/jdk21u/ --clean-git-repo --jdk-boot-dir /usr/lib/jvm/java-21-openjdk  --configure-args "--disable-warnings-as-errors --enable-dtrace" --destination build_artifacts --target-file-name jdk21.tar.gz --create-source-archive --create-jre-image --create-debug-image --create-sbom --enable-sbom-strace --freetype-dir bundled --skip-alsa --build-variant hotspot jdk21u
`
</details>

I would like to  add condition to existence of .git before `mv`:
```
   echo "Temporarily moving VCS source dir to ${tmpSourceVCS}"
  - mv "${sourceDir}/.git" "${tmpSourceVCS}"
  + if [ -e "${sourceDir}/.git" ] ; then mv "${sourceDir}/.git" "${tmpSourceVCS}" ; fi
   echo "Temporarily moving source dir to ${sourceArchiveTargetPath}"
```

@sxa  @jerboaa  wdyt?

**Comment by judovana** [comment]
or maybe not copyit at all? I would not expected the .git in sources snaphsot.   In addition it is huge. maybe do it optional? Like `--create-source-archive` ahving optional parametr of  "also git" ?

**Comment by jerboaa** [comment]
> I would like to add condition to existence of .git before `mv`:
> 
> ```
>    echo "Temporarily moving VCS source dir to ${tmpSourceVCS}"
>   - mv "${sourceDir}/.git" "${tmpSourceVCS}"
>   + if [ -e "${sourceDir}/.git" ] ; then mv "${sourceDir}/.git" "${tmpSourceVCS}" ; fi
>    echo "Temporarily moving source dir to ${sourceArchiveTargetPath}"
> ```

Seems sensible. The restoration part of the git dir needs to be handled similarly. I don't think the source archive should include any version control files (-1 on just not doing the moving the directory away temporarily). If it's not there to begin with we don't need to move it away, so fine with me.

**Comment by sxa** [comment]
+1 from me to everything Severin said above :-)

**Comment by judovana** [comment]
Thanx! Will do. 

@jerboaa  "The restoration part of the git dir needs to be handled similarly. " I do not parse. Do you suggest if `--openjdk-source-location tarballOrdir` is there, and it contains .git,  it should be extracted/copied?

**Comment by judovana** [comment]
The intetional skip is done here: https://github.com/adoptium/temurin-build/pull/3737/files#diff-1968af21c421fa9d7903dcd8950e640bc8ae257b7d7c5768c0fdd64d95fe3d7aR44  Maybe it should be dropped then.

**Comment by judovana** [comment]
> Thanx! Will do.
> 
> @jerboaa "The restoration part of the git dir needs to be handled similarly. " I do not parse. Do you suggest if `--openjdk-source-location tarballOrDir` is there, and it contains .git, it should be extracted/copied?

Oh, now I hit the `Restoring VCS source dir`. Clear now.

**Comment by judovana** [comment]
Should be fixed by https://github.com/adoptium/temurin-build/pull/4066
