### ISSUE TITLE
Reproducible test failure on Windows

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin-build#4096]
I spotted this a few days ago but I don't think it's been raised (If so, feel free to close this as a duplicate)
This seems to have been in [all runs of special.system](https://ci.adoptium.net/job/Test_openjdk21_hs_special.system_x86-64_windows) since job 27 on the 5th December: 
```
18:09:15  Reading The SBOM Content & Validating The Structure..
18:09:15  
18:09:15  SBOM Is Structurally Sound.. Extracting Values:
18:09:15  
18:09:15  assertion "cb == jq_util_input_next_input_cb" failed: file "/cygdrive/d/a/scallywag/jq/jq-1.7-1.x86_64/src/jq-1.7/src/util.c", line 381, function: jq_util_input_get_position
18:09:16  -----------------------------------
18:09:16  Rebuild_Same_JDK_Reproducibility_Test_win_0_FAILED
18:09:16  -----------------------------------
```

**Comment by adamfarley** [comment]
I haven't seen this, and I'm not aware of any dups.

For completeness, here's when you first noted this problem: https://github.com/adoptium/infrastructure/issues/3286#issuecomment-2507707091

**Comment by adamfarley** [comment]
The [internet suggests](https://stackoverflow.com/questions/71662276/jq-not-processing-a-json-file-in-cygwin) an sbom formatting issue. Didn't we update cygwin recently? We should check out the sbom formatting.

**Comment by sxa** [comment]
> Didn't we update cygwin recently? 

Not explicitly. The build machines were new installs from the playbooks but this failure is occurring on the test machines where we run the reproducible test.

**Comment by andrew-m-leonard** [comment]
It's the update to CDX 1.6 spec where metadata.tools has been deprecated in favour of new tools information "components" format
