### ISSUE TITLE
Ability to apply http proxy parameters to the build scripts

### ISSUE THREAD

**Issue by goafabric** [adoptium/temurin-build#426]
Inside my company I am behind a proxy.
The build system (MacOS) is configured to use the proxy, environment variables (http(s) proxy ) are also set.
But the makejdk-any-platform fails with e.g:  
Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease  
The http proxy parameters of the system do not seem to be honoured.
So it would be great to at least have an option to apply them via the command line.

**Comment by M-Davies** [comment]
@goafabric Apologies for the long silence. If you still can, can you post the exact ./makejdk-any-platform command you are using? If not, can you remember if you were trying to build using docker or on the host system?

**Comment by hege-li** [comment]
Works fine here for host system build, by simply setting these:

export http_proxy=proxy.server:8080
export https_proxy=proxy.server:8080
export JAVA_OPTS="-Dhttp.proxyHost=proxy.server -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxy.server -Dhttps.proxyPort=8080"

Atleast the JAVA_OPTS bit was crucial so gradle stuff works.

**Comment by hendrikebbers** [comment]
@goafabric can you check if `makejdk-any-platform` works in your environment by using the given params?
